### ISSUE TITLE
Remove use of "right click" descriptions in API methods

### ISSUE THREAD

**Issue by ChloeDawn** [TheIllusiveC4/Curios#102]
**Please describe the new feature or change.**

Rename `canRightClickEquip` to `canEquipFromHotbar` and `playRightClickEquipSound` to  `playHotbarEquipSound` (or similar, TBC).

**Please describe why you want this feature.**
The implication that the player is right-clicking is (presumably) based upon common Forge events such as `PlayerInteractEvent.RightClickItem`, however, these names are bad, because the player isn't always right-clicking in these contexts - right-clicking is just the default keybinding for "use". I don't think new APIs should be using this legacy terminology going forward.

**Comment by TheIllusiveC4** [comment]
You bring up a good point. I'll add in new renamed methods (which will also address your other issue about additional context) for the current API version and deprecate the existing ones, with eventual removal when appropriate, to avoid continued use of the misleading terminology.
