### ISSUE TITLE
Adding a head slot for the Create goggles

### ISSUE THREAD

**Issue by ktkk** [TheIllusiveC4/Curios#103]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.16.4-4.0.3.5
* Create: 1.16.3+4_v0.3
* Forge/Fabric: 35.1.28
#### Steps to Reproduce:
1. Created a new slot following the guide.
2. Equip the Create goggles in the default helmet slot: tool tip shown.
3. Equip the Create goggles in the new Curio slot: no tool tip shown

**Comment by TheIllusiveC4** [comment]
This is probably because Create is checking specifically for the helmet slot, so you cannot have this functional in your custom Head slot. You'd need to ask for integration directly from the Create developers.

**Comment by StormDragon-64** [comment]
try doing this in create 0.3.2c, because according [to the wiki](https://create.fandom.com/wiki/Engineer%27s_Goggles) "The goggle overlay can now be activated by external add-ons"
