### ISSUE TITLE
Configuration 1.16.4

### ISSUE THREAD

**Issue by CythonDotPyc** [TheIllusiveC4/Curios#105]

**Comment by CythonDotPyc** [comment]
How to configure quantity of some slot? I know about /curious add, but it adds only for one player, and other players wont have a additional slot.

**Comment by TheIllusiveC4** [comment]
Check out the wiki section for users
https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users

It explains how to configure slot settings universally.
