### ISSUE TITLE
Curios Button Clips With Quark Backpack

### ISSUE THREAD

**Issue by BookerCatch** [TheIllusiveC4/Curios#110]
The GUI button to open the Curios screen clips with the player model in the inventory screen when the Quark backpack is equipped. This is because the backpack shifts the inventory slots up and resizes the GUI, but the Curios button does not change in position.

I saw you implemented this QoL fix for Diet, and it would be nice if it were also implemented for the Curios button.
![Capture](https://user-images.githubusercontent.com/43504436/109989537-959ef400-7cd6-11eb-8f7e-2ad60fc1d821.PNG)

**Comment by TheIllusiveC4** [comment]
https://github.com/TheIllusiveC4/Curios/pull/119
