### ISSUE TITLE
[Fabric] Outdated REI causing issues in dev

### ISSUE THREAD

**Issue by AzureDoom** [TheIllusiveC4/Curios#112]
* Curios: 0.0.12-1.16.5
* Forge/Fabric: Fabric

You are shipping a super old REI version, which cause issues with newer versions in development.

**Comment by TheIllusiveC4** [comment]
I've released the 0.13 update that should address this. It uses the updated version that you PRed but also removes REI as an implementation-level dependency so that Curios no longer ships it at all to avoid this issue in the future.
