### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Archerelly** [TheIllusiveC4/Curios#115]
#### Versions (Be specific, do not write "latest"):
* Curios: 4.0.5.0
* Forge/Fabric: Forge 36.0.58
* Curious Elytra 4.0.2.3
#### Steps to Reproduce:
1. Open inventory.
2. Put Elytra (from Curious Elytra) into back slot.
3. Game crash
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
Minecraft just says "Unexpected game crash"

**Comment by TheIllusiveC4** [comment]
I can't be sure since I don't know your Caelus version, but this sounds like a similar issue I heard about so I think you just need to update Caelus to 2.1.3.0.
