### ISSUE TITLE
Curios Gui Missing

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TheIllusiveC4/Curios#116]
I noticed in my modpack [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato) that the Curios GUI was missing the hand slot when I tried to use the Curious Knuckles. I then created a new instance with only Curios and JEI. What I found was the four default items in Curios namely: Curious Amulet, Curious Crown, Curious Knuckles, and Curious Ring can not be used if no other Curios compatible mods are installed. So in the case of my pack, no 3rd party mod had added a slot for hands, so I could not use the Knuckles.

#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.5-4.0.5.0
* Forge/Fabric: Forge 36.1.0
* OS: Pop OS (based on ubuntu 20.04)
#### Observed Behavior: 
Curios GUI will not open if no Curios compatible mods are installed.
#### Expected Behavior: 
The Curios GUI should work as a standalone if it is going to come with the four default items.
#### Steps to Reproduce:
1. Make a new instance of Minecraft 1.16.5
2. Install forge 36.1.0
3. Install Curios and JEI
4. Launch and make a new world
5. Open inventory and attempt to open Curios GUI

![image](https://user-images.githubusercontent.com/17887664/112212873-1fa9f080-8be3-11eb-8810-469ffe037a91.png)

[debug.log](https://github.com/TheIllusiveC4/Curios/files/6192418/debug.log)
[latest.log](https://github.com/TheIllusiveC4/Curios/files/6192419/latest.log)

**Comment by TheIllusiveC4** [comment]
The four items are normally unobtainable except in Creative mode, so there's no reason to supply default slots.

If you're designing your modpack so that they're obtainable, either through custom recipes or rewards, then it's expected that you configure your user's slots as illustrated [here](https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users) so that they're available.

**Comment by ClaudiusMinimus** [comment]
Thank you
