### ISSUE TITLE
Curios menu not accessible when joining server, both with LAN server and with actual dedicated server

### ISSUE THREAD

**Issue by ShardPerson** [TheIllusiveC4/Curios#117]
-->
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.5-4.0.5.0
* Forge/Fabric: 36.1.0
* 
* When joining a server, Lan or dedicated, the curios menu is not accessible, the icon is there but it doesn't do anything
#### Steps to Reproduce:
1. Install curios and any mod that uses curios in your server
2. Access the server from another computer if it's a single player world open to LAN, or simply access it if it's a dedicated server
3. Attempt to open the Curios menu, it simply won't open at all

**Comment by TheIllusiveC4** [comment]
Which mod that uses Curios did you install for your reproduction step?
