### ISSUE TITLE
so I downloaded curious and any modded item that effects the look of my character causes my game to crash anyone know why

### ISSUE THREAD

**Issue by Adriborg8** [TheIllusiveC4/Curios#118]
any modded item that changes my look crashes the game and I have no idea why it doesn't matter which mod the item is from relics artifacts etc... it doesn't change anything so it has to be a problem with curios 
AND THERE IS NO CRASH LOG BECAUSE I spent 30 minutes trying to get a crash log but it's an instantly freeze and close game crash and then I have to load a backup because it CORRUPTS THE ENTIRE MINECRAFT WORLD and all I get is "ERROR Game crashed An unexpected issue occurred and the game has crashed. We,re sorry for the inconvenience" this message is from minecraft launcher.

**Comment by TheIllusiveC4** [comment]
As explained in our Discord discussion, you just need to update your Caelus version to 2.1.3.0+.
