### ISSUE TITLE
Curios throws an exception at startup, but not always?

### ISSUE THREAD

**Issue by stashymane** [TheIllusiveC4/Curios#12]
#### Versions:
* Curios: 0.22
* Forge: 28.0.46
####
Curios throws an exception before the title screen. I used to be able to solve this by starting the game with only Curios and mods dependent on it installed and only then installing other mods, however that no longer works. Sometimes this exception is accompanied by another mod's exception, like, in this case, the shulker boxes addon. The only mods installed are Caelus, Curios, Curio of Undying, Curious Elytra and Curious Shulker Boxes.
I don't know where to post this bug report as sometimes Curios doesn't even crash, but the other addons do. It's random most of the time.

Crash Log: https://hastebin.com/avicihowuv.sql

**Comment by TheIllusiveC4** [comment]
I was able to reproduce this somewhat, but it's a difficult issue to try and address considering its random nature. Regardless, I've tried to fix this in version 0.23. I haven't encountered the issue anymore after repeatedly starting up Minecraft, but again, it's hard to tell if it's been fully addressed. Please try out Curios version 0.23 and tell me if you're still encountering the startup errors (with the crash logs).

**Comment by stashymane** [comment]
Still happens with the rest of my mods on. Any other mod installed beside Curios and it's addons causes this.
[crash.log](https://github.com/TheIllusiveC4/Curios/files/3531340/crash.log)

**Comment by TheIllusiveC4** [comment]
How consistently does this occur? 
Is it only Curios crashing or is it the same behavior as before where the addons may crash as well? 
Does it not happen if it's only Curios and its addons?

**Comment by TheIllusiveC4** [comment]
Okay, made another attempt at this. Please try out Curios version 0.24 and tell me if you're still encountering startup errors. Note that you might still see startup crashes from the add-ons or any of my other mods, but the focus should be on if Curios itself crashes.

**Comment by stashymane** [comment]
Most of the time the crash does not happen on first startup anymore, instead on the 2nd launch of the game. It crashes with only Curios and it's addons installed about half the time, however when it crashes once it will not stop crashing no matter what until I remove it all. Somehow gets fixed after a few tries and fiddling with my mod list (removing everything then adding it back, removing curios, etc.)
Currently trying the new build, no issues so far.
