### ISSUE TITLE
Slot Item does not give the bonuses

### ISSUE THREAD

**Issue by heilong-studios** [TheIllusiveC4/Curios#123]
Just followed the tag guide
#### Versions (Be specific, do not write "latest"):
* Curios: 1.16.5
* Forge/Fabric: 1.16.5
* Quark-r2.4-309

**Comment by TheIllusiveC4** [comment]
If it's attribute modifiers you're talking about, then you either need to attach a `CurioAttributeModifiers` tag like you would a regular `AttributeModifiers` tag from vanilla or ask Quark to add Curios integration to that item. Just adding it as tag won't be enough to provide you with actual functionality while in the slot.
