### ISSUE TITLE
[1.16.5] Snow attributes for all Curios Slots

### ISSUE THREAD

**Issue by Rumaruka** [TheIllusiveC4/Curios#125]
Hello, I'm developing my mod and my idea is that - my items can be used for all slots - Inventory or Curios, but look image
Can I hide this? If I don`t, Can you make features? :)
Thanks!

![image](https://user-images.githubusercontent.com/8148679/114717041-188f8180-9d4e-11eb-8674-302c0ed769f9.png)
![image](https://user-images.githubusercontent.com/8148679/114717053-19c0ae80-9d4e-11eb-8de6-087d5eba9bdf.png)

**Comment by TheIllusiveC4** [comment]
Yes, you can hide it.

Return `false` in `ICurio#showAttributesTooltip`:
https://github.com/TheIllusiveC4/Curios/blob/57d890980bbdddd38e3433ebfa8460d668675b62/src/main/java/top/theillusivec4/curios/api/type/capability/ICurio.java#L284
