### ISSUE TITLE
Bug where items drop when you die and recover your items with tombstone mod

### ISSUE THREAD

**Issue by NuGearv2** [TheIllusiveC4/Curios#130]
Some items dont stay in their slots after death. when u go back to collect your items from ur tombstone. the item will be in ur main inventory n not the slot you placed it in. it can also drop if u have a full inventory an you dont have space for it.

egs are - items for Curios slot alone (works with any slot)

             - items that have multiple types (ring. necklace. bracelet ECT

 
i hope you will read this and work on the few that can we worked on. i enjoy this mod and i hope to see some of these issues resolved.
Last edited by geartestv2

**Comment by TheIllusiveC4** [comment]
Please follow the bug report template. I need version numbers for Forge and Curios, and I need you to list specific steps to reproduce the issue and specify which items are involved.
