### ISSUE TITLE
Disappearing Curious menu with plugins

### ISSUE THREAD

**Issue by Gawello** [TheIllusiveC4/Curios#131]
Hi,
I have a problem with disappearing menu. When I add plugin SkinRestorer, slots and menu of Curious mod doesn't work. After I type "/kill" and respawn menu starts working again, until I leave the server. When I reconnect, the problem returns.

Versions:
curios-forge-1.16.5-4.0.5.0
SkinRestorer v14.0.2
Server engine - Cauldron Mohist - Build #453 1.16.5 (java8)

When I delete plugin, everything works perfectly. Is there a way to keep both? (plugin and mod)
I have "premium" MC version but one of my friend not.
Pls help :(

**Comment by fullshadowcat** [comment]
Also faced with this problem, had to give up skins.

**Comment by cabinary** [comment]
Wow, I have the same problem, but I don't know that is only because a skin plugin problem. I use MySkin plugin in my server, and curios returns to normal after unload the plugin.
It seems that if want to show skin, could only set "online-mode=true" and give up all skin plugins.

**Comment by Sam-Wave** [comment]
Same here, but if I go to nether and back, it work until restart.

**Comment by TheIllusiveC4** [comment]
Unfortunately, I don't think I can solve this issue as I do not develop nor provide support for environments with plugins. If anyone has any further inputs about a possible solution on my end, please feel free to interject.
