### ISSUE TITLE
Unable to load saves.

### ISSUE THREAD

**Issue by Wondering-Oracle** [TheIllusiveC4/Curios#133]
#### Versions (Be specific, do not write "latest"):
* Curios: 0.0.13
* Forge/Fabric: Fabric 0.11.3
#### Observed Behavior:
Unable to load saves or create new ones.
#### Steps to Reproduce:
1. Attempt to load a save or create a new one.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No crash, game freezes and needs to be ended from task manager

**Comment by TheIllusiveC4** [comment]
Fabric API and Cardinal Components API versions?

**Comment by Wondering-Oracle** [comment]
Fabric API: 0.34.2
Cardinal Components: 2.72

**Comment by TheIllusiveC4** [comment]
You need to update Cardinal Components to 2.8.2 if you're using Fabric API 0.34+.

**Comment by Wondering-Oracle** [comment]
oh, sorry
