### ISSUE TITLE
Game locks up upon any world being loaded.

### ISSUE THREAD

**Issue by MagmaSlime123** [TheIllusiveC4/Curios#137]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-fabric-0.0.13-1.16.5
* Forge/Fabric: Read above. Using Fabric.
#### Steps to Reproduce:
Load a world.

Crash Log: No report is given. Logs below.
[latest.log](https://github.com/TheIllusiveC4/Curios/files/6487665/latest.log)

**Comment by TheIllusiveC4** [comment]
Likely a duplicate of https://github.com/TheIllusiveC4/Curios/issues/133

Update Cardinal Components API to 2.8.2+.

**Comment by MagmaSlime123** [comment]
Isn't that built into the mod.

**Comment by TheIllusiveC4** [comment]
Yes, but you can download and use a more recent version of CCA yourself that will override the embedded one. That's the temporary solution until I update the Curios dependencies.

**Comment by MagmaSlime123** [comment]
Oh, alright. Thanks, sorry for the duplicate issue. Didn't know this was already reported.
