### ISSUE TITLE
Creative Mode Issue

### ISSUE THREAD

**Issue by Foozey** [TheIllusiveC4/Curios#142]
If you're in creative mode, then click survival inventory, then click the Curios button, the recipe book button is missing. The diet button from your diet mod is there, however the recipe book button is not. Not too sure if this is an issue with Curios or even something you can resolve. But as usual, thought I'd let you know in-case you can do something about it.

**Comment by kristibektashi** [comment]
> If you're in creative mode, then click survival inventory, then click the Curios button, the recipe book button is missing. The diet button from your diet mod is there, however the recipe book button is not. Not too sure if this is an issue with Curios or even something you can resolve. But as usual, thought I'd let you know in-case you can do something about it.

You mean the one that shows crafting recipes? That one is purposely turned off by Mojang, it doesn't show up in creative mode even in vanilla Minecraft. Curios has nothing to do with it
