### ISSUE TITLE
Can't load on server

### ISSUE THREAD

**Issue by Rushmore75** [TheIllusiveC4/Curios#144]
When I try and load a moded server using this mod as well as some others (such as backpacked, tetra, etc.) but is crashes and says "Backpacked only supports curios 4.0.1.0 or above"
"Currently, curios is 1.16.5-4.0.5.1"
curios is definitely above the required version. But it doesn't realize it...

**Comment by TheIllusiveC4** [comment]
I believe this was fixed from Backpacked's end, make sure you've downloaded the latest version.
