### ISSUE TITLE
[1.16.5 Forge] Opening Curios inventory closes the recipe book

### ISSUE THREAD

**Issue by ocram9** [TheIllusiveC4/Curios#149]
#### Versions:
* Curios: 1.16.5-4.0.5.2
* Forge: 36.1.32

#### Observed Behavior: 
When you open the curios inventory with the recipe book open, it closes the book. When you then open the recipe book again the curios inventory stays open and you can close it with the recipe book remaining open.

#### Steps to Reproduce:
1. Open recipe book
2. Open curios inventory
3. Open recipe book again, then close the curios inventory and repeat

**Comment by DrunkBlood** [comment]
See #138
