### ISSUE TITLE
[1.14.4] Client-Server-Client desync + question

### ISSUE THREAD

**Issue by Shazuli** [TheIllusiveC4/Curios#15]
#### Versions (Be specific, do not write "latest"):
* Curios: FORGE-1.14.4-0.25
* Forge: 28.0.49
#### Observed Behavior:
When a player has logged out and then in again other player's rendered accessories do not show until they have updated the item manually.

![curios_bug2](https://user-images.githubusercontent.com/9884180/64544748-cee7e500-d327-11e9-9ef5-082163b813eb.gif)

#### Expected Behavior:
The layer should be rendered again when a new player logs in.

#### Steps to Reproduce:
Have two accounts login in on the same server and have one of the wear an accessory and logout with the other account and in again and the other player should not have their accessories be visible until they update them manually.

### Question
You can see I have a "band" (is going to be a watch render) rendered on the player's left arm, but I have problems with Z-fighting which is a bit hard to see in the video. How did you make so it doesn't happen on the head? I can't have the box size being rendered be fractions so I can't have it be rendered a little bit over the skin.

**Comment by TheIllusiveC4** [comment]
I'll look into the desync.

As for the question, I don't do anything to combat Z-fighting. That's entirely based on your model and how you render it. Can you not just scale your model up a little bit so that it isn't lined up to the player model?

**Comment by Shazuli** [comment]
Oh, I didn't notice you could have the scale factor be fractions, I thought it could only have whole numbers like the size arguments. Thanks!
