### ISSUE TITLE
Configurable slot layouts

### ISSUE THREAD

**Issue by ThePiekar** [TheIllusiveC4/Curios#150]
**Please describe the new feature or change.**
A config option, that would let you assign slot types to different columns, 
so that instead of all slots being displayed in a single column,
you'd be able to for instance, have all your rings in an additional column further left.
Maybe even let the items be sorted in rows instead of colums for more customization.

**Please describe why you want this feature.**
I've noticed that having too many slots, results in having a scroll bar that lets you navigate them all.
It's a decent solution but gets quite tiresome to use when frequently swapping items.

I think it would be nice to let players and modpack makers customize the layout of slots for feel/ease of play purposes.

**Comment by TheIllusiveC4** [comment]
The new GUI introduced in 1.20.1 and 1.20.4+ uses a couple configuration options in `curios-server.toml` to manipulate the slot layout, allowing users and modpack developers to change column, row, and page amounts to better suit their particular environment's slot configuration. It's not quite as customizable as the original feature suggestion but it's much more configurable than it was previously.
