### ISSUE TITLE
I can't equip the items in the curios slots

### ISSUE THREAD

**Issue by MAXIS05** [TheIllusiveC4/Curios#151]
* Curios: curios-forge-1.16.5-4.0.5.2
* Forge/Fabric: 1.16.5-forge-36.1.0

#### Observed Behavior:
 The items mods to add tags to in data packages, does not show curios info and are not added to the corresponding slots

#### Expected Behavior: 
be able to insert the items in the slots

#### Steps to Reproduce:
I followed all the steps in the user guide, create the frequent slots, assign the tags to the items for the respective slots and it doesn't seem to work

note:
the mods are mekanism and create, I read that some mods are not configured so that their effects work in the curiosity slots, but I can't even equip them

**Comment by TheIllusiveC4** [comment]
If the items don't show the tooltip information for Curios, then the tags were not set up correctly. Can you share the data pack you used to create the tags?

**Comment by MAXIS05** [comment]
[datapacks.zip](https://github.com/TheIllusiveC4/Curios/files/6721706/datapacks.zip)

I'm surely doing something wrong, but I can't find where the error is, I tried with the lenses of the create mod (later I read that it is not compatible but I should be able to put it in the slot), with the extendible arm of create, and with the jetpack of the mod mekanism ...
with curiosity you can add any item to the slots, even if they don't have a use or effect?

**Comment by TheIllusiveC4** [comment]
The file should be called `pack.mcmeta` not `pack.mcmeta.json` like you have now.

> with curiosity you can add any item to the slots, even if they don't have a use or effect?

Yes.

**Comment by MAXIS05** [comment]
The file is not called pack.mcmeta.json, I have it pack.mcmeta in the folder, .json is the type of file, what type it has to be, I also tried with notepad and it is the same

**Comment by TheIllusiveC4** [comment]
That's what I'm telling you to change. It's not supposed to be a .json file, it's supposed to be a .mcmeta file. To illustrate my point, your pack doesn't work when it's a `pack.mcmeta.json` file but when I changed it to `pack.mcmeta` then it works perfectly. That's the sole source of your issue from what I can tell.

**Comment by MAXIS05** [comment]
I knew that there was something I was doing wrong, I could still clarify in the guide that the file is format ".mcmeta", since for those of us who do not know that type of format, the name pack.mcmeta leads to confusion
