### ISSUE TITLE
Package top4.theillusivec4.curios does not exist?

### ISSUE THREAD

**Issue by BlankDev16** [TheIllusiveC4/Curios#155]
#### Versions (Be specific, do not write "latest"):
* Curios: 4.0.5.0
* Forge/Fabric: Forge 36.1.0
#### Steps to Reproduce:
1. Add a new curio
2. Import the dependencies
3. Compile
I added everything in the build.gradle AND the mcreator.gradle, so idk what's wrong at this point.

Crash Log: https://pastebin.com/sa2uweK9

**Comment by TheIllusiveC4** [comment]
Curios does not officially support MCreator and, unfortunately, I do not have any experience with it to help you in any other capacity.
