### ISSUE TITLE
The curios inventory cannot be opened when cosmetic slots are present

### ISSUE THREAD

**Issue by ochotonida** [TheIllusiveC4/Curios#157]
#### Versions:
* Curios: 1.17.1-5.0.0.0
* Forge: 37.0.22
#### Observed Behavior: 
Clicking the curios button does nothing if a slot type has cosmetic slots enabled
#### Expected Behavior: 
Clicking the curios button should open the curios inventory
#### Steps to Reproduce:
1. Register a slot type and enable cosmetic slots
2. Try to open the curios inventory

The curios container fails to initialize because `CosmeticCurioSlot` passes `null` as the `renders` parameter to its superclass' constructor, which causes a null pointer exception.
https://github.com/TheIllusiveC4/Curios/blob/71e5209c9226af05ff47eb2628efe598bc601fcf/src/main/java/top/theillusivec4/curios/common/inventory/CosmeticCurioSlot.java#L35 https://github.com/TheIllusiveC4/Curios/blob/71e5209c9226af05ff47eb2628efe598bc601fcf/src/main/java/top/theillusivec4/curios/common/inventory/CurioSlot.java#L53

**Comment by TheIllusiveC4** [comment]
> The curios container fails to initialize because CosmeticCurioSlot passes null as the renders parameter to its superclass' constructor, which causes a null pointer exception.

Now that's quite silly of me.

**Comment by TheIllusiveC4** [comment]
Fixed in https://github.com/TheIllusiveC4/Curios/commit/6e5aeeed942554beb0f0dd9bec8a6711abc5c340
