### ISSUE TITLE
crash in joining to world (1.16.5 FORGE)

### ISSUE THREAD

**Issue by AlgorithmLX** [TheIllusiveC4/Curios#161]
Forge 1.16.5
1. Strartup in world, and crash

Crash Log: [hastebin](https://hastebin.com/wijabohivo.rb).
Log: [Gist](https://gist.github.com/IgroGames2227/02da1e45b53ae340069f1eccd29011ac)

**Comment by TheIllusiveC4** [comment]
It looks like the config file failed loading. What does your `curios-server.toml` file look like?

**Comment by AlgorithmLX** [comment]
the fact is that there is no such thing

> It looks like the config file failed loading. What does your `curios-server.toml` file look like?

**Comment by TheIllusiveC4** [comment]
There's nothing in your world save's `serverconfig` folder by that name? That'd be quite strange since it means the config isn't being generated by Forge at all.

**Comment by AlgorithmLX** [comment]
ahh, got it, it helped, thanks!
