### ISSUE TITLE
GUI problem on server

### ISSUE THREAD

**Issue by GxXux** [TheIllusiveC4/Curios#162]
#### Versions:
* Curios: 4.0.5.2
* Forge/Fabric: Forge
#### Steps to Reproduce: 
* I'm using Curious API and Artifacts mod on my server and while I'm online I can't use keybind or button in inventory to open GUI, in addition if I right click equipment (for example gloves) it equips it but texture doesn't appear on player and seems that it doesn't gave buffs too. However if I try to execute command "/curious reset @p" this problem is getting fixed and I can equip equipment and open GUI but when I logout and login again this problem occurs again. I could make players type that command every time they join, but this command also erases equipped items of curse.
...

**Comment by TheIllusiveC4** [comment]
Are you able to reproduce this with _only_ Curios and Artifacts installed?

**Comment by GxXux** [comment]
I tried to only install Artifacts and its dependencies Curious API and ExpandAbility

**Comment by Jhonnyjokas** [comment]
I have this same problem.

I have to say that I have more mods installed but on the server when I log in the slots are not available. If I do the unlock command it solves the problem. The reset will remove my items. The interesting thing is that if the player dies and respawns, the slots are all available. 

@GxXux I think you have the same problem as me. Can you confirm if the player dies and respawns it unlocks the slots?

I'm attaching the mods that I have on my server :
https://drive.google.com/file/d/1K8GNIQQyLaBAgKcPk5mrBIiOULJOVTpv/view?usp=sharing

The versions  that I'm running:

Forge 1.16.5 36.2.2

Curios 1.16.5-4.0.5.2

**Comment by TheIllusiveC4** [comment]
@Jhonnyjokas There are too many mods in your instance to isolate the issue, you'll need to remove mods so that the issue can be reproduced using a minimum amount (like with Curios and only one or two more mods).

**Comment by Posponger** [comment]
I have this same problem.

But im using MohistMC Core on server.
I tried my modpack with Curios in singleplayer and everything is ok. So i think this is server-side problem.

The versions:

Mohist 1.16.5 831
Curios 1.16.5 4.0.5.3

**Comment by TheIllusiveC4** [comment]
@Posponger Mohist environments are not supported as some plugins have been known to cause this issue when loaded with Curios. You will need to remove Mohist and re-test in a Forge environment.

**Comment by Posponger** [comment]
@TheIllusiveC4  Ok.

I will try tomorrow in clear Forge environment and clear Mohist. I'll inform you of the results here.

**Comment by Posponger** [comment]
@TheIllusiveC4  Hello. Here are the results of testing:
 
I forgot in previous comment specify what **clear**  means.  _Its server with onliy mods that use curios installed_.

### Minecraft vesion: 1.16.5

### Mods that i used:

- Curios 4.0.5.3
- Artifacts 2.10.3
- Relics 0.3.0
- Reliquary 1.3.5.1100
- sophisticatedbackpacks 3.4.2.354

### Plugins that i used:

- LPC
- Luck Perms Bukkit 5.3.74
- NametagEdit
- Worldedit Bukkit 7.2.5 dist
- WorldEditSelectionVisualizer 2.1.0
- worldguard-bukkit 7.0.5 dist
- SkinRestorer

### Cores:

- Mohist 825
- Forge 36.2.8

### Results:

Forge (with mods)  **+**
Mohist (with mods)  **+**
Mohist (with mods, plugins **and** plugin SkinRestorer)   **-**
Mohist (with mods, plugins **without** plugin SkinRestorer)  **+**

### Conclusion:
So it seems that **SkinRestorer** is a problem.
Here is link to plugin: https://www.spigotmc.org/resources/skinsrestorer.2124/

**Comment by TheIllusiveC4** [comment]
SkinRestorer is a known compatibility issue, the only solution is to either try and report this to the Mohist developers or just remove SkinRestorer.

**Comment by Posponger** [comment]
I just removed SkinRestorer. Thanks for help ^_^
