### ISSUE TITLE
java.lang.NoSuchFieldException: fallFlyTicks

### ISSUE THREAD

**Issue by aburone** [TheIllusiveC4/Curios#168]
The crash happens at random when I have a lot of curios items and try to equip them all at once (picking tombstone)
If I have a small amount of curios items, the crash never happens.

#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.5-4.0.5.3.jar
* Forge/Fabric: forge
#### Steps to Reproduce:
1. die 
2. go to tombstone
3. try to recover (a lot) of curios items 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.pl/view/2a07179e

**Comment by TheIllusiveC4** [comment]
> at net.silentchaos512.gear.compat.curios.CurioGearItemCapability$2.curioTick(CurioGearItemCapability.java:62)

This appears to be an issue with the Curios compatibility from Silent Gear. Please report it to them instead.
