### ISSUE TITLE
Making a slot for elytra

### ISSUE THREAD

**Issue by JustinTheBob** [TheIllusiveC4/Curios#171]
I know there is a mod that adds an elytra slot for you. But i'm trying to not have to add that mod as well as the other mod that you have to have for that mod...(adding 2 more mods when u can just create your own slot using already installed curios)

But I have gone through the wiki. Followed all the steps. I got the elytra to go in the new "back" slot I made in the curios menu.  But it won't 1. Show on my back(visually) and 2. Let me use it to fly.
Am I doing something wrong or is it just not possible?
Thank you in advance!

**Comment by TheIllusiveC4** [comment]
There's a reason that the "elytra as a curio" mod exists. It's not possible to make elytras function in the curio slots without coding that functionality yourself.

**Comment by JustinTheBob** [comment]
> There's a reason that the "elytra as a curio" mod exists. It's not possible to make elytras function in the curio slots without coding that functionality yourself.

What about if I tried to do a totem slot? Is that possible or same thing? Can't function.

**Comment by TheIllusiveC4** [comment]
Same thing, can't function.

The vast majority of items that have some sort of function while in the inventory, whether it be the Elytra, Totem of Undying, or most modded items, check for specific inventory slots when they're "activated". Curios adds slots to your inventory, but these functions are not aware that these extra slots exist and would not care to check them even if they did (and no, there's currently no easy way to programmatically just add the Curios slots to these checks).

There are very rare cases, it depends on how the item is coded, where they can maintain functionality without specific Curios integration but this is not easily identifiable to the common user. The best rule of thumb is to assume that these items will not be able to maintain functionality in a Curios slot without coded integration.

The use-case for the custom slots for the average user is to create other slots for items that already have Curios integration, or for items that have no functionality in the inventory.

**Comment by JustinTheBob** [comment]
> Same thing, can't function.
> 
> The vast majority of items that have some sort of function while in the inventory, whether it be the Elytra, Totem of Undying, or most modded items, check for specific inventory slots when they're "activated". Curios adds slots to your inventory, but these functions are not aware that these extra slots exist and would not care to check them even if they did (and no, there's currently no easy way to programmatically just add the Curios slots to these checks).
> 
> There are very rare cases, it depends on how the item is coded, where they can maintain functionality without specific Curios integration but this is not easily identifiable to the common user. The best rule of thumb is to assume that these items will not be able to maintain functionality in a Curios slot without coded integration.
> 
> The use-case for the custom slots for the average user is to create other slots for items that already have Curios integration, or for items that have no functionality in the inventory.

Oh okay I see, thank you!
