### ISSUE TITLE
Detect Slot by it's custom tag

### ISSUE THREAD

**Issue by RegressiaUK** [TheIllusiveC4/Curios#172]
Hey is there way to get the slot by it's custom tag?
```java
InterModComms.sendTo(CuriosApi.MODID, SlotTypeMessage.REGISTER_TYPE, () -> new SlotTypeMessage.Builder("mytag").build());

```

so I register like so

I know we grab the slots with 
```java
CuriosApi.getCuriosHelper.getEquippedCurios(entity)
```
But how would I grab just the slot with in this case `mytag` so I can get the item already in there if this is possbile as I have loads of items what would be going in my custom slot.

**Comment by TheIllusiveC4** [comment]
> I know we grab the slots with

Actually, that's not how you grab slots. That's how you grab the _items_ in those slots. There's a difference because it does not provide any reference to the actual slots themselves.

Anyways, as for the question, you would do:

```java
CuriosApi.getCuriosHelper().getCuriosHandler(entity).ifPresent(handler ->
  ICurioStacksHandler tag = handler.getCurios().get("mytag");
  IDynamicStacksHandler stacks = stacksHandler.getStacks();
  // IDynamicStacksHandler is an implementation of ItemStackHandler so you can just grab the stacks from it by index at this point
)
```
