### ISSUE TITLE
Curios API has class loading errors

### ISSUE THREAD

**Issue by jorerivm** [TheIllusiveC4/Curios#176]
#### Versions (Be specific, do not write "latest"):
* Curios: forge-1,17,1-5.0.1.0
* Forge/Fabric:forge:1.17.1-37.0.86
#### Steps to Reproduce:
1.install mod
2.execute minecraft
3.minecraft error screen saying there was an error
...

Crash Log: https://hastebin.com/humatabana.sql
[crash-2021-10-12_23.18.19-fml.txt](https://github.com/TheIllusiveC4/Curios/files/7335126/crash-2021-10-12_23.18.19-fml.txt)

**Comment by TheIllusiveC4** [comment]
I believe this was a Forge issue that has since been addressed, so update to the latest Forge if you're encountering issues with loading Curios.
