### ISSUE TITLE
Crashes upon loading world with xerc0's music maker mod

### ISSUE THREAD

**Issue by EnderDude124** [TheIllusiveC4/Curios#18]
#### Versions):
* Curios: curios-FORGE-1.14.4-1.0
* Forge: 1.14.4-forge-28.1.10
* xerc0's music maker Version 1.1
#### Steps to Reproduce:
1. Install Curios and [xerc0's Music Maker Mod](https://www.curseforge.com/minecraft/mc-mods/music-maker-mod)
2. Launch Minecraft
3. Load a single player world (unknown if bug occurs in multiplayer, but it probably would.)
4. Game will crash on 83 - 100 percent.

I have also notified xerc0's of this issue. He didn't link to a github on his mod's curseforge page, so it may be a while...
Crash Log: https://pastebin.com/e0yx0rfy (Couldn't get hastebin to work, sorry.)

Good luck with this, i'd love to be able to use both mods.

**Comment by TheIllusiveC4** [comment]
Unfortunately, this is not an issue on my end so there's little that I can do. That mod is not properly checking if the capability is the correct instance before casting it, so it throws an error when Curios tries to initialize but gets their implementation instead.
