### ISSUE TITLE
New Curios update finds all invalid files in other mods

### ISSUE THREAD

**Issue by Darkere** [TheIllusiveC4/Curios#183]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.16.5-4.0.6.1
* Forge/Fabric: forge
#### Steps to Reproduce:
1. install other mod with invalid resources (chisel, suplementaries or immersive petrolium) 
2. crash on launch due to invalid resource location
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/SgxCBqZh

**Comment by drakray** [comment]
Same with Supplementaries https://pastebin.com/CGJWaS62
