### ISSUE TITLE
My Curios Items Disappears (Belt, Hands, Feet)

### ISSUE THREAD

**Issue by Modeeves** [TheIllusiveC4/Curios#185]
#### Versions (Be specific, do not write "latest"):
* Curios:  4.0.6.2
* Forge/Fabric:  forge-1.16.5
#### Steps to Reproduce:
1. Upon Log In while there are Equipment in the curios slots (Hands, Feet, and Belt, I haven't tried the other parts) They become unequipped and appear in my inventory instead.
2. I tried to equip them back to where they should be equipped, then the boots suddenly went missing after placing the equipment (it's an item from the Artifacts mod)
3. When I close either the GUI or my own inventory, it will duplicate my belt (an item from Tetra that can carry items in it). Whenever I try to open my curios GUI again to click the duplicated belt, it banishes. Then when I close it, it throws away a new belt.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Klouver-github** [comment]
my curios items keep flickering out and I am afraid I lost my belt with my enchanted tools

**Comment by TheIllusiveC4** [comment]
> my curios items keep flickering out and I am afraid I lost my belt with my enchanted tools

One follow-up question, do you also have Artifacts installed?

Edit: Nevermind, I think I figured out what was wrong.
