### ISSUE TITLE
[1.14.4] Localization issue

### ISSUE THREAD

**Issue by Extegral** [TheIllusiveC4/Curios#19]
#### Versions:
* Curios: FORGE-1.14.4-1.0.0.1
* Forge: 28.1.14
#### Observed Behavior:
So, there is one small problem that I've found out while working on Russian localization for my mod, when I decided to make one for Curios, too. It lies in EventClientHandler's onTooltip method, in this line:
```
tooltip.add(
         new TranslationTextComponent("curios.modifiers", identifier).applyTextStyle(
         TextFormatting.GOLD));
```
The way it is implemented does not allow to localize the identifier, and so any trinket type will be displayed as identifier defined upon type registration.
#### Expected Behavior:
It's generally up to you how to change this implementation, but I would offer creating separate lozalization keys for "When on %s:" tooltip, since there might be required declensions and other language-specific stuff.

**Comment by TheIllusiveC4** [comment]
You raise a good point. I'll change it to require specific keys in the form of `curios.modifiers.<identifier>`.
