### ISSUE TITLE
Exception getting Entity NBT

### ISSUE THREAD

**Issue by NighthowlerStudios** [TheIllusiveC4/Curios#194]
#### Versions (Be specific, do not write "latest"):
* Curios: 4.0.6.6
* Forge/Fabric: 36.2.22
#### Steps to Reproduce:
1. Install game
2. Install Curios API and Curios Armor Stands
3. run game for a while, any entity that error just will delete itself before being rendered
...

Crash Log: https://pastebin.com/BGYbz2Vc

**Comment by NighthowlerStudios** [comment]
mentioned this mod just in case the mod itself is at fault and not this API.

**Comment by TheIllusiveC4** [comment]
Some of the internals changed in the latest beta versions and Curious Armor Stands needs to update for compatibility.

Current workaround would be to downgrade Curios to 4.0.5.x unless a mod specifically requires the latest beta versions.
