### ISSUE TITLE
Crash Instanly

### ISSUE THREAD

**Issue by AlpherOut** [TheIllusiveC4/Curios#2]
The Game crashes instanly

**Comment by TheIllusiveC4** [comment]
Which Curios and Forge versions are you using? Do you have the crash logs?

**Comment by AlpherOut** [comment]
Hi! I'm using the 1.13.2 Version of Forge and i tried the "newest" Version but it didn't work

**Comment by AlpherOut** [comment]
only the "curios-1.13.2-0.r" worked for me.

**Comment by AlpherOut** [comment]
and no i dont have the crash logs

**Comment by SeanChengN** [comment]
@TheIllusiveC4 I have the crash log: https://paste.dimdev.org/cigayiyeyo.sql

**Comment by AlpherOut** [comment]
I see but how can I or you fix it so I can use the newest Version?

**Comment by TheIllusiveC4** [comment]
@AlpherOut This is something that I need to address on my end, so just hang tight until I release an update.

**Comment by AlpherOut** [comment]
Ok thanks :)

**Comment by TheIllusiveC4** [comment]
The 0.8 update should fix any crashing. At the very least, I can make it into the game with Forge 1.13.2-forge-25.0.79. Let me know if there are still issues and make sure to include the Forge version in your report.

@SeanChengN It doesn't seem like Curios is mentioned anywhere in that call stack, so I'm not sure if your crash is related to the mod.
