### ISSUE TITLE
Not sure if bug or me

### ISSUE THREAD

**Issue by FizixInt** [TheIllusiveC4/Curios#20]
I'm trying to integrate Curios into my mod. I'm not sure if there is a bug, a problem or if it's something I'm going wrong.

I'm running Minecraft 1.14.4, on Forge 28.1.0

I've created 2 curio slots "neck" and "ring", these display in the UI nicely. I've also created custom ring items and their json's. hese rings are accepted into the Curios ring slot.

In my ringItem class, I have an onCurioTick override. When I equip a ring item into the slot, it isn't firing the curioTick event. It also isn't firing the equip and remove events.

@Override
 public void onCurioTick(String identifier, int index, LivingEntity livingEntity)
    {
        LOGGER.debug("Curio Ring Item Tick");
    }

I'm not sure whether I'm setting it up incorrectly or whether there is an issue
^ this doesn't fire when requipped.

For more detail...

My item registry class:

public static Item RING_GARNET = new CeRingItem("ring_garnet", ItemGroup.COMBAT, EAManager.RING_GARNET_S);

public static Item RING_RUBY = new CeRingItem("ring_ruby", ItemGroup.COMBAT, EAManager.RING_RUBY_S);

The CeRingItem class:
public class CeRingItem extends Item implements ICurio
{
   private String itemName;
    private List<EAScheme> abilityScheme;

    public CeRingItem(String name, ItemGroup useGroup, List<EAScheme> abilityScheme)
    {
        super(new Item.Properties()
                .maxStackSize(1)
                .group(useGroup)
        );
        this.setRegistryName(new ResourceLocation(Cerulean.MODID, name));

        this.itemName = name;
        this.abilityScheme = abilityScheme;
    }

    @Override    
    public void onCurioTick(String identifier, int index, LivingEntity livingEntity)
    {
        LOGGER.debug("Curio Ring Item Tick");
    }

    @Override
    public void onEquipped(String identifier, LivingEntity entityLivingBase) {

        LOGGER.debug("Curio Ring Item Equipped");
    }

    @Override
    public void onUnequipped(String identifier, LivingEntity entityLivingBase) {

        LOGGER.debug("Curio Ring Item Removed");
    }
}

**Comment by TheIllusiveC4** [comment]
Do not implement the `ICurio` interface directly. It's meant to be used as a capability. See my comment here: https://github.com/TheIllusiveC4/Curios/issues/13#issuecomment-529141367
