### ISSUE TITLE
Clicking on the Curios Button with an item in your cursor will not carry over the item.

### ISSUE THREAD

**Issue by bconlon1** [TheIllusiveC4/Curios#202]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.18.1-5.0.4.2
* Forge: 39.0.9
#### Observed Behavior:
- When in the vanilla inventory, if you click on the Curios button with an item, it will not carry over, but clicking it again to go back will restore the item to your cursor.
- When in the Curios inventory, if you click on the Curios button with an item, it will deposit the item straight into your first hotbar slot.
#### Expected Behavior:
- The item in your cursor should not be misplaced when clicking on the Curios button, which is how this behaved in the 1.16 version.
#### Steps to Reproduce:
1. When in either the vanilla or Curios inventory, grab an item from within the inventory.
2. Click on the Curios button while the item is still grabbed.
3. The item will not stay grabbed, and will instead be misplaced in some way according to the details in __Observed Behavior__.

Crash Log: No crash log or relevant logged information.

**Comment by bconlon1** [comment]
This doesn't seem to be properly fixed when clicking the button from the vanilla inventory with an item in your cursor, and also clicking from the accessory inventory has the chance of causing item duplication.
1. Grab an item while in the Curios inventory.
2. Click the Curios button to go into the vanilla inventory.
3. Deposit the item into the vanilla inventory.
4. Click the Curios button to go back to the Curios inventory.
5. The item will be put back into your cursor, despite also being still in the inventory. Neither of them are ghost items, the item has been duplicated.

I can make another issue report for this if necessary.

**Comment by TheIllusiveC4** [comment]
Hmm, that's odd. I followed your instructions exactly and I don't get any of that behavior. Everything works as expected and I don't get any duplication. Can you reproduce this in a fresh instance with only Curios? In the meantime, I'll try to do some more testing on my end.

**Comment by bconlon1** [comment]
I have been able to reproduce this with only Curios, I will try to get a video of it in action to test it again.

**Comment by bconlon1** [comment]
Recorded gif: https://gfycat.com/brokenthunderouskusimanse

**Comment by TheIllusiveC4** [comment]
Ah ok, I see the issue. I believe it's a Creative-only issue. Are you able to reproduce this in Survival?

**Comment by bconlon1** [comment]
I cannot reproduce this in survival so you seem to be correct.

**Comment by ImBadEZ** [comment]
Might not be related, but I clicked the button while holding an item (Time in a bottle), and my game crashed.
