### ISSUE TITLE
Ring-Slot

### ISSUE THREAD

**Issue by Zerether** [TheIllusiveC4/Curios#204]
**Please describe the new feature or change.**
I have installed some Mods with adds Rings but there is no Slor for Rings. If i click on the ring, it shows me as favorite slot "Ring" but i cant find it in my Curios inventory. I remeber it worked in an older Version. It is a bug or isn't the feature in 1.18?

**Please describe why you want this feature.**

**Comment by TheIllusiveC4** [comment]
Which mods exactly did you install that supposedly gave you the ring slots?

**Comment by logosexnihilo** [comment]
I'm having the same problem as Zerether. I'm using the Gobber mod, which worked for 1.16.5 but for 1.17.1, it's not working at all for my modded server. I'm not having any crashes, the armour stand curio still works, but there isn't an option for rings, belts, etc... like there normally is.

**Comment by logosexnihilo** [comment]
The files I am using are:
curios-forge-1.17.1-5.0.2.7.jar
forge.37.1.1

I am using more mods, but that's never affected the interface.

**Comment by TheIllusiveC4** [comment]
On Gobber's project page (https://www.curseforge.com/minecraft/mc-mods/gobber), it states:

> Works with CuriosAPI if installed, not required (1.16.5 only). Not supported in 1.17.1+.

So the lack of support seems intentional. If you'd like further info, you'd have to ask that developer.
