### ISSUE TITLE
rings dont fit into rings slots

### ISSUE THREAD

**Issue by krjencik** [TheIllusiveC4/Curios#210]
why cant i put rings of ascension in the rings slots?

playing minecraft 1.18.1

it looks like i cant put ANY ring into that slots...

forge: 39.0.40 

curios forge 5.0.5.2

**Comment by TheIllusiveC4** [comment]
I can't reproduce this, the Rings of Ascension fit into my ring slots just fine. Also, you should report bugs of this nature to the mod that's implementing Curios (Rings of Ascension in this case), not Curios directly.
