### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by driftirl** [TheIllusiveC4/Curios#214]
hi i cant seem to put on other armor can someone please help 

#List of curio slot type settings
[[curiosSettings]]
	identifier = "head"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "createplus.goggle_slot"
	override = true
	priority = 3
	locked = true
	size = 1
	hasCosmetic = true

[[curiosSettings]]
	identifier = "necklace"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "back"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "body"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "hands"
	size = 2
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "ring"
	size = 3
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "belt"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "charm"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "feet"
	override = true
	hasCosmetic = true

[[curiosSettings]]
	identifier = "bracelet"
	override = true
	size = 0

[[curiosSettings]]
	identifier = "glasses"
	override = true
	size = 0

**Comment by driftirl** [comment]
the only thing i can equip is the elytra in the back slot no other slot works

**Comment by TheIllusiveC4** [comment]
Did you make sure to tag the items you're trying to equip with the appropriate slot tag? Or that they natively come tagged already? Items that can be equipped will have the `Slot: ___` tooltip under their name with the appropriate slots.

**Comment by driftirl** [comment]
> Did you make sure to tag the items you're trying to equip with the appropriate slot tag? Or that they natively come tagged already? Items that can be equipped will have the `Slot: ___` tooltip under their name with the appropriate slots.

im kind of new to the whole editing of mods can u please explain what u mean please

**Comment by StephenDay1** [comment]
https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users
Just make sure you follow steps 3 and 4 if you are making your own slots that aren't natively supported by the API.  I hope that helps.
