### ISSUE TITLE
Interface does not open

### ISSUE THREAD

**Issue by Samlegamer** [TheIllusiveC4/Curios#215]
Hi, when I made a mod with the curios api and launched the game for the first time, I noticed that the interface did not open.
And strangely this bug does not occur if I put the mod on modpack (like Better Minecraft).
If I put the two mods together the interface doesn't open, but on a big modpack it does.

build.gradle : https://github.com/Samlegamer/PotionRingReforged/blob/1.16.5/build.gradle

**Comment by TheIllusiveC4** [comment]
Did you add slots? Curios does not add any slots by default, which would mean the interface is empty if you did not add any slots.

**Comment by Samlegamer** [comment]
So that was it, thank you!
