### ISSUE TITLE
Creating a Slot with Functionality (Jetpacks)

### ISSUE THREAD

**Issue by StephenDay1** [TheIllusiveC4/Curios#217]
I'm using the create mod, and an extension of it, Create Stuff Additions ([Curseforge link](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)).  I tried making my own Curios slot, using the guide ([How to Use: Users](https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users)), and it worked, however I can't actually fly with the jetpack in that slot.  Is there something I can add to make this work?

**Comment by TheIllusiveC4** [comment]
Not as a user. Likely what's happening is that the Jetpack is checking specific slots for functionality, and it does not include Curios's slots. You would need to ask the mod developer for integration directly.
