### ISSUE TITLE
Curios 1.18.1-5.0.6.1 seemingly fails to initialize into Forge Modloader

### ISSUE THREAD

**Issue by spezard** [TheIllusiveC4/Curios#224]
* Curios: curios-forge-1.18.1-5.0.6.1-api
* Forge: 1.18.1-forge-39.0.79 (also tested on 39.0.59)
#### Observed Behavior: When loading into the game, Curios seems completely absent from the mod list and functionality in-game. If there's a mod dependant on it (in this case Enigmatic Legacy), it simply crashes java entirely with exit code 1. No crash log in either case since it doesn't get that far in one case and the latest.log seems to ignore it's existence entirely, though I'll include it just in case there's anything relevant there I'm unaware of.

[latest.log](https://github.com/TheIllusiveC4/Curios/files/8093333/latest.log)

I've got the feeling this could somehow be related to my specific system setup overall, though not sure in what capacity. Because I recently had an issue with Enigmatic Legacy itself that no one else I was playing with encountered, and that the dev couldn't recreate either. Just in case I'll include the part of a different crash log (from when it tried to run Enigmatic Legacy 2.16.1 with the older version of Curios, 5.0.6.0) that has relevant system data if that'd help at all, and I can provide any more data if needed.

```
-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1795508864 bytes (1712 MiB) / 3556769792 bytes (3392 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 67534.86
	Virtual memory used (MB): 12910.68
	Swap memory total (MB): 34816.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
```

**Comment by TheIllusiveC4** [comment]
> Curios: curios-forge-1.18.1-5.0.6.1-api

You downloaded the API jar instead of the regular one. The regular one that users should use should not have anything appended after the version.

**Comment by spezard** [comment]
Well I feel silly now, derp. Sorry to bother, but thanks for the prompt response.
