### ISSUE TITLE
Curios and sophisticated backpacks not working correctly together

### ISSUE THREAD

**Issue by KMFrench1** [TheIllusiveC4/Curios#226]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.18.1-5.0.6.1
* Forge/Fabric: Forge 39.0.75
* sophisticated backpack: sophisticatedbackpacks-1.18.1-3.15.9.533
#### Steps to Reproduce:
1. Play on a sever
2. put sophisticated backpack in curios slot
3. try to open it
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Does this happen on single-player also?

**Comment by KMFrench1** [comment]
I just checked, I actually had not played it single player. Yes, it happens in single player too.

**Comment by TheIllusiveC4** [comment]
I'm having trouble reproducing this behavior. Some more follow-up questions:

Does this happen if you load _only_ Curios and Sophisticated Backpacks?

How many total back slots from Curios do you have when it happens?

**Comment by KMFrench1** [comment]
I will go through my mods and delete them till I find the culprit. I did not want to do it as I have over 250 mods. But I will do it tomorrow and get you the info.

**Comment by KMFrench1** [comment]
This is weird. This morning I sat down to figure out what mods where conflicting to cause this bug. I created a new instance added just Curios and Sophisticated Backpacks. This worked fine. Then I started to re-add mods 10 at a time. Starting the game each time to see if the GUi glitch happened. I have now re-added every mod to the new instance and the backpack is working fine in the curios slot.  So I now have 2 identical instances of Minecraft one that works fine, the other that still has the GUI bug. I am not sure what is going on. I am going to try the new instance on the server once my friend starts it up later today, I will let you know if that changes anything.

**Comment by KMFrench1** [comment]
It is doing it agian. Here is the Log if that help.
https://paste.ee/p/PXPfz
If you scroll to the bottom you can see the error that happen when I try to open the backpack.
I did it multiple times in  a row, so the error would repeat and be easier to find.
Line 22503 for example.
""[19:36:28] [Render thread/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 112 out of bounds for length 0""
Then a of code stuff.

**Comment by KMFrench1** [comment]
After I log onto the server, it started happening again. It now happens in single player too. It is like connecting to the server cause the game to "remember" the not working version of the Gui.
Here is the Log if that help.
https://paste.ee/p/PXPfz
If you scroll to the bottom you can see the error that happen when I try to open the backpack.
I did it multiple times in  a row, so the error would repeat and be easier to find.
Line 22503 for example.
""[19:36:28] [Render thread/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 112 out of bounds for length 0""
Then a of code stuff.
Let me know if you need anything else.

**Comment by TheIllusiveC4** [comment]
You've verified that it works fine with only Curios and Sophisticated Backpacks installed in single-player. And then you've verified that the bug re-occurs when you log onto the server with all the mods installed. However, you would still need to verify that the bug also occurs when you log onto the server with _only_ Curios and Sophisticated Backpacks installed.

The last part is important because if that cannot be verified, I wouldn't know if the issue is because of an issue with a 3rd unidentified mod. And if I don't know that, then I don't know where to begin solving the problem.

**Comment by KMFrench1** [comment]
I don't run the server. I can ask if the owner would be willing to run the test. However, I "think" it will work with just the two mods installed. I will ask to see if they are willing to test it.
What puzzles me is that it worked fine all day in single player. Then after logging into the server (Nothing was change, no updates, no downloads), it stropped working in single player. I understand that it may not work while connected to the server, but why would it stop working in single player after?

**Comment by TheIllusiveC4** [comment]
My best guess is that logging onto the server causes _something_ to go wrong on your client, and this issue persists across the entire session (so it will affect you as long as the client is active) so that only restarting it will fix the issue temporarily.

The error that you posted is at least some kind of clue, so I'll do some investigating. However, unless I can properly reproduce the bug myself, any progress I can make will be limited.

**Comment by KMFrench1** [comment]
I can 100% get you a copy of the entire modpack we built. That's easy. If you want let me know and i can upload to mega a zip to mega. I may even be able to get you allowed on the server. But it is only ever up when he is home, so that may not be the best option for you to test it.  But I can ask if you want me too.

**Comment by TheIllusiveC4** [comment]
When I say reproduce the bug myself, I mean with only Curios and Sophisticated Backpacks installed. While I could try and reproduce the bug with all the mods in your modpack, I still wouldn't know if it's being caused by a 3rd mod or not.

But I suppose it couldn't hurt to have it, so you can send me your modpack if you're able.

**Comment by P3pp3rF1y** [comment]
Just spent a bit of time looking through my code and the only possibility I can see based on these symptoms is that curios slots for some reason stop existing on the client (but I suspect they are still there in the curio gui so likely not) or the identifiers for the slots get changed for some reason and then my logic is no longer able to get to them. Anyway given that some pretty big modpacks don't seem to have this issue I don't think this can be recreated with just curios and sbp so it would be good to understand what other mod needs to be present to be able to recreate.

**Comment by KMFrench1** [comment]
Here is a link to a *.rar copy of my mod folder. We did not change the configs, so default generated ones should work. Even if it does not help fix the issue feel free to enjoy the pack we created.
https://mega.nz/folder/3yoGhDLD#WRZzf75I3WqCpAEkJkOJtw

**Comment by Deadlite93** [comment]
just wanted to say its also happening once in awhile on our Project architect server. seems rare and sporadic though because some das its just happening to one of us at random, and other days its not happening to anyone. im sorry i couldnt be of more help.

**Comment by ChrisCrossOnGit** [comment]
This also happened on my All the Mods 6 server, MC 1.16.5, modpack version 1.8.22, forge version 36.2.31, Curios version urios-forge-1.16.5-4.0.5.3, Sophisticated Backpacks version sophisticatedbackpacks-1.16.5-3.15.13.560
