### ISSUE TITLE
[1.18.2] Crash at launch in modding environment

### ISSUE THREAD

**Issue by Erfurt92** [TheIllusiveC4/Curios#229]
* Curios: 1.18.2-5.0.6.3
* Forge: 40.0.12

I'm trying to update my mod to 1.18.2, and the game crashes when launching the game. I have tried a clean test mod, basically the example mod that comes with the Forge MDK, and the same thing happens there when adding the Curios API.

![image](https://user-images.githubusercontent.com/20155513/157565335-11be6481-5685-4f3b-91b3-cab41089f7de.png)

Crash Log: [Crash Log](https://www.toptal.com/developers/hastebin/mahumuzoqa.properties)

**Comment by TheIllusiveC4** [comment]
I think something hasn't updated properly in your development environment. Although it is running Curios 1.18.2-5.0.6.3, the crash stacktrace
```
Stacktrace:
	at top.theillusivec4.curios.client.CuriosClientMod.init(CuriosClientMod.java:24) ~[curios-forge-1.18.1-5.0.6.0_mapped_official_1.18.1.jar%2375!/:1.18.1-5.0.6.0] {re:classloading}
```
is showing that it's reading from an older version, 1.18.1-5.0.6.0. Perhaps refresh dependencies or clear your cache? I'm not exactly sure how the older version is sticking around.

**Comment by Erfurt92** [comment]
Yeah, I saw that as well, and I tried to clear my cache and reload the dependencies, same thing happened, so I was a bit unsure if it was on my end or something with Curios API, which is why I made the issue. But I will look into it again tomorrow when I some more time.

**Comment by TheIllusiveC4** [comment]
For the record, I've received comments from other developers that confirm they are able to load Curios fine in 1.18.2 and I am able to do so as well, so I do believe it is something on your end unless someone else happens to report the same issue.

**Comment by Erfurt92** [comment]
I believe you, I have never had any issues like this before :)
I must have done something wrong when I tried to clear the cache, will try again when I get the time. Closing the issue for now
