### ISSUE TITLE
when putting anything into the curios slots Minecraft crashes

### ISSUE THREAD

**Issue by krjencik** [TheIllusiveC4/Curios#230]
#### Versions (Be specific, do not write "latest"):
* Curios:5.0.6.3
* Forge/Fabric:40.0.17
#### Steps to Reproduce:
1.download any mod using curios 
2. launch the game
3.enter a world and try to put anything into curios slots
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://gist.github.com/krjencik/af03fe637fb1554127876da69d6ff67b#file-maybebrokencurios

**Comment by krjencik** [comment]
its Minecraft 1.18.2

**Comment by TheIllusiveC4** [comment]
I believe it's a JEI issue: https://github.com/mezz/JustEnoughItems/issues/2752
According to that, it should be fixed in JEI 1.18.2-9.5.0.134.
