### ISSUE TITLE
Items with attributes in curios slots

### ISSUE THREAD

**Issue by addaonez** [TheIllusiveC4/Curios#231]
How can I add an attribute to items so that it works in a curios slot?
When you add an attribute to some item, you can specify the slot in which it should be kept, for example /give @p carved_pumpkin{AttributeModifiers:[{AttributeName:"generic.armor",Amount:2,Slot:head,Name:"generic.armor",UUID:[I;-122221,17561,115550,-35122]}]} 1
If no slots are specified, the attributes still only apply to minecraft slots.
Is it possible to somehow designate a slot from curios? 

Thank you in advance

**Comment by TheIllusiveC4** [comment]
It'd be almost the same, except replace `AttributeModifiers` with `CurioAttributeModifiers` and it takes in the name of the slot as a string in the `Slot` field.

For your example, to add an attribute for a `ring` slot:
```
/give @p carved_pumpkin{CurioAttributeModifiers:[{AttributeName:"generic.armor",Amount:2,Slot:"ring",Name:"generic.armor",UUID:[I;-122221,17561,115550,-35122]}]} 1
```

**Comment by addaonez** [comment]
Thank you very much!
