### ISSUE TITLE
force item

### ISSUE THREAD

**Issue by jubblyo** [TheIllusiveC4/Curios#236]
im trying to make it so that with the artifacts mod you cant take off the charm of sinking, is there anyway to do this? ive went on the artifacts mod discord and they cant seem to help.

**Comment by TheIllusiveC4** [comment]
This is something that can be done from Artifacts, if they wish, by setting up a configuration option for the item's `ICurio#canUnequip` implementation. This is something done in code and currently cannot be changed by the user directly.
