### ISSUE TITLE
pls help idk what happened

### ISSUE THREAD

**Issue by Bobgogg** [TheIllusiveC4/Curios#237]
[latest.log](https://github.com/TheIllusiveC4/Curios/files/8557770/latest.log)

**Comment by TheIllusiveC4** [comment]
This seems like it's due to either an outdated Cardinal Components API or an outdated Fabric API. Make sure both of those mods are updated. Regardless, Curios is not loaded in your environment so if the issue persists then it's not something that is caused by Curios.
