### ISSUE TITLE
Curios Light icon does not seem to apply

### ISSUE THREAD

**Issue by Raidobw2** [TheIllusiveC4/Curios#239]
#### Versions (Be specific, do not write "latest"):
* Curios: `curios-forge-1.18.2-5.0.7.0.jar`
* Curios lights: `curiouslights-forge-1.1.0+1.18.2.jar`
* Forge/Fabric: `Forge 40.1.20`
#### Observed Behavior:
It looks like making a new light slot and giving it an icon will never render the correct texture for the icon. I've tried with KubeJS's assets folder as well as a normal resource pack
![image](https://user-images.githubusercontent.com/17010632/169205984-3ba70ca8-c1ee-45e7-b6bc-221358c3de21.png)
#### Expected Behavior:
The icon should load with the right texture injected in the resources
#### Steps to Reproduce:
1. Configure the serverconfig: 
```
#List of curio slot type settings
[[curiosSettings]]
  identifier = "light"
  size = 1
  icon = "curios:item/empty_light_slot"
  visible = true
```
2. Put the png at the right spot in a resource pack/KubeJS assets folder, following the tutorial. `assets/curios/textures/item/empty_light_slot.png`
3. Load the game and access resource packs to enable it if needed
4. Enter the world
5. Notice the icon is empty in game, although the slot behaves correctly
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/). N/A

**Comment by TheIllusiveC4** [comment]
As instructed [here](https://github.com/TheIllusiveC4/Curios/wiki/Slot-Textures):

> Create a new resource directory `assets/curios/textures/slot` and place any `.png` file in the slot folder.

You have your image in the `item` directory, instead of the `slot` directory. If you rename the directory, it should work.

**Comment by Raidobw2** [comment]
Sorry for the delayed answer, thank you for your reply! I'll try that and quickly report back here

**Comment by Raidobw2** [comment]
Renaming the folder to `slot` worked as well as changing the serverconfig to:
```
#List of curio slot type settings
[[curiosSettings]]
  identifier = "light"
  icon = "curios:slot/empty_light_slot"
  size = 1
  visible = true
```
Thank you very much for your time and have a nice day!
