### ISSUE TITLE
Curios crashes while Industrial Foregoing Meat Feeder is equipped near endermen

### ISSUE THREAD

**Issue by ThatPreston** [TheIllusiveC4/Curios#241]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.18.2-5.0.7.0
* Industrial Foregoing: 1.18.2-3.3.1.0-2
* Titanium: 1.18.2-3.5.5-37
* Forge/Fabric: Forge 1.18.2-40.1.47
#### Observed Behavior:
The game crashes when near an enderman with the Meat Feeder from Industrial Foregoing equipped
I think this is a problem with the way Industrial Foregoing set up curios compatibility, but the crash is caused by curios
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.18/src/main/java/com/buuz135/industrial/plugin/curios/MeatFeedCurios.java
#### Expected Behavior:
If something goes wrong when getting the item to check if it's an ender mask, it should just assume it isn't
The crash says it couldn't use isEnderMask because getStack() returned null, maybe curios could add extra checks to avoid the crash
#### Steps to Reproduce:
1. Open any world
2. Equip the "Meat Feeder" item from Industrial Foregoing
3. Spawn or summon an Enderman

Crash Log: https://pastebin.com/ktX5Wrn5

**Comment by TheIllusiveC4** [comment]
It seems like this was fixed on Industrial Foregoing's end, which I think was the ideal solution.
