### ISSUE TITLE
Industrial  Foregoing Placing Meat Feeder In Baubles Crashes Server 

### ISSUE THREAD

**Issue by SilverBackHorse** [TheIllusiveC4/Curios#243]
#### Versions  ""curios-forge-1.18.2-5.0.7.1""
* Curios:
* Forge 1.18.2
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/). -- Do not have

**Comment by TheIllusiveC4** [comment]
I'm going to need at least the Industrial Foregoing version number and the crash log from the server. Otherwise, I don't have enough information to fix the issue.

**Comment by SilverBackHorse** [comment]
industrial-foregoing-1.18.2-3.3.1.3-7.jar

I will have to get the crash logs later tonight. I am very thankful for the response and help. Thank you much

**Comment by SilverBackHorse** [comment]
Ok so I went ahead and updated any of my mods that had an update I have 108 mods and It looks like the meat feeder is working now no crashes or server reset and works in single player as well. Im not sure what mod was causing the problem but its working fine now.
