### ISSUE TITLE
Curios in combination with Curios Armor Stands performance issue.

### ISSUE THREAD

**Issue by NoxyNixie** [TheIllusiveC4/Curios#251]
#### Versions:
* Curios: `curios-forge-1.18.2-5.0.7.1`
* Curios armor stands: `curious-armor-stands-1.18.1-4.0.0` (https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands)
* Forge/Fabric: `Forge 40.1.68`

#### Observed Behavior:
I've noticed curious being rather hungry in performance on some entities where I wasn't expecting curios to do much.

Below is a profile view of entities being ticked in one minute. As you can see Curios event handler is taking `1.36%` on an armor stand in comparison the second worst event handler is only `0.05%`.
![image](https://user-images.githubusercontent.com/211381/180863578-d657941a-75f5-4342-bc3e-6b1afa704b93.png)

On our dedicated server with a large world and various dungeons that have generated in armor stands the impact of this is even worse that in the above picture (which is single player). It also has me somewhat worried about potentially pointless network traffic due to armor stands and curios since the trace contains packet related things.

When checking for how many armor stands there are `forge entity list` only shows 10 in the same exact location the above profile was done so it is not an excessive amount.

Removing only Curious armor stands from the mod pack does resolve this issue.

#### Expected Behavior:

Curios to not do any ticking with armor stands. If somehow this is still needed an option to disable this would be neat.

I'm not sure if this falls on Curious itself to resolve or the Curios Armor Stand mod.

(Cross posted here too: https://github.com/ochotonida/curious-armor-stands/issues/7)

**Comment by TheIllusiveC4** [comment]
Curios only provides a player implementation currently, so the performance impacts of the armor stand implementation would need to be addressed by Curious Armor Stands.
