### ISSUE TITLE
[1.16.5]The Sophisticated Backpacks mod inventory does not open when it is in curio slots

### ISSUE THREAD

**Issue by DrSigma4164** [TheIllusiveC4/Curios#252]
#### Versions (Be specific, do not write "latest"): 4.0.8.2
* Curios: 4.0.8.2
* Forge/Fabric: 36.2.39
* Sophisticated Backpacks: 3.15.15.607
* Essential mod: They haven't uploaded the version for 1.16 on Curseforge yet, but here is the link to their official site: https://essential.gg/download
#### Observed Behavior:
When the Essential mod, which recently received support for version 1.16, is installed, the button to open the backpack inventory from the Sophisticated Backpacks mod does not work, meaning that the backpack does not open when it is in the curio slots. In the breastplate slot or in the inventory, it opens. I wrote to the developers of Sophisticated Backpacks and they referred me to you.

#### Steps to Reproduce:
1) Install the Essential, Sophisticated Backpacks, Curios API mods
2) Configure a hotkey for opening the backpack
3) Try to open the backpack.

**Comment by TheIllusiveC4** [comment]
If this is happening with the Essential mod, and not with just Sophisticated Backpacks + Curios, then you need to report it to the Essential developers, not here.
