### ISSUE TITLE
No Ring Slots - Cannot Add

### ISSUE THREAD

**Issue by QueenCorbeau** [TheIllusiveC4/Curios#253]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-1.18.2-5.0.7.1
* Forge/Fabric: Forge 40.1.68
#### Steps to Reproduce:
1. Updated mods and Forge engine and restarted client. 
2. Made new world, but the issue persists.
3. Disabled majority of the other mods I have installed, and it persisted.
...

Crash Log: Nothing crashed, so there is no crash log. It was just an issue of the slots not being available as expected.

**Comment by TheIllusiveC4** [comment]
Have you verified that the Ring of Repair and Ring of Attraction actually are supposed to add ring slots? From what I can tell, they do not and thus this behavior is expected. In that case, you would need to add a mod that adds ring slots and/or add ring slots yourself using the config as described here: https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users

**Comment by QueenCorbeau** [comment]
They both say Slot: Ring when I hover over the items, so I assumed, perhaps incorrectly, that they would add the appropriate slots. Failing that, when not given the slots outright previously, I was able to use the /curios add ring command in game to add them manually, but that wasn't working either. I'll check the configs to see if there's something I missed there.

**Comment by QueenCorbeau** [comment]
Changing the server config file did fix the issue. Sorry for submitting a false bug. :) It just had always worked previously, so it confused me.

Thanks!
