### ISSUE TITLE
Feature Request: Override Slots

### ISSUE THREAD

**Issue by egshels** [TheIllusiveC4/Curios#254]
**Please describe the new feature or change.**
A config option to allow slots in curious-server.toml to override their existing slot count

**Please describe why you want this feature.**
Many mods add Curio slots without checking if they already exist - this results in a mess of far too many rings and charms, and there's currently no way to fix this (as far as I know) 
![image](https://user-images.githubusercontent.com/31183838/183794755-54853e12-ec8f-44ed-9689-ebff6e58c6b8.png)

**Comment by TheIllusiveC4** [comment]
There is already a way to do this. Check here: https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users#creating-a-new-slot-type
Specifically, the `override` field. If you have 100 rings from mods, then you can just do:
```toml
[[curiosSettings]]
  identifier = "ring"
  size = 2
  override = true
```
And it's suddenly down to 2. Note that this can be used to override _any_ setting, setting `override = true` basically takes your configuration's settings as the sole source.

As an aside, mods aren't adding all the rings together. That would defeat some of the purpose of Curios integration. Curios merges all of them together and gives you an amount of slots equal to the highest amount given by any one mod. This means that a single mod has chosen to give you that many ring slots, it's not the sum of many mods together.
