### ISSUE TITLE
Crash between curios, caelus and netherite elytra

### ISSUE THREAD

**Issue by Blugori** [TheIllusiveC4/Curios#256]
Hi, I ran into an issue :(

Minecraft : 1.18.2
Curios : 5.0.7.0 or 5.0.7.1 (both crash)
Forge : 40.1.48 (I can't use higher version of forge, I hope it's not the problem)
Caelus api : 3.0.0.2
Netherite elytra : 1.1.1-curios

What happens : When trying to put a netherite elytra from the mod of the same name, game crash
What should happen : Game shouldnt crash and the elytra should be on the related slot

How to reproduce :
1. Install the netherite elytra mod, curious api and caelus api
2.Put a netherite elytra on the related slot in curious inventory

Crash Log: https://pastebin.com/Sw6ymqwQ

Thanks for reading !

**Comment by TheIllusiveC4** [comment]
This is an issue with Netherite Elytra, please report this to those developers.

**Comment by Blugori** [comment]
I'm dumb sorry, they changed the name of the other dependency : curios elytra (now elytra slot), and I skipped it. It should work now, sorry for the inconvenience.
