### ISSUE TITLE
Internal Exception: java.lang.IndexOutOfBoundsException issue in multiplayer game (possible issue is rings of ascension)

### ISSUE THREAD

**Issue by MstDominik** [TheIllusiveC4/Curios#259]
* Curios:last version
* Forge 41.1.0
 when i equip ring and try take off from curios menu i dissconect from server with this inscription (Internal Exception: java.lang.IndexOutOfBoundsException ) i duplicate this to rings of ascension too (mods: quark, Nevermine, Sophisticated backpacks and ring of ascension all mods the last version of 1.19 ) :D

**Comment by TheIllusiveC4** [comment]
What ring exactly?

> mods: quark, Nevermine, Sophisticated backpacks and ring of ascension all mods the last version of 1.19

Are these the _only_ mods you have installed?

**Comment by MstDominik** [comment]
> What ring exactly?
> All rings from mod (rings of ascension)
> > mods: quark, Nevermine, Sophisticated backpacks and ring of ascension all mods the last version of 1.19
> 
> Are these the _only_ mods you have installed?

generally installed mods for optimization (betterfpsdist,deuf,krypton,smooth boot,lazydfu,ai improvements,deuf,connectivity,radium,radon,rubidium all this mods installed with 4 mods that I have already written )
p.s btw if i remove quark and nevermine mods the bug with the so-called 5th element disappears so i hope it helped
