### ISSUE TITLE
Server Crash 1.19 forge 41.1.0

### ISSUE THREAD

**Issue by Thisguyneedshelp** [TheIllusiveC4/Curios#260]
hello im trying to start up  my server, and i got this crash im not sure if the real problem is curios but id figured id let you guys look just in case heres the crash report https://mclo.gs/WUGgZsh

**Comment by Thisguyneedshelp** [comment]
i dont mean to be impatient, but i would really appreciate it if you'd help with this sooner rather than later cause ive basically narrowed down the problem to this mod, but i cant remove it as its a necessity for like 20 of my core mods

**Comment by TheIllusiveC4** [comment]
This is not caused by Curios, this is caused by Curios Quark Oddities Backpack. Please report this issue to that mod instead.
