### ISSUE TITLE
[Question] Is there a way to identify what mods added what slots?

### ISSUE THREAD

**Issue by Lion4K** [TheIllusiveC4/Curios#261]
I have something that made a "Body" slot, and I have no idea what made it.
I have no items with the "body" slot.

Is there a command to see what other slots are available and are hidden? Like slots that can be given with the /curios set slot command?

**Comment by TheIllusiveC4** [comment]
There was none before, but the latest update for 1.19.3 (which I plan to backport to some older versions) has a new command `/curios list` which will reveal what slots have been added by what mod.

**Comment by Lion4K** [comment]
AWESOME!!!
Thank you a lot!!!
