### ISSUE TITLE
Unable to locate ring of regeneration

### ISSUE THREAD

**Issue by mberlin1** [TheIllusiveC4/Curios#266]
Running from pack tnp limitless 5, minecraft 1.18.2.
I'm unsure if betterstronghold:stronghold is interfering with its spawn, but at last count I've looked in 76 strongholds, going west from my spawn. I'm at about -80000 by 25000.  I've looked in every single stronghold library in each of these strongholds, and have not found this ring.  It claims a spawn rate of 25% per stack.  I've found all the other rings, but not this one. Any chance Yung's better strongholds is interfering somehow? 
Looking through the configs there's nothing that leads me to believe that it is -- it only has configs for a single type of room it adds, a storage room, which as foodstuffs and other things on display.

If the chance listed in the JEI is accurate then something is definitely wrong.

**Comment by TheIllusiveC4** [comment]
I don't know what ring you're referring to, but Curios does not have such a ring and does not add anything to loot in general. I believe you may be speaking of another mod, in which case you need to post this to their repository instead.

**Comment by mberlin1** [comment]
My apologies, when i clicked on rings of ascension, issues page, this is where it brought me. thank you.
