### ISSUE TITLE
Sophisticated backpack and elytra slot uses same slot

### ISSUE THREAD

**Issue by jbrandek** [TheIllusiveC4/Curios#267]
Add another separate slot for elytra slot mod

Add another slot the to have both items at same time, elytra and the backpack.

**Comment by TheIllusiveC4** [comment]
Curios does not add any slots natively, and how items are classified is entirely up to the implementing mods. In this case, Sophisticated Backpack and Elytra Slot. However, you can configure this yourself by referring to this guide: https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users

You can create a new custom slot type and reconfigure the item tags to use it, or you can even just have 2 back slots. The choice is yours.
