### ISSUE TITLE
curios 1.16.5 auto crashing bug

### ISSUE THREAD

**Issue by UnimitedPixel** [TheIllusiveC4/Curios#275]
version curios-forge-1.16.5-4.0.6.0.jar to version curios-forge-1.16.5-4.0.8.2.jar i know that they are in beta but 1.16.5 hasnt updated in a little under a year and it auto crashes every time i try to join a world and its needed for a mod and idk if its just me thats crashing but i would like to know if anyone has found a way to fix this annoying glitch if they have ever encountered it because its starting to get annoying to have to keep removing the mod and downgrading curios

**Comment by TheIllusiveC4** [comment]
Please fill out the bug report template. You will need to provide the version of Curios that is crashing, the Forge version, and the crash log.
