### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by Zemogiter** [TheIllusiveC4/Curios#277]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.19.2-5.1.1.0
* Forge/Fabric: 1.19.3-44.1.5
#### Steps to Reproduce:
1. Put these mods in `mods` folder:
 ```
curios-forge-1.19.2-5.1.1.0.jar
RingOfBlink-Forge-1.19.2-1.5.4.jar
RingOfEnderchest-Forge-1.19.2-1.5.5.jar
RingOfRepair-Forge-1.19.2-1.5.4.jar
RingOfReturn-Forge-1.19.2-1.4.4.jar
 ```
2. Launch the game with forge profile mentioned above
3.After the loading screen, observe the crash message.

Crash Log: 
[crash-2023-01-18_18.14.45-fml.txt](https://github.com/TheIllusiveC4/Curios/files/10448966/crash-2023-01-18_18.14.45-fml.txt)
[latest.log](https://github.com/TheIllusiveC4/Curios/files/10448969/latest.log)

**Comment by TheIllusiveC4** [comment]
It looks like you're trying to load 1.19.2 mods on 1.19.3, which isn't going to work well. Please either downgrade Forge to 1.19.2 or update your mods to 1.19.3 (or remove them if they don't have one available).
