### ISSUE TITLE
Issue Loading Up with Artifacts

### ISSUE THREAD

**Issue by Shreshy** [TheIllusiveC4/Curios#279]
Hi, I have an issue when I try to open the game using the artifacts mod the game crashes, this has never happened before when trying to use this mod, I have been instructed to give my modlist so here you go, also I am playing on 1.19.2 Forge 43.2.0 and all mods are updated to the latest version

Only log present
[latest.log](https://github.com/TheIllusiveC4/Curios/files/10489438/latest.log)

AI Improvements
Alex Mobs
Allurment
Appleskin
Aquamirae
Architectury API
Artifacts
AutoRegLib
Backpacked
Balm
Berry Good
Better Advancements
Better Fps- Render Distance
Biome Makeover
Blaze Gear
Blue Skies
Blueprint
Bookshelf 
Botania
Canary
Castle in the sky
citadel
Client tweaks
Cloth Config Api
Cloud Storage 
Clumps
Collective
Controlling
CoralReef
Corpse
Cosmetic Armor Reworked
Craftable horse armor and saddle
Creatures and Beasts
Creeper Overhaul
Cull Leaves
Curios API
Darker Depths
Dragon mounts legacy
Ecologies
Enchantment Descriptions
End Remastered
End Trigon
Enlighted End
Entity Culling
Every Compat
Explorer's Compass
Farmer's Delight
Fast leaf decay
FerriteCore
FlickerFix
ForgetMeChunk
FPS Reducer 
From the Shadows
Galosphere
Gateways to eternity
GeckoLIb
Goblin Traders
Hopo Better Mineshafts
Hopo Better Ruined Portals
Hopo Better Underwater Ruins
Iceberg
Illage and Spillage
Immersive Armors
Infernal Expansion
Insanelib
Inventory HUD+
It Takes a Pillage
Item Highlighter
Jade
JEI (Just enough items)
JEP
JER
L+Ender's Cataclysm
Laya DataFixer
Loot Journal
Lootr
Magnesium/Rubidium Dynamic Lights
Marjusz Library
Marjusz's Progressive Difficulty 
Meet your fight
MmmMmmMmmMmm (Target Dummy)
Mob Catcher
Moonlight Lib
More Dragon Eggs
More Villgers
Mouse Tweaks
Nature Compass
Neapolitan 
Neko's Enchanted Books
Nether Depths
Nether Portal Fix
Not Enough Crashes
Nourished Nether
Obscure Api
Oculus
Ore Excavation
Patchouli
Placebo
Pluto
Polymorph
Progressive Bosses
Puzzles Lib
Quark
Radon
Raided
Relics
Rubidium
Rubidium Extra
Saturn
Savage & Ravage
Shroom Dealer
Sky villages
Spark
Spirit
Stalwart Dungeons
Starlight
Structory
Structure Gel API
Terralith
TexTrue's Rubidium Options
The Bumblezone
The Conjurer
The Graveyard
Towers of the Wild additions
Towns and Towers
Trading Post
Traveler's Titles 
Tumbleweed
Twigs
Underground Villages
Unusual End
Upgraded Core
Upgraded Netherite
Valhesia Core
Valhesia Furniture
Valhesia Structures
Village Artifacts
Waystones
What did you vote for 2022
When Dungeons Arise
Xaero Minimap
Xaero World Map
YUNG API
YUNG Better Desert Temples
YUNG Better Dungeons
YUNG Better Ocean Monuments
YUNG Better Witch Huts
YUNG Bridges
YUNG Extras

**Comment by TheIllusiveC4** [comment]
Please share the crash log.

**Comment by Shreshy** [comment]
> Please share the crash log.

I just did but I am not sure if it will help

**Comment by TheIllusiveC4** [comment]
Are there no logs in the `crash-reports` folder for your instance? Without a crash log, I cannot decipher the cause of your issue unfortunately.

Also, in the absence of a crash log, what leads you to believe that this is a Curios issue?

**Comment by Shreshy** [comment]
> Are there no logs in the `crash-reports` folder for your instance? Without a crash log, I cannot decipher the cause of your issue unfortunately.
> 
> Also, in the absence of a crash log, what leads you to believe that this is a Curios issue?

No there is no crash log, and I pretty sure its an issue with the artifacts mod as its only when I load the game with it

**Comment by TheIllusiveC4** [comment]
If it's an issue with the Artifacts mod and not Curios, you should report it to that developer instead for further investigation.
