### ISSUE TITLE
Exception caught during firing event: Trying to add tag of type 10 to list of 1

### ISSUE THREAD

**Issue by Lance5057** [TheIllusiveC4/Curios#282]
#### Versions (Be specific, do not write "latest"):
* Curios: 5.1.1.0
* Forge/Fabric: 42.2.3
#### Steps to Reproduce:
1. Die to drowning by an Infernal Mob (Maybe?)
...

Crash Log: [https://pastebin.com/6xzfegpK](https://pastebin.com/6xzfegpK)

**Comment by Lance5057** [comment]
[Cross Post to Corail Tombstones](https://github.com/Corail31/tombstone_lite/issues/133)

**Comment by TheIllusiveC4** [comment]
Based on your log this doesn't seem related to Curios, this seems like either an Infernal Mobs or Tombstone issue.
