### ISSUE TITLE
Game crashes while trying to open the curios GUI with a backpack from the sophisticated backpacks mod on the back slot

### ISSUE THREAD

**Issue by Darkem08** [TheIllusiveC4/Curios#287]
#### Versions:
* Curios:1.19.2-5.1.2.2
* Forge/Fabric:1.19.2-43.2.6
#### Steps to Reproduce: Unfortunately, i was not able to reproduce the bug, but it seems to be occurring while trying to render the golden backpack from the sophisticated backpacks mod

Crash Log: (https://hastebin.com/share/poneruwema.php).

If the solution is easy blame me, i dont know anything about coding

**Comment by TheIllusiveC4** [comment]
You should report this to Sophisticated Backpacks instead, as it is their rendering that is crashing and I have no control over that.
