### ISSUE TITLE
1.18.2 Can't create world. 

### ISSUE THREAD

**Issue by Swifty744** [TheIllusiveC4/Curios#294]
Hello, I love this mod and hope it gets fixed soon. I load up a world and it goes into an endless loop where the world will continously load and not stop no matter how long I wait. I have JEI and Curio enabled, nothing else and it gets stuck.

**Comment by TheIllusiveC4** [comment]
Please fill out the bug report template. I need at least the version numbers of your mods and Forge, as well as any logs from your session that loops.
