### ISSUE TITLE
Crash in dev environment Forge 1.19.4

### ISSUE THREAD

**Issue by Tiviacz1337** [TheIllusiveC4/Curios#295]
* Curios: 5.1.4.2
* Forge: 1.19.4 - 45.0.29
#### Steps to Reproduce:
1. add Curios 5.1.4.2 to dev environment

Crash Log: https://hastebin.com/share/ilusokesuj.scss

**Comment by Unixkitty** [comment]
Exact same issue, but in a 1.19.2 dev environment.

mod_minecraft_version = 1.19.2
mod_forge_version = 43.2.6
mappingsChannel = parchment
mappingsVersion = 2022.11.27-1.19.2
curios_version = 5.1.3.0

**Comment by TheIllusiveC4** [comment]
Sorry for the delay on this. The listed versions of Curios seem to work, from what I can tell, based on others and my own development. If this issue is still persisting, can someone share another crash log as well as their `build.gradle`? The crash log in the original post seems to have expired.

**Comment by Tiviacz1337** [comment]
Sure (1.19.4 Forge - 5.1.4.2
build.gradle: https://pastebin.com/jWsNwyrj 
full crash log: https://pastebin.com/rejjAY91

# Minecraft Version Information
minecraft_version=1.19.4

# Forge Version Information
forge_version=45.0.41
forge_version_toml=44

# Mappings Information
forge_mappings_version=1.19.3
parachment_mappings_version=2023.03.12-1.19.3

# Dependency Information
jei_mcversion=1.19.4-forge
jei_version=jei-1.19.4-forge\:13.1.0.2
curios_version=1.19.4-5.1.4.2

**Comment by Unixkitty** [comment]
Here's my log and some additional info from 1.19.2:
[5.1.3.0.log](https://github.com/TheIllusiveC4/Curios/files/11180207/5.1.3.0.log)

For me I found that the client actually runs fine in the dev environment with any 1.19.2 version, but **runData** ONLY runs with version 5.1.1.0, any version higher and it crashes with the error above.

P.S. The fellow above's log seems to no longer be available again, I'll just point out that when I found this bug at first I was able to read his first log and the error matched mine.

**Comment by TheIllusiveC4** [comment]
I think the issue is in the `build.gradle`. Make sure either of you have added this to each run configuration:

```
property 'mixin.env.remapRefMap', 'true'
property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
```
Example: https://github.com/illusivesoulworks/charmofundying/blob/7de1539091a22d55c4313f10f0ce53b64c00013e/forge/build.gradle#L53-L54

Let me know if that doesn't work.

**Comment by Unixkitty** [comment]
I'm afraid not... tried adding this to data {} in build.gradle that is failing, and it still crashes.

https://github.com/Unixkitty/gemspark/blob/1.19.2/build.gradle (Currently only present in client run because it did nothing in data)

I also tried adding the plugin bits in case that was part of it - no change
```groovy
buildscript {
    repositories {
        ...
        maven {
            name = 'Sponge / Mixin'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
        mavenCentral()
    }
    dependencies {
        ...
        classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
    }
}
...
apply plugin: 'org.spongepowered.mixin'
```

**Comment by Tiviacz1337** [comment]
Adding those lines to build.gradle fixed my issue on 1.19.4

**Comment by TheIllusiveC4** [comment]
> I'm afraid not... tried adding this to data {} in build.gradle that is failing, and it still crashes.

Just making sure, did you regenerate your run configurations after adding that?

**Comment by Unixkitty** [comment]
> > I'm afraid not... tried adding this to data {} in build.gradle that is failing, and it still crashes.
> 
> Just making sure, did you regenerate your run configurations after adding that?

Tested again, making sure to completely clear out runs and regenerate them, and this seems to have worked!
https://github.com/Unixkitty/gemspark/commit/852b9e0c8d33cbe7f35a90934f8d48fe27578b43

**Comment by TheIllusiveC4** [comment]
Okay great!
