### ISSUE TITLE
Add seperate slot for quiver

### ISSUE THREAD

**Issue by thederpykrafter** [TheIllusiveC4/Curios#297]
**Please describe the new feature or change.**

The quiver should have its own slot rather than using the back slot. The back slot is often used for backpacks and I don't want to have to pick one or the other.

**Please describe why you want this feature.**

The quiver is rendered on your hip, so it doesn't make a lot of sense for it to use the back slot.

**Comment by TheIllusiveC4** [comment]
Curios does not add any slots or items natively, you need to ask for this from the mod that adds the quiver that you're referring to.

**Comment by thederpykrafter** [comment]
Quiver is a vanilla item

**Comment by TheIllusiveC4** [comment]
I can't find any information on the quiver being a vanilla item. But regardless, my previous point still stands. Curios itself does not put any item into any slot or add any slots itself.

**Comment by thederpykrafter** [comment]
Sorry i thought vanilla used to have a quiver on a different version. It was supplementaries and I figured it out.
