### ISSUE TITLE
Tool Belt Slot missing

### ISSUE THREAD

**Issue by RegitCM** [TheIllusiveC4/Curios#299]
i'm running a mod pack in 1.19.3 with curious and "tool Belt". there is no "waist" slot showing up in the Curious UI. i'm not sure if this is a bug or if this is something to do with incompatible versions. 
Forge Version : 44.1.23
Curious Version : 5.1.4.1
Tool Belt Version : 1.19.7
     - Running "Sewing Kit" mod with this

**Comment by TheIllusiveC4** [comment]
This is an issue that you'd need to bring up with the Tool Belt developer, as I am not responsible for that functionality and it could be that their integration has changed.
