### ISSUE TITLE
Menu not opening

### ISSUE THREAD

**Issue by DeltaD99** [TheIllusiveC4/Curios#300]
I'm running a mod pack on 1.19.4 and for some reason when going to open the curio's menu nothing happens, I have both clicked the button in the inventory and the hotkey button but like I said nothing happens
Curios: 5.1.4.3
Forge: 45.0.43

**Comment by TheIllusiveC4** [comment]
Do you have a mod installed that adds a slot? By default, Curios has no slots.

**Comment by DeltaD99** [comment]
Oh... well technically I should but the doom mod doesn't add one for some reason I guess I should take this up with them.
