### ISSUE TITLE
Curios not functioning on a server in dawncraft.

### ISSUE THREAD

**Issue by Kriminalostrich** [TheIllusiveC4/Curios#306]
Hello, I wanted to report an issue and perhaps find a solution. On the DawnCraft Modpack I play on a server with a few friends. The Curios slots are all present and allow the input of the slot specific items, however these items do not function as they are intended when placed in a curio slot. Currently the only working curio slots are ones that have an inventory item like a backpack or a quiver, however the quiver does not pull arrows and can only be used to store arrows. I am not sure what the issue might be but I could not find any similar posts or discussions after scouring the internet. I would appreciate any feedback or insight towards the current situation. Thanks you

**Comment by TheIllusiveC4** [comment]
You need to fill out the bug report template with version numbers.

**Comment by Kriminalostrich** [comment]
I am not sure how to find the bug or any reports I am not the server owner, I just know them personally. There are no crashes resulting from the problem either, maybe it is not a bug but I just was not sure what the issue or conflict with the mod and online servers is. Everything works fine in singleplayer.

**Comment by TheIllusiveC4** [comment]
To be specific, I need at least the Forge version and the Curios version. In addition, is your server using any plugins in addition to mods?

**Comment by VictorSPM** [comment]
for the latest version of DawnCraft
Forge: Forge-40.2.1
Curios: curios-forge-1.18.2-5.0.9.0
