### ISSUE TITLE
[1.19.2] Fireflies Don't Work in Curio Slot

### ISSUE THREAD

**Issue by Flexico** [TheIllusiveC4/Curios#307]
Fireflies from the Twilight Forest can be worn on your head and light up the area around you, but it only works in the vanilla helmet slot, not the Head slot in the Curio menu, even though it specifically says it goes in the Head slot!

**Comment by TheIllusiveC4** [comment]
This is something you would need to bring up with the Twilight Forest developers, as Curios is not responsible for the functionality of specific mod items.

**Comment by Flexico** [comment]
Ah, ok! Thank you~
