### ISSUE TITLE
Unable to change server config

### ISSUE THREAD

**Issue by wosavim** [TheIllusiveC4/Curios#309]
Versions:
* Minecraft: 1.19.2
* Curios: 5.1.4.1
* Forge: 43.2.10

Observed Behavior: Curio server config file is generated in a world's `serverconfig` folder on world creation. (If the file was changed after world creation, the generated file also overwrites the custom one)

Expected Behavior: Curio server config file in modpack's `defaultconfigs` folder to be copied into a world's `serverconfig` folder on world creation.

Steps to Reproduce: 
1. make a new instance
2. add curios api
3. launch pack to generate usual folders/files for pack
4. make custom config for curios in `defaultconfig` folder (following directions in [this](https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users) wiki)
5. load pack and make new world
6. look in `serverconfig` folder of new world save at file `curios-server.toml`

The file I see contains the following, not what I had made in the other folder.
```
#List of curio slot type settings
curiosSettings = []
```
I can edit said file in the world's folder, however it is cleared and overwritten with the block above when I load the world.

No crashes to log, I am just trying to adjust the number of curios slots.

**Comment by TheIllusiveC4** [comment]
I just tested it really quickly and it works for me. The most likely cause of your issue is that your config is malformed for some reason. Can you share exactly what the config looks like that you're trying to set?

**Comment by wosavim** [comment]
In looking at the file to send here I found that I made a spelling error in the config file.. after fixing the file everything works as expected.
I need to get more sleep to avoid overlooking these simple mistakes in the future..

Thank you for your help
