### ISSUE TITLE
[1.14.4] Missing Recipe Book

### ISSUE THREAD

**Issue by Erfurt92** [TheIllusiveC4/Curios#31]
Not sure if this is a bug, oversight or if it's meant to be this way. But whenever I open the Curio inventory the Recipe Book disappears. I assume it's a bug/oversight, if not maybe it's something that could be added?

**Comment by ItsTheBdoge** [comment]
#34

**Comment by CREEATION** [comment]
was about to say "this is still happening with version `1.16.5-4.0.5.1`", but i guess this issue is related to the recipe book button and not the gui?

my issue is the recipe book gui closing.

1. open inventory
2. open recipe book gui
3. click curios button
4. recipe book gui closes
