### ISSUE TITLE
curios-server.toml settings is useless

### ISSUE THREAD

**Issue by willis1030** [TheIllusiveC4/Curios#317]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-forge-5.2.0-beta.3+1.20.1
* Forge/Fabric: Forge 
#### Observed Behavior:
[[curiosSettings]]
	identifier = "back"
	visible = true
	size = 2

but there is ony 1 back slot

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
There is no server config anymore in 1.20+. Slot registration and modification has all been moved to datapacks. See the updated guides here: https://docs.illusivesoulworks.com/category/curios
