### ISSUE TITLE
Curious 1.19.2-5.1.3.0 mixins crash

### ISSUE THREAD

**Issue by pasta-pasta** [TheIllusiveC4/Curios#322]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.19.2-5.1.3.0
* Forge/Fabric: 43.2.0
#### Observed Behavior: 
Developing mod with curious API. Running runClient task. Caught error at **Mixing MixinApplyBonusCount from curios.mixins.json into net.minecraft.world.level.storage.loot.functions.ApplyBonusCount**, crash. 
#### Expected Behavior:
Successfull run of runClient gradle task.
#### Steps to Reproduce:
1. IntelliJ IDEA, JDK 19, forge 43.2.0, gradle 8. Developed mod is still simple and don't override any core mechanics, nor does it use mixins in any way; i can provide zip if needed. 
2. Run gradle "run client" task. 

Crash Log:https://pastebin.com/m21ZMdF8
build.gradle file: https://pastebin.com/EkQRJpgU

**Comment by TheIllusiveC4** [comment]
Everything in your `build.gradle` looks correct, but I believe you should be using the `forge Client` run configuration and not just the runClient task.

**Comment by pasta-pasta** [comment]
Updated build.gradle file, now catching different error:https://pastebin.com/Q6SAxhzU
 https://pastebin.com/ZzVLFtBq

**Comment by pasta-pasta** [comment]
> Everything in your `build.gradle` looks correct, but I believe you should be using the `forge Client` run configuration and not just the runClient task.

thanks!
