### ISSUE TITLE
Curious module duplication crash 

### ISSUE THREAD

**Issue by pasta-pasta** [TheIllusiveC4/Curios#323]
#### Versions (Be specific, do not write "latest"):
* Curios: forge 1.19.2-5.1.3.0
* Forge/Fabric: forge 43.2.0
#### Observed Behavior:
After clean build, run runProject task. Caught error **Modules curios.forge and curios export package top.theillusivec4.curios.mixin to module ascendance**, full crash report below.
#### Expected Behavior:
Successfull start of client.
#### Steps to Reproduce:
1. Clone project repo: https://github.com/pasta-pasta/Ascendance
2. Use JDK 19. Perform clean build.
3. Start "runClient" gradle task and enjoy the crash.
...

Crash Log: https://pastebin.com/cp9y2FrH

**Comment by TheIllusiveC4** [comment]
You have Curios both in your `build.gradle` and your `mods` folder. You should not be putting it in your runtime `mods` folder since you're developing with it.
