### ISSUE TITLE
No more visibility toggle button & add command not working

### ISSUE THREAD

**Issue by Celi-161** [TheIllusiveC4/Curios#331]
#### Versions (Be specific, do not write "latest"):
* Curios: 5.2.0-beta.3+1.20.1
* Forge/Fabric: Forge 47.1.3
#### Steps to Reproduce:
1. I don't know. Download this version and see if the issues are showing up I guess?
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
I've fixed the command issue in-dev, however I don't see any issues with the visibility toggle. In my environment, the toggles appears just fine. Have you tested only loading up Curios and maybe one other mod to see if maybe it's a mod conflict somewhere?

**Comment by aAndrew3030** [comment]
Its the Cyclic mod, made a issue

**Comment by TheIllusiveC4** [comment]
Since this is likely a Cyclic issue, I'll close this thread. The other issue dealing with commands should be fixed as of the latest update.
