### ISSUE TITLE
1.19.2 Forge duping artifacts and other slots curios

### ISSUE THREAD

**Issue by GitJhopa** [TheIllusiveC4/Curios#333]
see video: https://youtu.be/2rkIJ1YYvc4

Dupe artifacts and other items that can be placed in Curious, must be wearing a backpack. I also use the Curious BackPack mod.

To dupe, the inventory must be full.

**Comment by TheIllusiveC4** [comment]
Since this is a specific interaction with the Curios Backpack mod, have you reported this to that developer? It may be the case that this is something only they can fix, and I don't know enough about their code to judge one way or another.
