### ISSUE TITLE
Multiplayer commands not working

### ISSUE THREAD

**Issue by killerkitt** [TheIllusiveC4/Curios#334]
#### Versions (Be specific, do not write "latest"):
* Curios:curios-forge-5.2.0-beta.3+1.20.1
* Forge/Fabric:47.1.3
#### Steps to Reproduce:
1. op player trying to add another ring slot 
2. /curios add (slot that doesnt work causes error)
3. checks for auto fill or anything and after pressing space it shows error after /curios add 
no Crash log just commands not working in multiplayer

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/327
Update to the latest Curios version, 5.2.0.

**Comment by killerkitt** [comment]
ok updated same problem saying when i type in /curios add head killerkitt 1, it says incomplete command see below and shows what i typed with a <-----
but the command goes through just doesnt auto fill so all good
