### ISSUE TITLE
[1.20.1] Its me again - tiered makes curios go boom boom

### ISSUE THREAD

**Issue by Cixon** [TheIllusiveC4/Curios#335]
#### Versions (Be specific, do not write "latest"):
* Curios: latest. (jk - 5.3.1)
* Forge/Fabric: Forge

#### Observed Behavior:
client start-up failure

#### Expected Behavior:
to load sucessfully

#### Steps to Reproduce:

1. Download Tiered among dependacy
2. Download Curios API
3. Launch client
4. Rarted

Crash Log:
https://gist.github.com/Cixon/f2b21302ad3db685596a1d2604b46cef

**Comment by TheIllusiveC4** [comment]
This looks like an error with a mixin from Tiered, so you will need to report this to that developer to get this addressed.
