### ISSUE TITLE
Curios Ui won't open

### ISSUE THREAD

**Issue by vholiday** [TheIllusiveC4/Curios#340]
Using the inventory button, or key bind, the curios UI won't open. This is just singleplayer Better Minecraft 4 modpack through curseforge.
#### Versions (Be specific, do not write "latest"):
* Curios: 5.3.4+ 1.20.1
* Forge/Fabric: 47.2.0

**Comment by TheIllusiveC4** [comment]
Which slots should be there and which mods provide them?

Have you tried with just that version of Curios and one or two mods to see if it's a mod conflict?

**Comment by MrKashew** [comment]
having similar issue, any luck
https://github.com/TheIllusiveC4/Curios/issues/347

**Comment by TheIllusiveC4** [comment]
Closing this as a duplicate of https://github.com/TheIllusiveC4/Curios/issues/347 as that thread has more relevant information as of now.
