### ISSUE TITLE
The server .toml resets when joining a world

### ISSUE THREAD

**Issue by Entyco** [TheIllusiveC4/Curios#341]
I tried adding a couple extra slots but they get reset when joining the worlds. It also doesn't help to make it a default config

**Comment by TheIllusiveC4** [comment]
Are you trying to do this in 1.20.x? Because the `curios-server.toml` file is no longer the method to add slots in that version, that's all done in datapacks as documented here:
https://docs.illusivesoulworks.com/category/curios
