### ISSUE TITLE
I'm not able to augment the number of slots

### ISSUE THREAD

**Issue by JisuCraft** [TheIllusiveC4/Curios#342]
#### Versions (Be specific, do not write "latest"):
*Minecraft: 1.20.1
* Curios: curios-forge-5.3.5+1.20.1.jar
* Forge/Fabric: 47.1.0
#### Steps to Reproduce:
1. I have created the file "Back.json" with this content: 
{
  "size": 2,
}
3. This file is in this path: C:\Users\lluis\curseforge\minecraft\Instances\Simple Mod Pack\saves\Jisu's World\data\curiosmasback\curios\slots

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
> C:\Users\lluis\curseforge\minecraft\Instances\Simple Mod Pack\saves\Jisu's World\data\curiosmasback\curios\slots

You don't put it into that folder, it should be part of a datapack in the `datapacks` folder.

**Comment by JisuCraft** [comment]
Hi!

I followed the steps from this link:

https://docs.illusivesoulworks.com/curios/slot-register

Thanks for your answer
