### ISSUE TITLE
Curios encountered error during sided setup 

### ISSUE THREAD

**Issue by homersmipson** [TheIllusiveC4/Curios#344]
#### Versions (Be specific, do not write "latest"):
* Curios: 5.3.5
* Forge/Fabric: 47.2.0
#### Steps to Reproduce:
1. Start minecraft with Ars mod which need curios to run
2. Load mods 
3. Curios mod problem pops up 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/XC4YxiGg

![image](https://github.com/TheIllusiveC4/Curios/assets/118036829/3d22d830-7eae-4747-bf58-b609da360c23)

**Comment by TheIllusiveC4** [comment]
This is an issue with the Tiered mod.
