### ISSUE TITLE
JEI Item List is moved on the wrong side

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/Curios#35]
#### Versions (Be specific, do not write "latest"):
* `Curios: v1.0.5.3`
* `Forge: v28.1.90`
* `JEI: v6.0.0.25`
#### Observed Behavior:
- The JEI item list is moved unnecessarily on the right side, as seen in the image below.

#### Expected Behavior:
- Only the JEI Favorite item list should be moved on the left side.

#### Steps to Reproduce:
1. Install JEI
2. Open the Curios inventory
...

![2019-11-13_20 19 12](https://user-images.githubusercontent.com/12000593/69209148-c546de80-0b1b-11ea-9af9-e053411acd70.png)

**Comment by TheIllusiveC4** [comment]
I can't reproduce this. It only ever applies to the left side for me.

Can you reproduce this with only Curios and JEI installed? Also, why does there not seem to be a Curios button on your inventory GUI?

**Comment by WenXin20** [comment]
It looks like the right side only does that on larger screen sizes, if I shrink my window size, jei moves back to the correct position.

Favorites side of jei does seem to be working.

As to why the curios button isn't there, I'm not sure why. It's in the top right corner, but invisible. I can still click on it too.

**Comment by WenXin20** [comment]
I'll try with only jei and curios next

**Comment by WenXin20** [comment]
After testing with only JEI and Curios, it looks like the JEI reposition bug still happens. The invisible button though looks to be a compatibility issue. I'll work on figuring out which mod causes the invisible button.
![2019-11-20_10 14 13](https://user-images.githubusercontent.com/12000593/69256099-8dbd4e00-0b7e-11ea-895d-040a840dc143.png)

**Comment by WenXin20** [comment]
Found out why the Curios Button was invisible. 

It only happens if I install the mods [Animated Recipe Book](https://www.curseforge.com/minecraft/mc-mods/animated-recipe-button) and [Fast Workbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench).

For some reason, the Animated Recipe Book mod makes a recipe book appear in the Curios inventory, which seems to replace the Curios button, not just overlap it, but is able to be clicked on to close the inventory still.

Once Fast Workbench is added, the button becomes invisible, since the mod removes the recipe book.

This should probably be addressed by the Animated Recipe Book mod.
Bit of an odd bug...

**Comment by WenXin20** [comment]
As a side note, I just found out the reposition config also moves the button in the Creative Player Menu. This might need to be separated from the survival menu.
