### ISSUE TITLE
Curios API encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by KapsiF** [TheIllusiveC4/Curios#350]
#### Versions
* Curios: curios-forge-5.4.2+1.20.1.jar
* Forge: 47.2.6
#### Observed Behavior:
Error
#### Expected Behavior: 
No Error
#### Steps to Reproduce:
1. Enable Curios API
2. Enable Iron's Spells and Spellbooks 
3. Crash.

Crash Log: 
https://pastebin.com/sHtN28ZP

![image](https://github.com/TheIllusiveC4/Curios/assets/73310940/33d0beeb-c666-4267-9256-5dd43ce6e289)

**Comment by KapsiF** [comment]
The crash does not occure with the mod "Tiered" is disabled
Issue created over at "Tiered" page https://github.com/Stereowalker/tiered/issues/65

**Comment by TheIllusiveC4** [comment]
This is an issue coming from Tiered, there's nothing I can do from my end.
