### ISSUE TITLE
[1.20.1] Curios Cosmetics cause glitched curios positionings.

### ISSUE THREAD

**Issue by PlayfulPiano** [TheIllusiveC4/Curios#353]
#### Versions (Be specific, do not write "latest"):
* Curios: 5.4.4
* Forge/Fabric: 47.2.8

![image](https://github.com/TheIllusiveC4/Curios/assets/3158887/9a551abb-6946-4223-8e19-16ddd5a33428)
I'm honestly unsure how this happens, and it seems to also mess up Sophisticated Backpacks, like so.
![image](https://github.com/TheIllusiveC4/Curios/assets/3158887/2d6db325-792c-4611-bea5-74a3f79b2fc9)

I didn't have this issue prior to the latest update, even when having two backpacks in my inventory.

**Comment by TheIllusiveC4** [comment]
Can you explain in more detail? I'm not sure what I'm looking at, or what the issue is. What positions are incorrect?

What do you mean by the Curios cosmetics? I don't see anything in your cosmetics slots, so I'm not sure if you're referring to those or something else. And what makes you think they are the cause of the bug?

Do you see any errors in your logs? Does reverting to the previous update fix the issue?

**Comment by PlayfulPiano** [comment]
In the first image you can see there are 2 magnets. I don't have 2 magnet slots, it seems to cause a duplicate slot that drags vertically as you scroll, changing it to a different slot that duplicates visually.

I normally don't even have cosmetic slots available (see the below image), so something causes the cosmetic slot column to start appearing, which is when these issues occur.
![image](https://github.com/TheIllusiveC4/Curios/assets/3158887/9c23adab-5c66-49fa-97b4-10ef5d43d6e1)

I was able to get this to trigger by having two of the same slot in my inventory as I swap dimensions. Note the slots across the following images.
![image](https://github.com/TheIllusiveC4/Curios/assets/3158887/64707a55-3703-413d-9e6e-821a666689c4)
![image](https://github.com/TheIllusiveC4/Curios/assets/3158887/1758e302-fdf1-4560-85ea-eb65e55cda0d)


I don't seem to notice any errors in my log related to curios. I'll try testing it out in the previous version next.

**Comment by PlayfulPiano** [comment]
Here is my latest log in case there's something you can see that I didn't spot. The dimension change that is shown in the above images is towards the end of the log.
[latest.log](https://github.com/TheIllusiveC4/Curios/files/13507983/latest.log)

**Comment by PlayfulPiano** [comment]
Can now confirm this does not occur when switching dimensions in v5.4.3

**Comment by BrandonPotter0** [comment]
Ive had an identical issue that seemed to pop up when I died. I go back to collect my gear, and when I go to requipp all the dropped stuff, I have the exact same issue. Slot graphics seemed to get switched around, but the slots function normally. Save/Quitting and going back into the world fixes the issue until the next time I die.

**Comment by TheIllusiveC4** [comment]
Are you saying that switching dimensions _causes_ this or that it _fixes_ it (in the latest version)?

> Ive had an identical issue that seemed to pop up when I died.

Is this also on the latest version?

**Comment by BrandonPotter0** [comment]
> Are you saying that switching dimensions _causes_ this or that it _fixes_ it (in the latest version)?
> 
> > Ive had an identical issue that seemed to pop up when I died.
> 
> Is this also on the latest version?

I do not switch dimensions at all. Happens in the overworld that I have seen so far. Saving/Quitting, and logging/loading back into the world fixes it. Like the UI was refreshed.

This happens on Version 5.4.4 on MC Version 1.20.1

**Comment by TheIllusiveC4** [comment]
The dimension comment was for OP, my apologies for the confusion.

**Comment by BrandonPotter0** [comment]
> The dimension comment was for OP, my apologies for the confusion.

Whoops, Sorry.

**Comment by PlayfulPiano** [comment]
> Are you saying that switching dimensions _causes_ this or that it _fixes_ it (in the latest version)?
> 
> > Ive had an identical issue that seemed to pop up when I died.
> 
> Is this also on the latest version?

It was at least *a* cause I found in the latest version (5.4.4), but does not occur in the previous (5.4.3). I first experienced this issue when I found a second backpack while in the nether, so I think the main cause comes from having multiple items of the same slot in your inventory at once. Might be specifically items that have storage themselves (e.g. sophisticated backpacks).

**Comment by PlayfulPiano** [comment]
Actually based on what brandon said, it's probably based on a refresh of your inventory. I'm going to assume that going between dimensions forces a refresh, and it would make sense that picking up items after dying would as well.

Will say that dropping and picking up a backpack in v5.4.3 (previous) does not cause the issue. I'm going to update again and see if doing just that will cause an issue.

**Comment by BrandonPotter0** [comment]
I also use Sophisticated Backpacks. Might there possibly be a conflict?

**Comment by PlayfulPiano** [comment]
> I also use Sophisticated Backpacks. Might there possibly be a conflict?

If there is one it had to come from the latest update, which could make sense since the latest update allowed for entering and exit container inventories using the curios inventory hotkey as per a previous report I did.

**Comment by TheIllusiveC4** [comment]
Okay, thanks for all the info. I think I know what's happening. Fix incoming.

**Comment by BrandonPotter0** [comment]
Fantastic :) Fingers crossed. I thought my game was horribly broken. Haha.

**Comment by PlayfulPiano** [comment]
Can now confirm on latest (v5.4.4) that:
- I started my world with two backpacks in my inventory
- There are no inventory issues, curios doesn't show cosmetic items
- dropping and picking up a backpack doesn't cause issues.
- placing and picking up a backpack doesn't cause issues.
- placing both backpacks and picking them up doesn't cause issues.
- Swapping dimensions *does* cause issues, cosmetics column appears, etc. etc..

**Comment by PlayfulPiano** [comment]
> > Are you saying that switching dimensions _causes_ this or that it _fixes_ it (in the latest version)?
> > > Ive had an identical issue that seemed to pop up when I died.
> > 
> > 
> > Is this also on the latest version?
> 
> I do not switch dimensions at all. Happens in the overworld that I have seen so far. Saving/Quitting, and logging/loading back into the world fixes it. Like the UI was refreshed.
> 
> This happens on Version 5.4.4 on MC Version 1.20.1

also can confirm that relogging fixes the visual

**Comment by PlayfulPiano** [comment]
Notable update here, just had this happen to me from swapping dimensions without having a second backpack in my inventory. I'm unsure why, but hopefully the fix you're working on will fix this too.

**Comment by BrandonPotter0** [comment]
Got the bug to show up when I went to visit the Twilight Forest for the first time

**Comment by TheIllusiveC4** [comment]
This should be fixed in version 5.4.5.

**Comment by BrandonPotter0** [comment]
It looks like it has been fixed! Good job!

**Comment by PlayfulPiano** [comment]
Yeah can confirm dimension swapping is fixed.
