### ISSUE TITLE
Curious API (curious) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by PhoqueMeister** [TheIllusiveC4/Curios#354]
### Minecraft Version

1.20.1

### What happened?

I was watching some YT videos of minecraft and that motivated me to play it and so I try to download the mods that will enhance Vanilla minecraft but not so much that it adds like a lot of stuff as well. When I finished downloading the mods, I tried starting it. It went well at first but then I get the following message:

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

I tried switching Mod versions but it wouldnt work, so now I'm here asking on what to do.
Though maybe its because I tried downloading 117 mods e.e

### How do you trigger this bug?

1. I download mods
2. Realized I forgot some mods so I installed the necessary mods to run the other mods
3. Boom the message appeared
...

### Loader

Forge

### Loader Version

Forge - 47.2.6

### Mod Version

Curious 5.4.5+1.20.1

**Comment by TheIllusiveC4** [comment]
Can you share the crash log? Otherwise, I don't know where the error may be coming from.

**Comment by PhoqueMeister** [comment]
Oh uhh sorry, I should have answered earlier but I got caught up with
college work and stuff.Anyways, everything is good now. Asked my friend
what's going on and he helped me with it. Sorry to waste your time.
