### ISSUE TITLE
[Bug]: Crash when modifying HUD positions when using Inventory HUD + & ATM9

### ISSUE THREAD

**Issue by PlayfulPiano** [TheIllusiveC4/Curios#358]
### Minecraft Version

1.20.1

### What happened?

I just added in Inventory HUD+ to ATM9, and when I was trying to modify the config for IHUD it caused a crash.

### How do you trigger this bug?

1. Install ATM9
2. Add Inventory HUD + (v3.4.18)
3. Go into IHUD's config to modify HUD positions.
4. Hit "esc".
5. Crashes.
...

### Loader

Forge

### Loader Version

47.2.16

### Mod Version

5.4.5

### Relevant Log Outputs

[crash-2023-12-10_12.11.23-client.txt](https://github.com/TheIllusiveC4/Curios/files/13628641/crash-2023-12-10_12.11.23-client.txt)

**Comment by TheIllusiveC4** [comment]
It seems like Inventory HUD+ is trying to pass a `null` entity to Curios, which is causing the crash as it's not expected. Technically could be fixed on either end, but I'll go ahead and do some validations on my end that'll also fix this.
