### ISSUE TITLE
[Feature]: Add an option in the configuration interface to disable the button for the GUI interface.

### ISSUE THREAD

**Issue by QianFuv** [TheIllusiveC4/Curios#362]
### What is the new feature or improvement?

As the title suggests, it's about disabling that small button. I believe adding this configuration option shouldn't be too difficult. Some people prefer to open the accessory bar using keyboard shortcuts.

**Comment by QianFuv** [comment]
Thanks for checking it out! Please ping me if this feature is released! Hope to receive an update to this feature in 1.19.2, thank you for your efforts!

**Comment by TheIllusiveC4** [comment]
This is now a configuration option in 1.19.2, 1.20.1, and 1.20.4+.

**Comment by QianFuv** [comment]
Thank you!
