### ISSUE TITLE
[Bug]: MorePlayerModels and Curios compatibility problems only on Aternos?

### ISSUE THREAD

**Issue by HideDude** [TheIllusiveC4/Curios#367]
### Minecraft Version

1.18.2

### What happened?

Hello guys. This bug or problem has melted my mind. I tried three whole days to fix it and nothing but i have some interesting things.

So, i have an Aternos server with friends. We installed some mods, everything is fine. Curios API was one of them, along with Artifacts. All good. Then we **installed More Player Models.** All good when we entered on the server and tested it. We only had a problem: the extra inventory that Curios add doesn't show up, not with the button assigned, not with clicking on the character, nothing. 

I tried to fix it for three days as i said. I tried everything, like testing it without some mods, generating a new world, commands, pack textures, configuration, nothing.

Then we step up with the **FIRST WEIRD THING:** Those two mods (Curios and More Player Models) work perfectly fine on a Singleplayer world... but not on Aternos.

![2 English](https://github.com/TheIllusiveC4/Curios/assets/156980276/07c62ee8-26cc-4409-9d39-34a10bb79412)

After a lot of testing. We find another thing.

The "/curios reset" command make the two mods work together again on Aternos. But we lose all the items we had equipped because we can't open the inventory to grab them. (Backpacks included), and when you enter on the server after a log out, the mod gets screwed again and have to do the command again.

**THE LAST WEIRD THING:**  On Aternos, i did /kill and respawned... then the mods works fine. It's the safest solution we have at the moment. But we have to do it everytime we enter on the server. 

That's it at the moment. Please help us. We don't really know what to do, we want to use Curios and More Player Models at the same time. 

Thank you! Oh, and i leave the list of mods we have here if it helps.

![Mods](https://github.com/TheIllusiveC4/Curios/assets/156980276/22ebe234-df3a-4243-a75d-64bb9c453af8)

### How do you trigger this bug?

1. Installed More Player Models
2. Log in on Aternos server
3. Try to open the extra Curios API inventory
4. Nothing happens.

...

### Loader

Forge

### Loader Version

40.2.14

### Mod Version

Curios 1.18.2-5.0.9.2

**Comment by TheIllusiveC4** [comment]
1. Do you have anything on the server that isn't on your client?
2. Is your server a pure Forge server, no plugins or anything extra?
3. Does the problem go away if you remove More Player Models?

**Comment by HideDude** [comment]
> 1. Do you have anything on the server that isn't on your client?
> 2. Is your server a pure Forge server, no plugins or anything extra?
> 3. Does the problem go away if you remove More Player Models?
-----
> 1. A few client side mods, that didn't figure on Aternos mod list (So you can't install on the server and doesn't need to), for example Ambient Sounds.
> 2. No, it's Arclight. Sorry for not pointing that earlier
> 3. Okay that's... weird. I tested it removing the following mods: Cosmetic Armour, JEI and the MorePlayerModels itself (Those that can change a bit the inventory, and also those i installed before all the problem)... And Curios still don't work fine. Didn't know that.

**Comment by TheIllusiveC4** [comment]
> No, it's Arclight. Sorry for not pointing that earlier

If you have plugins installed, any number of them could have an adverse effect on Curios since mods and plugins were not built to run in the same environment. In particular, loading Curios with the SkinsRestorer plugin has been known to cause this issue. In addition, Curios was not built to run on Arclight itself so the environment could also be a factor.
