### ISSUE TITLE
[Visual Bug]: Curio items aren't rendering properly

### ISSUE THREAD

**Issue by SireAwfulThe1st** [TheIllusiveC4/Curios#371]
### Minecraft Version

1.20.1

### What happened?

![2024-02-03_08 18 48](https://github.com/TheIllusiveC4/Curios/assets/106896635/2a6a0741-3cca-4a28-bcd7-76a08e709a3b)
Seems like suddenly Curio items started rendering improperly, rather than rendering said items in their respective places (e.g Catalysm's sticky hands and sand in a bottle aren't rendered on the player's hands and waist as a belt respectively. It seems nearly every item are rendered on the chest instead. Not sure what happened but I have a suspicion Quark perhaps caused this cuz I had only noticed this bug as soon as Quark was downloaded. 
Doesn't seem to visually affect all Curio items tho, as Supplementaries's Quiver are rendered on the hips properly, so does CERBON's Better totem of undying.
![2024-02-01_20 01 57](https://github.com/TheIllusiveC4/Curios/assets/106896635/492992ef-6d97-43a5-bea1-da6afcc1ee7f)
![2024-02-01_20 02 03](https://github.com/TheIllusiveC4/Curios/assets/106896635/f39ac60f-fc86-48d0-9156-da3862efd886)
The two images provided is a showcase of how it usually renders properly.

### How do you trigger this bug?

1. Didn't do anything specific, only logged onto world to check up on a few things and only quickly noticed curio items aren't rendering properly soon.

### Loader

Forge

### Loader Version

Forge - 47.2.17

### Mod Version

Curious 5.6.1+1.20.1

**Comment by TheIllusiveC4** [comment]
Does this happen if you have _only_ Curios and those mods with those items installed?

**Comment by SireAwfulThe1st** [comment]
> Does this happen if you have _only_ Curios and those mods with those items installed?

Will check soon, I'll notify you soon when I do.

**Comment by SireAwfulThe1st** [comment]
> Does this happen if you have _only_ Curios and those mods with those items installed?

This _doesn't_ seem to happen when the above steps are done, so what should I do at this point?

**Comment by TheIllusiveC4** [comment]
You'll need to figure out which mod is causing this issue. If you know this worked before, then you can try starting with the set of mods you know it works with and then slowly add some of the other mods until you find which one causes the issue.

**Comment by SireAwfulThe1st** [comment]
> You'll need to figure out which mod is causing this issue. If you know this worked before, then you can try starting with the set of mods you know it works with and then slowly add some of the other mods until you find which one causes the issue.

noted, will notify you if I ever find anything further down the line.

**Comment by SireAwfulThe1st** [comment]
> You'll need to figure out which mod is causing this issue. If you know this worked before, then you can try starting with the set of mods you know it works with and then slowly add some of the other mods until you find which one causes the issue.

Hello, seems like this isn't a curio issue, this is actually a Better totem of undying's issue as applying BTOU intae the respective curio slot seems to make the appearance of Cataclysm's items tae bug out on your player model. I'll report tae the Cerbon's team ASAP.
