### ISSUE TITLE
[Feature]: Better Scrolling

### ISSUE THREAD

**Issue by IdrisQe** [TheIllusiveC4/Curios#372]
### What is the new feature or improvement?

Currently the scrolling when a lot of slots are present is a bit clunky, requiring multiple scrolls (with a notched scrollwheel on my Razer Basilisk V3 for example) to go down a single slot in some cases despite there not being that many slots to go through. See:
![curiscroll](https://github.com/TheIllusiveC4/Curios/assets/40530630/b1e1e86e-4039-4b1f-afba-663721156acd)

It would be nice if the scrolling would adapt to how many slots are present so that they fit the scroll length more naturally, having the scroll bar have greater effect the less slots there are - so if you only have 12 slots for example, scrolling just once would cause the 4 hidden ones to scroll up or down. Perhaps just a scroll-sensitivity config if having it automatically adapt is out of scope?

**Comment by TheIllusiveC4** [comment]
The latest 1.20.1 and 1.20.4 releases have some better scrolling logic so that it scales better with the slot amounts.
