### ISSUE TITLE
[Bug]: Menu not open

### ISSUE THREAD

**Issue by elpixel0** [TheIllusiveC4/Curios#373]
### Minecraft Version

1.20.1

### What happened?

when I try to open the menu it does not open, I reinstalled the latest version of the mod and the problem continues, I have installed optifine and another mod compatible with curios.

### How do you trigger this bug?

i really don't know, i just download the mod and every time i try to open de curios menu it did'nt open

### Loader

Forge

### Loader Version

forge-1.20.1-47.2.20

### Mod Version

curios-forge-5.6.0+1.20.1

**Comment by TheIllusiveC4** [comment]
Do you have any mods installed that give slots? By itself, Curios does not give any slots and without slots there will be nothing in the menu.

**Comment by elpixel0** [comment]
well i have Weapons of Miracle installed, the last version of cruios i used the menu was displayed when I pressed the icon

**Comment by TheIllusiveC4** [comment]
It doesn't seem like Weapons of Miracle adds any curio slots. If you saw slots when you last installed Curios, then you likely had some other mods installed that did add slots.

**Comment by elpixel0** [comment]
I see, sorry for the inconvenience, I haven't used the mod for a long time and the last time I used it was in 2019.
