### ISSUE TITLE
[Bug]: ModernFix + curios-forge-1.19.2-5.1.6.1.jar

### ISSUE THREAD

**Issue by Krimatoria** [TheIllusiveC4/Curios#375]
### Minecraft Version

1.19.2

### What happened?

Log Spam

### How do you trigger this bug?

Launch Game with curios-forge-1.19.2-5.1.6.1.jar + modernfix-forge-5.13.0+mc1.19.2.jar

### Loader

Forge

### Loader Version

Forge 43.3.5

### Mod Version

curios-forge-1.19.2-5.1.6.1.jar

### Relevant Log Outputs

[10Feb2024 16:13:58.033] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: C:\Users\********\Downloads\MultiMC\MultiMC\instances\1.19.21\.minecraft\mods\curios-forge-1.19.2-5.1.6.1.jar
[10Feb2024 16:14:39.366] [Render thread/WARN] [ModernFix/]: PathResourcePack base class instantiated with root path of mod file curios-forge-1.19.2-5.1.6.1.jar. This probably means a mod should be calling ResourcePackLoader.createPackForMod instead. Applying workaround.

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this as this does not happen when I install Curios and ModernFix together. Have you tried this with _just_ those two mods installed?

**Comment by Krimatoria** [comment]
> Я не могу воспроизвести это, поскольку этого не происходит, когда я устанавливаю Curios и ModernFix вместе. Вы пробовали это сделать, установив _только_ эти два мода?

I have 281 mods in the build, I'm just complementing FearNightfall for myself. I can try to run a separate clean build and see. I'll take another look, maybe there's something else in the logs that indicates this. Since it will take a very long time for 280+ launches with 2 separate mods)

**Comment by Krimatoria** [comment]
These are the errors that were in the current launch of the entire 280 mods build

[main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: C:\Users\********\curseforge\minecraft\Instances\Fear Nightfall (1)\mods\curios-forge-1.19.2-5.1.4.4.jar
[Render thread/WARN] [ModernFix/]: PathResourcePack base class instantiated with root path of mod file curios-forge-1.19.2-5.1.4.4.jar. This probably means a mod should be calling ResourcePackLoader.createPackForMod instead. Applying workaround.

**Comment by TheIllusiveC4** [comment]
If you cannot get the same error with just Curios and ModernFix installed and no other mods, then it's likely another mod that is somehow causing this issue. I will need to know which mod that is in order to investigate further. You can try and find the source by removing half of the mod list at a time (instead of one by one) to cut down on the number of tests you need to do.

**Comment by Krimatoria** [comment]
> Если вы не можете получить ту же ошибку, если установлены только Curios и ModernFix и нет других модов, то, скорее всего, эту проблему каким-то образом вызывает другой мод. Мне нужно будет знать, что это за мод, чтобы продолжить расследование. Вы можете попытаться найти источник, удаляя половину списка модов за раз (а не один за другим), чтобы сократить количество тестов, которые вам нужно выполнить.

Yes, I understand) I'll try it later today)

**Comment by Krimatoria** [comment]
> If you cannot get the same error with just Curios and ModernFix installed and no other mods, then it's likely another mod that is somehow causing this issue. I will need to know which mod that is in order to investigate further. You can try and find the source by removing half of the mod list at a time (instead of one by one) to cut down on the number of tests you need to do.

![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/c33b643b-29b5-4996-9078-892b2f05dfab)
I forgot to add a screenshot))) And orange is not a mistake, right?) Ahha

**Comment by Krimatoria** [comment]
> If you cannot get the same error with just Curios and ModernFix installed and no other mods, then it's likely another mod that is somehow causing this issue. I will need to know which mod that is in order to investigate further. You can try and find the source by removing half of the mod list at a time (instead of one by one) to cut down on the number of tests you need to do.

@TheIllusiveC4 🔥

I found what causes this from 280+ mods) by accident and at the very beginning. I don't know, I haven't checked the rest, but I think that's the problem, since this is a major mod.

[12Feb2024 04:24:04.612] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: C:\Users\********\Downloads\MultiMC\MultiMC\instances\1.19.22\.minecraft\mods\curios-forge-1.19.2-5.1.6.1.jar

The hint was in plain sight, but I didn't notice it) "Instances\Fear Nightfall"

This is a mod - aether-1.19.2-1.2.0- forge.jar 
The Fear Nightfall build will not start if there is no Aether+ Terraphobia. I decided to just remove the phobia and leave only Aether. And lo and behold, in one case there is an error, in the other there is none) I hope this helps) Tetraphobia may also have some effect, but it cannot be checked separately. Minecraft will just crash and ask you to install The End of Herobrine and Aether as they are connected.

Fuhhhh)))

![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/ab219e55-724d-418a-bdd0-db249d57b10d)
![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/0f11bb36-5e3d-4c1c-a2b2-6b9778b9b41e)

**Comment by TheIllusiveC4** [comment]
The error you're referring to in your last message is different than the one in your original message. This error, "Attempted to select a dependency jar for JarJar...", is not a problem as it just explains that there is a mod that has embedded Curios and there is also a Curios mod file installed. So it's technically installed twice, but it will only load one, but this won't usually have any noticeable effect.

The error that this was originally about and I am unable to replicate is "PathResourcePack base class instantiated with root path of mod file curios-forge-1.19.2-5.1.6.1.jar".

**Comment by Krimatoria** [comment]
> Ошибка, о которой вы говорите в своем последнем сообщении, отличается от ошибки в исходном сообщении. Эта ошибка «Попытка выбрать jar-файл зависимостей для JarJar...» не является проблемой, поскольку она просто объясняет, что существует мод, в который встроен Curios, а также установлен файл мода Curios. Таким образом, технически он устанавливается дважды, но загружает только один, но обычно это не оказывает заметного эффекта.
> 
> Ошибка, о которой изначально говорилось, и которую я не могу воспроизвести, - это «базовый класс PathResourcePack, созданный с использованием корневого пути файла мода curios-forge-1.19.2-5.1.6.1.jar».

How confusing everything is, I didn't see that they were different.
