### ISSUE TITLE
[Bug]: Insufficient number of affixes 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [TheIllusiveC4/Curios#376]
### Minecraft Version

1.19.2

### What happened?

Logs Spam
![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/2c0f4f69-dc0f-4880-a696-f8a1a6283f7f)

### How do you trigger this bug?

Launch game with mods

### Loader

Forge

### Loader Version

Forge 43.3.7

### Mod Version

curios-forge-1.19.2-5.1.6.1.jar

### Relevant Log Outputs

<html>
<body>

[15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:backRequired: 2; Provided: 0
--
7199 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:walletRequired: 2; Provided: 0
7200 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_ringRequired: 2; Provided: 0
7201 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_pendantRequired: 2; Provided: 0
7202 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_glovesRequired: 2; Provided: 0
7203 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_shieldRequired: 2; Provided: 0
7204 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:charmRequired: 2; Provided: 0
7205 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:backRequired: 3; Provided: 0
7206 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:walletRequired: 3; Provided: 0
7207 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_ringRequired: 3; Provided: 0
7208 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_pendantRequired: 3; Provided: 0
7209 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_glovesRequired: 3; Provided: 0
7210 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_shieldRequired: 3; Provided: 0
7211 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:charmRequired: 3; Provided: 0
7212 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:backRequired: 2; Provided: 0
7213 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:walletRequired: 2; Provided: 0
7214 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_ringRequired: 2; Provided: 0
7215 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_pendantRequired: 2; Provided: 0
7216 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_glovesRequired: 2; Provided: 0
7217 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_shieldRequired: 2; Provided: 0
7218 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:charmRequired: 2; Provided: 0
7219 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:backRequired: 3; Provided: 0
7220 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:walletRequired: 3; Provided: 0
7221 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_ringRequired: 3; Provided: 0
7222 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_pendantRequired: 3; Provided: 0
7223 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_glovesRequired: 3; Provided: 0
7224 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_shieldRequired: 3; Provided: 0
7225 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:charmRequired: 3; Provided: 0
7226 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:backRequired: 2; Provided: 0
7227 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:walletRequired: 2; Provided: 0
7228 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_ringRequired: 2; Provided: 0
7229 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_pendantRequired: 2; Provided: 0
7230 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_glovesRequired: 2; Provided: 0
7231 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_shieldRequired: 2; Provided: 0
7232 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:charmRequired: 2; Provided: 0
7233 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:backRequired: 4; Provided: 0
7234 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:walletRequired: 4; Provided: 0
7235 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_ringRequired: 4; Provided: 0
7236 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_pendantRequired: 4; Provided: 0
7237 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_glovesRequired: 4; Provided: 0
7238 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_shieldRequired: 4; Provided: 0
7239 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:charmRequired: 4; Provided: 0
7240 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
7241 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2
7242 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:backRequired: 3; Provided: 0
7243 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:walletRequired: 3; Provided: 0
7244 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_ringRequired: 3; Provided: 0
7245 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_pendantRequired: 3; Provided: 0
7246 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_glovesRequired: 3; Provided: 0
7247 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_shieldRequired: 3; Provided: 0
7248 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:charmRequired: 3; Provided: 0
7249 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:backRequired: 4; Provided: 0
7250 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:walletRequired: 4; Provided: 0
7251 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_ringRequired: 4; Provided: 0
7252 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_pendantRequired: 4; Provided: 0
7253 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_glovesRequired: 4; Provided: 0
7254 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_shieldRequired: 4; Provided: 0
7255 | [15:56:37] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:charmRequired: 4; Provided: 0
  |  

<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>

[16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:backRequired: 2; Provided: 0
--
8891 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:walletRequired: 2; Provided: 0
8892 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_ringRequired: 2; Provided: 0
8893 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_pendantRequired: 2; Provided: 0
8894 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_glovesRequired: 2; Provided: 0
8895 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:aether_shieldRequired: 2; Provided: 0
8896 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity common for category curios:charmRequired: 2; Provided: 0
8897 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:backRequired: 3; Provided: 0
8898 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:walletRequired: 3; Provided: 0
8899 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_ringRequired: 3; Provided: 0
8900 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_pendantRequired: 3; Provided: 0
8901 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_glovesRequired: 3; Provided: 0
8902 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:aether_shieldRequired: 3; Provided: 0
8903 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity uncommon for category curios:charmRequired: 3; Provided: 0
8904 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:backRequired: 2; Provided: 0
8905 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:walletRequired: 2; Provided: 0
8906 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_ringRequired: 2; Provided: 0
8907 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_pendantRequired: 2; Provided: 0
8908 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_glovesRequired: 2; Provided: 0
8909 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_shieldRequired: 2; Provided: 0
8910 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:charmRequired: 2; Provided: 0
8911 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:backRequired: 3; Provided: 0
8912 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:walletRequired: 3; Provided: 0
8913 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_ringRequired: 3; Provided: 0
8914 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_pendantRequired: 3; Provided: 0
8915 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_glovesRequired: 3; Provided: 0
8916 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:aether_shieldRequired: 3; Provided: 0
8917 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity rare for category curios:charmRequired: 3; Provided: 0
8918 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:backRequired: 2; Provided: 0
8919 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:walletRequired: 2; Provided: 0
8920 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_ringRequired: 2; Provided: 0
8921 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_pendantRequired: 2; Provided: 0
8922 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_glovesRequired: 2; Provided: 0
8923 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_shieldRequired: 2; Provided: 0
8924 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:charmRequired: 2; Provided: 0
8925 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:backRequired: 4; Provided: 0
8926 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:walletRequired: 4; Provided: 0
8927 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_ringRequired: 4; Provided: 0
8928 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_pendantRequired: 4; Provided: 0
8929 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_glovesRequired: 4; Provided: 0
8930 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:aether_shieldRequired: 4; Provided: 0
8931 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:charmRequired: 4; Provided: 0
8932 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
8933 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2
8934 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:backRequired: 3; Provided: 0
8935 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:walletRequired: 3; Provided: 0
8936 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_ringRequired: 3; Provided: 0
8937 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_pendantRequired: 3; Provided: 0
8938 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_glovesRequired: 3; Provided: 0
8939 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_shieldRequired: 3; Provided: 0
8940 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:charmRequired: 3; Provided: 0
8941 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:backRequired: 4; Provided: 0
8942 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:walletRequired: 4; Provided: 0
8943 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_ringRequired: 4; Provided: 0
8944 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_pendantRequired: 4; Provided: 0
8945 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_glovesRequired: 4; Provided: 0
8946 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:aether_shieldRequired: 4; Provided: 0
8947 | [16:01:19] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:charmRequired: 4; Provided: 0

</body>
</html>

**Comment by TheIllusiveC4** [comment]
I don't know what mod is logging these errors, but it is not from Curios. You will need to ask the developers of whichever mod adds these affixes and loot rules about this error.

**Comment by Krimatoria** [comment]
> Я не знаю, какой мод регистрирует эти ошибки, но он не от Curios. Вам нужно будет узнать об этой ошибке у разработчиков того мода, который добавляет эти аффиксы и правила добычи.

He adds items necessary for enchantments to the loot from all mobs, there is a random effect of the appearance of objects of different rarity that are inserted into objects. What do I need to do about it?) Should I write to Apotheosis about this problem? @TheIllusiveC4

**Comment by TheIllusiveC4** [comment]
If this error is coming from Apotheosis, then yes, you should discuss it with that developer and see what they say about it.
