### ISSUE TITLE
[Bug]: Heartstone from Heartstone mod doesnt add a slot type

### ISSUE THREAD

**Issue by AnonymisedFellow** [TheIllusiveC4/Curios#378]
### Minecraft Version

1.20.1

### What happened?

Heartstone doesnt register the charm slot, you can see it in the item but the slot is not there
Also, editing the curios-server.toml file according to the tutorial doesnt work, it always resets to the previous unedited state, on server it spits out a message that config is incorrect and resets it immedietaly, read only just crashes the server
When trying curios add charm it states that charm is not a valid value
https://www.curseforge.com/minecraft/mc-mods/heartstone/files/4851350 - latest version as of today
![image](https://github.com/TheIllusiveC4/Curios/assets/24274546/16c1810c-6eaa-4eb4-8c3a-b14014a3a79a)
![image](https://github.com/TheIllusiveC4/Curios/assets/24274546/5a19eb37-afdd-4b6f-8ad6-2046d45f421a)
![image](https://github.com/TheIllusiveC4/Curios/assets/24274546/bc725dc3-1a4d-4c95-a937-029815d16d65)
on client and server the situation is the same, files from elytra and create look the same to me, i dont know why it refuses to work

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

47.2.20

### Mod Version

5.7.0 & 5.6.1 - 1.20.1

**Comment by AnonymisedFellow** [comment]
made a typo when curios add charm, 
![image](https://github.com/TheIllusiveC4/Curios/assets/24274546/f5337691-9ca4-457a-af0f-8fe1a901d230)
upper case doesnt help

**Comment by AnonymisedFellow** [comment]
Just noticed that toggle visibility works only for the head 
![image](https://github.com/TheIllusiveC4/Curios/assets/24274546/58631c5f-3aa8-4f29-8d23-01d4d65ddbdd)

**Comment by AnonymisedFellow** [comment]
`curiosSettings = []`
[[curiosSettings]]
  identifier = "charm"
adding this crashes the game, obviously
curiosSettings = []
[[curiosSettings]]
  identifier = "charm"
just resets
[[curiosSettings]]
  identifier = "charm"
also resets

**Comment by AnonymisedFellow** [comment]
And on top of that, when an item has changed texture via resourcepack, using NBT, like in optifine etc, when its put into the slot it reverses to the original one, (icon doesnt change)

**Comment by TheIllusiveC4** [comment]
I cannot control whether Heartstone adds a Charm slot, you'll need to report that to the Heartstone developer.

> Also, editing the curios-server.toml file according to the tutorial doesnt work, it always resets to the previous unedited state, on server it spits out a message that config is incorrect and resets it immedietaly, read only just crashes the server

On 1.20.1 and above, the new way of adding and editing slots is through datapacks:

https://docs.illusivesoulworks.com/curios/slot-register
https://docs.illusivesoulworks.com/curios/entity-register

Since you're trying to add a charm slot, which is a preset slot type from Curios, you'll only need the second link. The configuration tutorial is only for 1.19.x and below.

> Just noticed that toggle visibility works only for the head

This may or may not be a bug in Curios. Mods sometimes will override the toggle visibility feature. I'll need to know which mods provide the items in your screenshot in order to investigate further.

**Comment by AnonymisedFellow** [comment]
> This may or may not be a bug in Curios. Mods sometimes will override the toggle visibility feature. I'll need to know which mods provide the items in your screenshot in order to investigate further.

Its a quiver from supplementaries and elytraslot, quiver seems to be overridden, its still there even when not in the slot

> Since you're trying to add a charm slot, which is a preset slot type from Curios, you'll only need the second link. The configuration tutorial is only for 1.19.x and below.

Ive added that datapack myself and now it works

> And on top of that, when an item has changed texture via resourcepack, using NBT, like in optifine etc, when its put into the slot it reverses to the original one, (icon doesnt change)

What about this one?

**Comment by TheIllusiveC4** [comment]
>> And on top of that, when an item has changed texture via resourcepack, using NBT, like in optifine etc, when its put into the slot >it reverses to the original one, (icon doesnt change)
>
>What about this one?

Can you be more specific about this? And do you mean the texture of the icon is wrong or the rendering of the item is wrong?
