### ISSUE TITLE
[Bug]: java.lang.Noclassdeffounderror:

### ISSUE THREAD

**Issue by Krimatoria** [TheIllusiveC4/Curios#379]
### Minecraft Version

1.19.2

### What happened?

I repeat, when you enable mods in the CurseForge application. The Aether has not enabled the Curious API
![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/8e532084-678c-4333-8406-64349ae5c2c4)

Cataclysm Mod (cataclysm) has failed to load correctly
java.lang.Noclassdeffounderror:
top/theillusivec4/curios/api/type/capability/ICurioItem

Initially, I just included this entire list of mods in the Forge, but the Curious API + Cumulus were not automatically enabled when The Aether was turned on 

I wouldn't have noticed this if I hadn't removed Aether. I don't quite understand what it all means, I just decided to make a branch with this problem.

![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/29b26756-f65c-426a-98e0-d9bcb28bd49a)

### How do you trigger this bug?

If you remove The Aether mod [aether-1.19.2-1.2.0- forge.jar] from this list, the build starts with an error indicating an error:

Cataclysm Mod (cataclysm) has failed to load correctly
java.lang.Noclassdeffounderror:
top/theillusivec4/curios/api/type/capability/ICurioItem

You need to enable these mods, but not include libraries for the mod.

![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/4f59a4a8-59db-4130-9f66-a42fb23f4521)
![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/33a640a3-59b4-462f-896f-129dee1aa980)
![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/0540c79e-e1ad-416a-ba09-0cc27bf565da)
![image](https://github.com/TheIllusiveC4/Curios/assets/106809386/2f685259-f9fe-4204-8bd9-00073367bc71)

If you enable The Aether, then the build magically starts, without libraries and without crash error.

1. endofherobrine-1.19.2-1.0.7.1.jar
2. Fastload-Reforged-mc1.19.2-3.4.0.jar
3. EndlessBiomes 1.4s - 1.19.2 (Server-friendly).jar
4. biomancy-forge-1.19.2-2.3.1.0.jar
5. Lazy DataFixerUpper(LazyDFU) [FORGE]
6. L_Enders_Cataclysm-1.90 tongue fixed-1.19.2.jar
7. born_in_chaos_[Forge]1.19.2_1.10.1.jar
8. Quark-3.4-418.jar
9. AutoRegLib-1.8.2-55.jar
10. gardens-of-the-dead-forge-2.0.1.jar
11. architectury-6.5.90-forge.jar
12. ImmersiveEngineering-1.19.2-9.2.3-167.jar
13. aether-1.19.2-1.2.0-forge.jar
14. citadel-2.1.4-1.19.jar
15. geckolib-forge-1.19-3.1.40.jar
16. embeddium-0.3.0+mc1.19.2.jar
17. embeddiumplus-1.19.2-v1.2.4.jar
18. textrues_embeddium_options-0.1.1+mc1.19.2.jar
19. rubidium-extra-0.4.19+mc1.19.2-build.105.jar
20. supplementaries-1.19.2-2.4.19.jar
21. moonlight-1.19.2-2.3.6-forge.jar
22. modernfix-forge-5.13.0+mc1.19.2.jar23. 

### Loader

Forge

### Loader Version

43.3.5

### Mod Version

curios-forge-1.19.2-5.1.6.1.jar

**Comment by TheIllusiveC4** [comment]
The `NoClassDefFoundError` that you are getting means that a mod is referencing Curios but Curios is not installed. The solution, when this error occurs, is to be sure you've installed and enabled the Curios mod.
