### ISSUE TITLE
[Bug]: mod crash

### ISSUE THREAD

**Issue by TheCoolDave** [TheIllusiveC4/Curios#380]
### Minecraft Version

1.20.1

### What happened?

basically the mod is incompatible with the undergarden newest version but that's on them not you.

### How do you trigger this bug?

1. loading the world

### Loader

Forge

### Loader Version

47.2.20

### Mod Version

5.7.0+1.20.1

### Relevant Log Outputs

![image_2024-02-16_200122268](https://github.com/TheIllusiveC4/Curios/assets/158842133/092f0e85-9669-42ab-93c5-9c1b6856c258)

**Comment by TheIllusiveC4** [comment]
Closing this since it is an Undergarden issue and not Curios, and it looks like they've addressed this already.
