### ISSUE TITLE
[Bug]: Some item disappear after using inventory sorter

### ISSUE THREAD

**Issue by glea94** [TheIllusiveC4/Curios#383]
### Minecraft Version

1.20.1

### What happened?

I use the middle scroll sorting (usng inventorysorter-1.20.1-23.0.1 on the curios inventory and it make the sound as it was sorted but item disappeared.
The backback disappear, hands (1 on 2 slots) , head, necklace, ring (1 on 2 slots).
Belt and neck stay on place.
The inventory wasnt full with item, idk if other like shoes can disappear after sorting.

### How do you trigger this bug?

1.put item in curios
2.press middle scroll to sort
3.item dissapear
...

### Loader

Forge

### Loader Version

47.1.3

### Mod Version

5.7.0+1.20.1

### Relevant Log Outputs

no error or message showing up on the log when i sort inventory.

**Comment by glea94** [comment]
I went to the inventory sorter mod and it seems that in the bugs items disappear when they are stacked, maybe sorting in curios also makes the items disappear. idk..
https://github.com/cpw/inventorysorter/issues
espacially this one talking about curios
https://github.com/cpw/inventorysorter/issues/179

**Comment by TheIllusiveC4** [comment]
Since this affects more mods than just Curios, there's unlikely anything I can do and this must be addressed by Inventory Sorter.
