### ISSUE TITLE
[Bug]: Visibility toggle not appearing on all slots

### ISSUE THREAD

**Issue by MichaelMichelle2** [TheIllusiveC4/Curios#385]
### Minecraft Version

1.20.1

### What happened?

I made a pretty large modpack for myself and a good portion of the slots don't have a visibility toggle.

### How do you trigger this bug?

1. Open Curios Menu
2. Look at trinkets
3. More than 60% do NOT have visibility toggle
...

### Loader

Forge

### Loader Version

Forge - 47.2.18

### Mod Version

curios-forge-5.7.0+1.20.1.jar

**Comment by TheIllusiveC4** [comment]
This is usually caused by a mod that specifically disables the visibility toggle when they add their slots. You'll need to remove some mods that add or edit slots and find out if any of them are doing that.
