### ISSUE TITLE
[Bug]: Problem with a Plugin

### ISSUE THREAD

**Issue by SoyJetixXD** [TheIllusiveC4/Curios#386]
### Minecraft Version

1.18.2

### What happened?

**Hello! Pleased to meet you!**
As you have already imagined, this is an incompatibility with the famous SkinsRestorer plugin, similar to #154 and #131.
At first I wanted to report it in version **1.16.5**, since this is where I discovered the incompatibility when organizing a server with my friends and of course its mod is essential.
But it won't let me report it in that version, I imagine it's because it's very old, I hope one day they support it :).
Returning to the main thing, I complied with what was required because the incompatibility persists in **1.18.2** so I reported it taking this version.
I know that your job is not to fix the plugins, but maybe you can find a way to coexist with SkinsRestorer.
Of course, I'm using _**MOHIST.**_
Thanks for reading...

### How do you trigger this bug?

1.Create a server using Mohist.
2.Install the mods and plugins
3.Start the server and change your skin
4.Well I have Treasure2 installed and I can't place the objects in the Curios menu
5.**Let's cry**
https://www.youtube.com/watch?v=PFdXTNG0UzU

### Loader

Forge

### Loader Version

forge-40.2.17

### Mod Version

curios-forge-1.18.2-5.0.9.2

### Relevant Log Outputs

Check this https://www.youtube.com/watch?v=PFdXTNG0UzU

**Comment by TheIllusiveC4** [comment]
This incompatibility isn't something I can fix, plugins exist in a wholly different environment than mods and I do not have a way to properly interact with them to resolve this issue.
