### ISSUE TITLE
[Bug]: Dupe items in Curious or removing inventory

### ISSUE THREAD

**Issue by BazZziliuS** [TheIllusiveC4/Curios#390]
### Minecraft Version

1.20.1

### What happened?

Dupe items in Curious or removing inventory

The server is in use https://github.com/IzzelAliz/Arclight/actions/runs/8219893955 or Mohist Version : 1.20.1-604

### How do you trigger this bug?

1. Put on a Ring or a [Sophisticated bag](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
2. Enter the ender world
3. Exit it through the portal or teleport with the command /spawn or /home ([EssentialsX](https://essentialsx.net/))
4. The bag will be in the hotbar after opening Curious, the inventory will be cleared

### Loader

Forge

### Loader Version

Forge 49.0.31

### Mod Version

curios-forge-5.7.0+1.20.1.jar

**Comment by TheIllusiveC4** [comment]
You'll need to reproduce this in a pure Forge environment (not a hybrid one like Arclight or Mohist) in order for me to investigate this further. The reason being that if this issue is caused by the hybrid environment itself (or an interaction with a plugin) then there is nothing I can do.

**Comment by BazZziliuS** [comment]
> You'll need to reproduce this in a pure Forge environment (not a hybrid one like Arclight or Mohist) in order for me to investigate this further. The reason being that if this issue is caused by the hybrid environment itself (or an interaction with a plugin) then there is nothing I can do.

I double-checked in the single player game and it also bugs

**Comment by TheIllusiveC4** [comment]
Okay, can you verify that this issue occurs in a pure Forge environment with _only_ Curios and Sophisticated Backpacks installed (and no other mods or anything else) and following the reproduction steps you outlined above?

**Comment by BazZziliuS** [comment]
> Okay, can you verify that this issue occurs in a pure Forge environment with _only_ Curios and Sophisticated Backpacks installed (and no other mods or anything else) and following the reproduction steps you outlined above?

As I said earlier, I checked in a single player game and this bug worked there
Or do you want me to drop something?

**Comment by TheIllusiveC4** [comment]
I know but I assume that you have other mods and such installed as well. I'm asking to verify this issue occurs in a minimal testing environment, using only Curios and Sophisticated Backpacks and nothing else installed and reproducing the bug that way. If you have any other mods and such installed, remove them for this purpose. It's to isolate any potential mod conflicts that could be causing this.

**Comment by BazZziliuS** [comment]
Well, I checked on a clean build with a couple of mods and didn't find this bug.
For the sake of interest, I deleted DivineRPG in the build in which I tested initially and it stopped bugging
I'm sorry for disturbing you
