### ISSUE TITLE
[Bug]: Duplicate Capability Key

### ISSUE THREAD

**Issue by SaltSouls** [TheIllusiveC4/Curios#392]
### Minecraft Version

1.20.1

### What happened?

This isn't causing any bugs, but I believe this may be the cause of the Invalid Playerdata when trying to join a world for the first time.

### How do you trigger this bug?

1. Create a world
2. Join world
3. Save and exit world
4. Attempt to rejoin
5. Get kicked for invalid data
6. Attempt to join again
7. Success

### Loader

Forge

### Loader Version

1.20.1-47.2.21

### Mod Version

5.7.2-1.20.1

### Relevant Log Outputs

[Latest.log](https://gist.github.com/SaltSouls/2dc0c2d28d6b8e2a0d3a2a5eec7c8bdf)
[Debug.log](https://gist.github.com/SaltSouls/0e6a01034006c5eb21af18bc5d373de6)

**Comment by TheIllusiveC4** [comment]
Does this happen with only Curios loaded?

I also noticed that you have Sinytra Connector installed, does this happen if you remove it?

**Comment by dabomb6405** [comment]
I am getting this same issue when trying to run the latest version of Beans Backpacks.

**Comment by LegendarySpy** [comment]
I get the same issue but mine just full on crashes the server, this is the beginning of a very long crash log, for me it crashes with elytra slot enabled, if its disabled it works fine:


[ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Duplicate Capability Key: curios:item com.illusivesoulworks.elytraslot.ElytraSlotForgeMod$1@30e36fc9

**Comment by TheIllusiveC4** [comment]
Are either of you running Sinytra Connector as well?

**Comment by LegendarySpy** [comment]
I am not

**Comment by TheIllusiveC4** [comment]
Usually this is a result of multiple mods trying to add the same capability to an item. My suggestion is to try and remove mods in order to isolate which ones are conflicting with each other. In addition, it may be beneficial to begin with a bare minimum environment with just Curios API and a couple other mods to verify if it's a Curios bug.
