### ISSUE TITLE
[Bug]: Cannot Add Mod Items to Datapack for Additional Slots in 1.19.2

### ISSUE THREAD

**Issue by arlight1** [TheIllusiveC4/Curios#394]
### Minecraft Version

1.19.2

### What happened?

Following the "How to Use: Users" guide to add more slots into my personal modpack, I can do the example "egg" slot, but any modded items don't work using the same steps. The slot gets added to the list, but mod items never get registered after being listed in their respective jsons. For instance, just one example, a "Battery" slot was added in the .toml and a "Battery.json" was created which added the registry name of the IntegratedDynamics battery:
![image](https://github.com/TheIllusiveC4/Curios/assets/30439252/15b91a14-3608-46ca-844b-42f7a38d02d4)

I've attempted many mod items. A "datapack" slot for AE2 Crafting Terminal, a "battery" with several RF cells from various mods, and a "chalice" slot for evilcraft's chalice.

### How do you trigger this bug?

1. Attempt to add any mod's items to curios slots
2.
3.
...

### Loader

Forge

### Loader Version

43.3.5

### Mod Version

Curios API 1.19.2-5.1.6.1

### Relevant Log Outputs

n/a

**Comment by TheIllusiveC4** [comment]
You need to lowercase your tag file name (i.e. "Battery.json" -> "battery.json").

**Comment by arlight1** [comment]
That worked perfect, thank you!
Should the wiki page be updated to include that it needs to be lowercase?

**Comment by TheIllusiveC4** [comment]
Sure, updated it just now to make it clearer.
