### ISSUE TITLE
[Bug]: Game crash with Simple hats on newest version

### ISSUE THREAD

**Issue by ALainxD** [TheIllusiveC4/Curios#398]
### Minecraft Version

1.20.1

### What happened?

Game crashes
[crash-2024-04-16_18.56.28-client.txt](https://github.com/TheIllusiveC4/Curios/files/15000465/crash-2024-04-16_18.56.28-client.txt)

### How do you trigger this bug?

New Instance
Forge 1.20.1
Forge 47.2.23
Install newest Curios API
Install newest Simple Hats
Make creative world
Give yourself a hat
Shift right click it in your survival inventory

-> Game crashes
[crash-2024-04-16_18.56.28-client.txt](https://github.com/TheIllusiveC4/Curios/files/15000465/crash-2024-04-16_18.56.28-client.txt)

### Loader

Forge

### Loader Version

47.2.23

### Mod Version

curios-forge-5.8.1+1.20.1.jar

### Relevant Log Outputs

https://pastebin.com/m2znETaT

**Comment by ALainxD** [comment]
btw not a simple hats issue, worked fine on 5.7.2+1.20.1.jar

**Comment by TheIllusiveC4** [comment]
It is a Simple Hats issue, as they are accessing and using mixins on internals from Curios that are liable to change. It's crashing because those are now outdated. They'll need to either update their compatibility to match the newer version or, potentially, switch to API methods for better stability.

**Comment by kinifox** [comment]
Hey, actually this was my issue. But I can´t exactly understand, what I can do now to fix my issue.

**Comment by TheIllusiveC4** [comment]
As of now, you either need to wait for Simple Hats to make an update to fix this or downgrade Curios to 5.7.2.
