### ISSUE TITLE
[Bug]: Game crashes when I attempt to open curios on personal modpack

### ISSUE THREAD

**Issue by Bobapplesims** [TheIllusiveC4/Curios#399]
### Minecraft Version

1.20.1

### What happened?

What I expected: 
- Open Curios menu
- Equip Curio or Hat from Simple Hats

What happened:
- Press Curios menu button
- Game crash

Something that also happened:
- Atempted to equip Hat from Simple Hats by right clicking while holding the item, expecting it to slot onto Cosmetic Head slot of Curios
- Game crash

### How do you trigger this bug?

1. Have Curios installed
2. Atempt to open Curios menu
3. Alternatively, atempt to equip item that goes into curios slot by right clicking the held item

I have multiple other mods installed, but it is specifically giving me a curios error. I cannot see other mods being called out in the crash log, but it is hard for me to read code.

### Loader

Forge

### Loader Version

Forge - 47.2.0

### Mod Version

curios-forge-5.8.1+1.20.1

### Relevant Log Outputs

https://gist.github.com/Bobapplesims/5e00969bdd11c738bacef16b3ffd44b4#file-crash-2024-04-19_13-48-58-client-txt

**Comment by TheIllusiveC4** [comment]
This is a Simple Hats issue, they need to update their compatibility to match the internal changes they were trying to access in Curios.

**Comment by Bobapplesims** [comment]
Ah, alright then, thank you! So sorry to have bothered you!
