### ISSUE TITLE
Single player crash when starting a new world. NPE - Ticking memory connection

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Curios#4]
Crash
https://gist.github.com/ProsperCraft/026e81fa7a27388f63a836cd480aa277
Log
https://gist.github.com/ProsperCraft/018f6e4ae36b2068038ffcba75509a26

**Comment by TheIllusiveC4** [comment]
Sorry, I can't reproduce this issue. I start a new world and everything works fine, no crashes.
Is this repeatable for you? Can you list your versions and your steps exactly?
Is this repeatable without any other mods present?

**Comment by TheIllusiveC4** [comment]
This is caused by ArtemisLib.

**Comment by CammiePone** [comment]
Can I request a mod list? From everything we've been able to tell, including from other modders, we've done everything right, so I'd like to double check that it is ArtemisLib's fault.

**Comment by TheIllusiveC4** [comment]
I can reproduce the crash with just:
ArtemisLib 1.13.2-1.0.3
Curios 1.13.2-0.9
Forge 1.13.2-25.0.100

So it's either an ArtemisLib issue, a Curios issue, or a Forge issue. I've stated what I think is the problem in the issue I opened on the ArtemisLib repo, but it's entirely possible that something else is going on that I've overlooked.

**Comment by TheIllusiveC4** [comment]
It should be noted that there's an issue on CarryOn's repo with the same crash behavior: https://github.com/Tschipp/CarryOn/issues/161

There's no full mod list but the list of resources loaded in the crash log shows ArtemisLib is loaded but Curios is not, isolating the problem further.

**Comment by CammiePone** [comment]
Aye, we've verified that this is an ArtemisLib issue. Xzero found a way to fix it, and is currently working on some other tweaks to the 1.13 build of ArtemisLib.
