### ISSUE TITLE
[1.15.1] Can't close Curios Slots after Opening in some modes

### ISSUE THREAD

**Issue by realTIMematrix** [TheIllusiveC4/Curios#40]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-FORGE-1.15.1-2.0-beta.jar
* Forge: forge-30.0.41
#### Observed Behavior:
After open Curios Slots it is not possible to close this again. And also the tooltips of the slots are not shown. Also you can not put items in there
#### Expected Behavior:
No matter which Gui-Scale or Fullscreen on/off should close the slots or add some items.
#### Steps to Reproduce:
1. Turn in Graphic Options "Fullscreen OFF" and "GUI-Scale: AUTO"
2. Click Curios Button (Curios Slots opens)
3. Try to hoover over slots (no text appears) or to put in Item (not possible)
#### Notes:
Actual Curios is best used with Fullscreen Mode ON, but it seems that this depends on the resolution or game window when it can not be open.
Crash Log: No Crashlog

**Comment by TheIllusiveC4** [comment]
What launcher are you using?

**Comment by realTIMematrix** [comment]
Using Twitch and this uses the normal Minecraft Launcher

**Comment by TheIllusiveC4** [comment]
I've personally found that only Twitch has this weird bug. Can you try using the vanilla launcher or just anything else other than Twitch and see if the problem persists? Because if it truly is just a Twitch problem, then it's out of my hands.

**Comment by realTIMematrix** [comment]
The Minecraft Launcher has the same behavior.

I download Forge 30.0.41 direct from Forge Website and install it in the Original Minecraft Folder.

i've checked the Javaw.exe versions and both Vanilla and Twitch uses the same Java executable. Another Point is that if the screen resolution in the Launcher on a fixed value (e.g 1024 x 768) and not "automatic" you can reproduce the problem.

Start your vanilla Launcher with 1024 x 768 and check the video settings ingame. The GUI Scale has to be "AUTO" and Fullscreen OFF (windowed mode). You can see this if your video settings need to be scrolled down or up to see all the settings. Then you can reproduce the behavior

If you have the "AUTO" Settings "ON" you can switch with F11 between Fullscreen ON or Windowed. Only in Windowed Mode the API Butten can't be clicked. in Fullscreen it worked fine.

**Comment by TheIllusiveC4** [comment]
Are you using any other mods when testing this? Because I cannot reproduce this behavior. I normally play Minecraft at 1024 x 768 (or something like that) windowed mode, so this is just my normal development setting. Everything works fine for me.

**Comment by realTIMematrix** [comment]
That is really wired. Sure, at the first i start to use it with other mods but this final tests were done with forge and curios only and of course a clean profile and not using the twitch launcher.
Anyway if you cannot reproduce it there is no way for me to show it to you, so you can close it or investigate later when other users mention this issue. :-)

**Comment by realTIMematrix** [comment]
Are you working on a 1.15.2 port? Actual i can't use it and still want to create my own pack under 1.15.2 with Forge.

**Comment by TheIllusiveC4** [comment]
Sorry I never answered you. Just in case you were unaware, there has been a 1.15.2 port released since the time that you asked.
