### ISSUE TITLE
[Bug]: Ifinity backpack (Industrial Foregoing) Not working on added slot

### ISSUE THREAD

**Issue by ErikolGamer14** [TheIllusiveC4/Curios#404]
### Minecraft Version

1.20.1

### What happened?

Item is not functioning as expected when ussing it on an added slot
-I added an extra back slot by using command (/curios add back player) So I can use 2 backpacks at the same time (Sophisticated backpacks and Industrial foregoing) 

- The infinity backpack has 3 functions
  - Pickup items to get stored
  - Refill items on the inventory
  - Magnet items to player inventory or backpack (if filtered to be picked up)

-Magnet is woking but not placing the item to the backapackpack even if filtered to do, pickup isn't working neither but refill is working properly.
-Backpack hotkey isn't working when on added back slot.

- This was working on a previous version of Curious (5.7.2 for MC1.20.1)

### How do you trigger this bug?

1. Clean instalation, added mods (Industrial foregoing,Titanium core and curious API)
2. Execute "/curios add back player" command
3. Put the ifinite backpack on the new slot
4. Test infinite backpack functionalities

This was done on a

### Loader

Forge

### Loader Version

47.2.20

### Mod Version

curios-forge-5.9.0+1.20.1

Bug reported to Industrial Foregoing as well.

**Comment by TheIllusiveC4** [comment]
This is most likely because, from what I can tell, Industrial Foregoing only checks the _first_ index of the back slot for the backpack and so functionality in other indices will not work.

> This was working on a previous version of Curious (5.7.2 for MC1.20.1)

Are you certain this is the case? When I tested on that version, the keybinding still doesn't work when the backpack is placed in a slot other than the first one.

**Comment by ErikolGamer14** [comment]
> Are you certain this is the case? When I tested on that version, the keybinding still doesn't work when the backpack is placed in a slot other than the first one.

I double checked this, my bad, you're right this isn't working on any version of Curios.

**Comment by TheIllusiveC4** [comment]
In that case, this will likely need to be settled on Industrial Foregoing's end.
