### ISSUE TITLE
[Bug]: Copy eqipped items after respawning

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TheIllusiveC4/Curios#405]
### Minecraft Version

1.20.1

### What happened?

The items in Curios API's GUI will be copied after respawning.

### How do you trigger this bug?

1. Set `keeyInventory` to `true`;
2. Equip an item in Curios slot;
3. Run `/kill` command;
4. Click `Respawn` button;
5. The item was copied.
![2024-05-01_10 42 40](https://github.com/TheIllusiveC4/Curios/assets/37864486/b6a5c29e-eb5c-4a1a-8e9b-5e4f1c56f772)

### Loader

Forge

### Loader Version

47.2.30

### Mod Version

5.9.0+1.20.1

### Relevant Log Outputs

[mod list](https://bytebin.lucko.me/lKBWJF494E)
[latest.log](https://github.com/TheIllusiveC4/Curios/files/15173017/latest.log)

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this with just Curios (and Artifacts). Setting `keepInventory` to `true` and then dying/respawning does not duplicate items. Please try it out yourself with _only_ Curios and one other mod that adds a curio slot/item. If this only happens with your mod list, then it's likely a mod conflict with another mod.

**Comment by Enphyum** [comment]
it seems like this is caused by [DivineRPG ](https://www.curseforge.com/minecraft/mc-mods/official-divinerpg)
