### ISSUE TITLE
[Bug]: "/clear"command cannot clear irons-spells-n-spellbooks mod's magic book

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/Curios#406]
### Minecraft Version

1.20.1

### What happened?

As title,the "/clear" command cannot clear irons-spells-n-spellbooks mod's magic book on bauble slot.
And i also asked their's author,they answered this is an issue with curios, the mod that adds the extra slots.

### How do you trigger this bug?

1.Equip a magic book on bauble slot.
2.Run "/clear" command.
3.The all bauble has cleared,but magic book haven't been cleared!
![The_magic_book_have_not_cleared](https://github.com/TheIllusiveC4/Curios/assets/115908948/d345444f-30fe-42b1-a512-247bf0dc0c1e)

### Loader

Forge

### Loader Version

1.20.1-47.2.30

### Mod Version

5.9.0+1.20.1

### Relevant Log Outputs

NONE

**Comment by TheIllusiveC4** [comment]
Curios has its own `/curios clear` command for clearing its inventory.
