### ISSUE TITLE
[Bug]: the game crashes with the last version of embeddium++

### ISSUE THREAD

**Issue by 0Trinster0** [TheIllusiveC4/Curios#408]
### Minecraft Version

1.19.2

### What happened?

[crash-2024-05-14_19.48.44-client.txt](https://github.com/TheIllusiveC4/Curios/files/15315022/crash-2024-05-14_19.48.44-client.txt)

[latest.log](https://github.com/TheIllusiveC4/Curios/files/15315026/latest.log)

### How do you trigger this bug?

only when I enter my world does the game crash

### Loader

Forge

### Loader Version

1.19.2 - 43.3.13

### Mod Version

radiantgear-forge-2.0.3+1.19.2.jar

**Comment by TheIllusiveC4** [comment]
This is the Curios issue tracker, you should be reporting this on Radiant Gear's issue tracker.

**Comment by 0Trinster0** [comment]
I can't find it, could you please redirect me?

**Comment by TheIllusiveC4** [comment]
https://github.com/illusivesoulworks/radiantgear/issues
