### ISSUE TITLE
Bug when using Ensorcellation and Curio API together

### ISSUE THREAD

**Issue by Erfurt92** [TheIllusiveC4/Curios#41]
Hey, I just want to let you know. There seems to be a bug with the Soulbound Enchant from Ensorcellation, when I'm using Curio API, if you have anything equipped in a Curio slots, doesn't matter if it's enchanted with Soulbound or not, all Soulbound items drops when you die, they also looses the enchant, although not all the time it would seem. I'm using the 1.15.2-2.0-beta2 versions of Curio, 1.15.2-0.3.0b version of Ensorcellation, and Forge 31.1.16. I have talked with KingLemmingCoFH about it, and he said "_Yeah, that's 100% on their end._", although it seem to bug out their mod with some configs not going through, but what do I know.

**Comment by MrCrayfish** [comment]
I'm not the author of Curios but this is not TheIllusive's fault. Curios API isn't going to check for an enchantment from a random enchantment mod. All they can do is add a hook for developers to apply a predicate if an item should drop then it's up to KingLemmingCoFH to support it.

**Comment by TheIllusiveC4** [comment]
It's a priority issue. The problem is solvable on either end, but I have to assume they have a good reason for having it as they do so I just handled it on my side.

That said, the Soulbound enchantment randomly getting lost is reproducible with only Ensorcellation and CoFH Core installed so that issue is something you'll have to talk about with the developer.

**Comment by Erfurt92** [comment]
> I'm not the author of Curios but this is not TheIllusive's fault. Curios API isn't going to check for an enchantment from a random enchantment mod. All they can do is add a hook for developers to apply a predicate if an item should drop then it's up to KingLemmingCoFH to support it.

Don't get me wrong I assumed the same as you, that was why I reported it to KingLemmingCoFH first :)
