### ISSUE TITLE
[Bug]: The game crashed when i die

### ISSUE THREAD

**Issue by super-crystal** [TheIllusiveC4/Curios#413]
### Minecraft Version

1.20.1

### What happened?

When I died in game,the game would crush.If I didn't use any slot,the crash would not happen.

### How do you trigger this bug?

1.I have tried different versions (5.3.5/5.9.1/5.9.0/5.8.1) of curios api
2.I have tried unequiping my facilities and it works,but I need them.
3.
...

### Loader

Forge

### Loader Version

Forge 47.2.0

### Mod Version

Curios 5.9.1/5.9.0/5.8.1+1.20.1

### Relevant Log Outputs

https://mclo.gs/QXf0Q90

This web records crash report.

**Comment by TheIllusiveC4** [comment]
Can you try removing Keep Curios Inventory and see if that changes anything?

**Comment by super-crystal** [comment]
I have tried it,but it didn't work.There is no gamerule "keep curios inventory",so I can only turn off keepinventory,but it didn't change anything.

**Comment by super-crystal** [comment]
The game still crashed and I lose all the things in my inventory(they disappeared)except facilities in slots no matter I turned on or off keepinventory.

**Comment by TheIllusiveC4** [comment]
> I have tried it,but it didn't work.There is no gamerule "keep curios inventory",so I can only turn off keepinventory,but it didn't change anything.

I meant that you have a mod installed called "Keep Curios Inventory". Not a gamerule. And I'd like for you to uninstall that mod and see if that changes anything.

**Comment by super-crystal** [comment]
It works!Thx a lot.😭😭😭
