### ISSUE TITLE
[Bug]: Diet Button Disappears When Using New Curios Menu

### ISSUE THREAD

**Issue by evanbones** [TheIllusiveC4/Curios#418]
### Minecraft Version

1.20.1

### What happened?

Since the release of Curios Menu V2, the Diet button disappears in the inventory. When set to legacy mode, the Diet compatibility works again.

### How do you trigger this bug?

1. Open curios menu with Diet installed (in survival)
2. Diet button disappears

### Loader

Forge

### Loader Version

47.3.1

### Mod Version

5.9.1-1.20.1

**Comment by TheIllusiveC4** [comment]
This should be on the Diet issue tracker instead.
