### ISSUE TITLE
Curio Slots Missing

### ISSUE THREAD

**Issue by ColossalKnight13** [TheIllusiveC4/Curios#42]
#### Versions (Be specific, do not write "latest"):
Curios:
- curios-FORGE-1.14.4-1.0.6.1
- curioofundying-FORGE-1.14.4-2.0.1
- curiouselytra-FORGE-1.14.4-1.0
- curiousshulkerboxes-FORGE-1.14.4-1.0.0.1
- EnigmaticLegacy-1.6.4 (utilizes curio)

Forge: 1.14.4-forge-28.2.0

#### Observed Behavior:
 I launch Minecraft with the mods and curios only gives me two ring slots and a backpack slot.
#### Expected Behavior: 
I expected there to be slots for the totem, elytra, and the spell stone.
#### Steps to Reproduce: 
Launch Minecraft with the mods.

**Comment by TheIllusiveC4** [comment]
I can't reproduce this. Launching a fresh instance with just those mods installed, I get one back slot and one charm slot. As far as I'm aware, this is the correct behavior as the elytra uses the back slot, the totem uses the charm slot, and Enigmatic disables everything else at the beginning.

Are you using just those mods or are there other ones? And have you tried reproducing this in a fresh instance?

**Comment by ColossalKnight13** [comment]
@TheIllusiveC4 Okay so going back and just testing in creative, I realize that yea, in the beginning, the other slots are not there until you actually receive an item to fill it. I thought it was bugged sorry. Thanks though. Once again, sorry if this was pointless.
