### ISSUE TITLE
[Bug]: Curios accessories do not show Quark's custom enchant glint

### ISSUE THREAD

**Issue by SeveringHams** [TheIllusiveC4/Curios#423]
### Minecraft Version

1.20.1

### What happened?

Curios accessories do not show Quark's custom enchantment glints on the player model, despite the item accepting the Runic Etching templates.

### How do you trigger this bug?

1. Use Quark, Curios, and any Curios mod, like the Aether or Elytra Slot. (For comparison purposes, Elytra Slot would be better)
2. Pick an accessory, like an Elytra, or gloves from the Aether mod.
3. Enchant the accessory. Runic Etchings cannot be applied to unenchanted items.
4. Use a smithing table to apply a Runic Etching smithing template from the Quark mod, with any dye, or no dye to the accessory.
5. Place it in its respective slot.
6. It does not show the custom glint.

Note that if you chose an Elytra, you'd be able to place it onto your chestplate slot and see the glint colour applied properly. 

Another strange, but likely related bug, the Elytra (in the curios slot, when enchanted, regardless of the applied rune) seems to inherit the glint colour from these in this order: Held item, Helmet slot, Boots slot, Leggings slot, Chestplate slot. If the slot is null, it will check the next. If the slot is not null, it uses the glint colour from that item (if the colour is default or if it is unenchanted, it uses default glint)

### Loader

Forge

### Loader Version

Forge - 47.3.1

### Mod Version

Curios 5.9.1+1.20.1

**Comment by SeveringHams** [comment]
![2024-06-16_14 57 26](https://github.com/TheIllusiveC4/Curios/assets/49352616/8fd7c47e-adfb-4961-92f2-358aef6f89ac)
![2024-06-16_14 57 34](https://github.com/TheIllusiveC4/Curios/assets/49352616/cc21ac64-780f-48be-b692-8a9f28f16598)
![2024-06-16_14 57 39](https://github.com/TheIllusiveC4/Curios/assets/49352616/5b854190-4ddd-4e2e-8c38-a129caea5455)

**Comment by SeveringHams** [comment]
Elytra in Curios slot and Aether Netherite Gloves:

![2024-06-16_14 57 26](https://github.com/TheIllusiveC4/Curios/assets/49352616/e09dd325-9680-4240-aa6a-173784bb2362)
![2024-06-16_15 27 51](https://github.com/TheIllusiveC4/Curios/assets/49352616/64a3388a-599f-4bfb-a895-e2318f854af1)
![2024-06-16_15 28 01](https://github.com/TheIllusiveC4/Curios/assets/49352616/245b36f5-6140-4ee4-b63e-262caf92e63a)

**Comment by SeveringHams** [comment]
Elytra in Chestplate slot:
![2024-06-16_15 36 32](https://github.com/TheIllusiveC4/Curios/assets/49352616/6a569136-b578-4e7c-989e-246d8443a822)
![2024-06-16_15 38 27](https://github.com/TheIllusiveC4/Curios/assets/49352616/1b0276de-a72d-47ec-bbbb-33ddc47adfaa)

**Comment by SeveringHams** [comment]
Okay... So Create's goggles works fine with Runic Colouring in its slot, and the Elytra is completely broken... I have no idea if this is even Curios' fault.

**Comment by TheIllusiveC4** [comment]
This is unlikely to be related to Curios directly, as it is up to each mod to implement the rendering involved. Please report this to the Elytra Slot issue tracker for further investigation.

**Comment by SeveringHams** [comment]
my apologies, thank you
