### ISSUE TITLE
[Bug]: While killing entities using better combat and Curios crashes server 

### ISSUE THREAD

**Issue by HatelessHeart** [TheIllusiveC4/Curios#429]
### Minecraft Version

1.20.1

### What happened?

Anything above curios 5.7.2 Will crash the server either killing entities like piglins or anything else. This bug has been present for several months and I tried out the newer versions Hoping that the bug would be fixed but it has still not been fixed so I'm still having to use a lower version of curios. I've tried almost all the versions above this version of Curios.. Only 5.7.2 WONT crash the server. 

### How do you trigger this bug?

1. killing mobs
2. killing piglins
3. falling into the void
...

### Loader

Forge

### Loader Version

47.2.0

### Mod Version

anything above version: 5.7.2 

### Relevant Log Outputs

3 crash reports : 
https://pastebin.com/Af83zqYT
https://pastebin.com/idaUJ29q
https://pastebin.com/XLFFHcbT

**Comment by TheIllusiveC4** [comment]
This is a bug from KeepCuriosInventory, they are using Curios internals that have changed and have not updated to the latest versions. In addition, Curios has its own `keepCurios` setting in the configuration file so the mod is redundant on 1.20.1.

**Comment by HatelessHeart** [comment]
> This is a bug from KeepCuriosInventory, they are using Curios internals that have changed and have not updated to the latest versions. In addition, Curios has its own `keepCurios` setting in the configuration file so the mod is redundant on 1.20.1.

Thank you for the speedy reply. I will try this and configure the curios file. Thank you
