### ISSUE TITLE
[Feature]: Config option for always showing Curios on left of inventory

### ISSUE THREAD

**Issue by java-jambalaya** [TheIllusiveC4/Curios#430]
### What is the new feature or improvement?

This would remove the need for a button to link the vanilla and Curios player inventory, and fix some issues like the sort button and backpack grid from Quark not showing in the Curios inventory.

**Comment by TheIllusiveC4** [comment]
This isn't really feasible on current versions and I'm not developing the mod on newer versions. Changing the code to integrate curio slots directly into the main inventory menu would require a large refactor in how it currently works and it risks destabilizing current integrations or mod behavior.
