### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HUAHU28** [TheIllusiveC4/Curios#433]
### Minecraft Version

1.20.1

### What happened?

Trinkets, accessories, backpacks, and elytra all eject out of my inventory and onto the ground whenever I try to put them in a slot. Only in survival. Everything works fine whenever in creative. I also have lots of mods installed.

### How do you trigger this bug?

1. Be in survival or Adventure mode
2. Place the trinket or accessory into UI.
3. The trinket will eject out of the slot onto the ground.

### Loader

Forge

### Loader Version

47.3.5

### Mod Version

5.9.1

**Comment by TheIllusiveC4** [comment]
If you have a lot of mods installed, this could very well be a result of a mod conflict. Please test this out first in a minimal testing environment with only Curios and a few other mods installed to narrow down the potential interactions involved.

**Comment by HUAHU28** [comment]
The mod causing the issue is Reskillable FORGE. I have no idea why, though.

https://www.curseforge.com/minecraft/mc-mods/reskillable-forge/files/all?page=1&pageSize=20

Sorry for the long reply.

**Comment by HUAHU28** [comment]
Seems the creator of the mod has fixed the issue now and updated the mod.
