### ISSUE TITLE
[Bug]: Unable to change or modify or /clear the custom slots with commands and data packs

### ISSUE THREAD

**Issue by Sul4urx** [TheIllusiveC4/Curios#434]
### Minecraft Version

1.20.4

### What happened?

If you use `/clear`, It will delete all items from your inventory, except for the custom slots added in the curios mod.
This is so annoying, especially when using data packs, because there is no way to remove an item from the curios slot.
You can't use `/item` on the slots as well.

### How do you trigger this bug?

1. Put some items in the curios slot and in the inventory.
2. Use `/clear`.
3. Notice how the items in the inventory are gone, but not in curios.
4. You can also notice how you can't modify the custom slots using `/item`.

### Loader

Forge

### Loader Version

Forge 49.1.0

### Mod Version

Curios Forge 7.4.0+1.20.4

**Comment by TheIllusiveC4** [comment]
This is a list of commands available to Curios, with options for both clearing and replacing slots:
https://docs.illusivesoulworks.com/curios/commands
