### ISSUE TITLE
[Bug]: curios won't add a new slot

### ISSUE THREAD

**Issue by Rebel2890** [TheIllusiveC4/Curios#435]
### Minecraft Version

1.19.2

### What happened?

So I tried to add a slot for the ars nouveau spellbook, but when the server-side config file is added to the files, the game hangs on world creation.

the files i used are attached below; the data and resource packs were loaded via kubejs.

### How do you trigger this bug?

1. Create a pack with Ars Nouveau, KubeJS, KubeJS Ars Nouveau, Patchouli, and Curios API.
2. add the files attached to the KubeJS folder; save for the .toml file which goes into minecraft's defaultconfigs folder
3. create a new world.

[Spellbook Slot(Curios).zip](https://github.com/user-attachments/files/16433475/Spellbook.Slot.Curios.zip)

### Loader

Forge

### Loader Version

Forge 43.4.2

### Mod Version

Curios 5.1.6.3

### Relevant Log Outputs

https://pastebin.com/LJFNr27Z

**Comment by TheIllusiveC4** [comment]
You have `priority = "199"` instead of `priority = 199`. Quotes turns the integer into a string, which won't parse correctly.

**Comment by Rebel2890** [comment]
Thank you, that worked; but I can't use the spell book now, is there a way to relay the keybinds to ars nouveau?

**Comment by TheIllusiveC4** [comment]
No, something like that needs to be done in-code through a mod.
