### ISSUE TITLE
Not compatible with the action pack for “Solid Texture Features”

### ISSUE THREAD

**Issue by sinterde** [TheIllusiveC4/Curios#436]
### Minecraft Version

1.20.1

### What happened?

With the action pack of "Entity Texture Features", the model of the ornament is not unable to adapt to the action

https://github.com/user-attachments/assets/4580b269-2257-480a-b8dc-4ca588d6750b

### How do you trigger this bug?

1. Install "[EMF] Entity Model Features" and "Entity Texture Features"
2. Add "Fresh Moves"Resource Packs

### Loader

Forge

### Loader Version

forge-47.2.0

### Mod Version

curios5.9.1

**Comment by TheIllusiveC4** [comment]
This probably needs to be addressed by Entity Model Features or Entity Texture Features, whichever is adding the extra animations.
