### ISSUE TITLE
More slot width in curios menu

### ISSUE THREAD

**Issue by Drunkender** [TheIllusiveC4/Curios#44]
**Please describe the new feature or change.**

The feature I'm asking for is for the curios menu to be more than 1 slot wide.
2 or 3 by ∞

**Please describe why you want this feature.**

I want this feature be cause when curios gets more mod support it is going to be a chore to scroll through all of the slots. I'm the type of player that adds more slots if i really want them(Extra rings, charms things that make sense). FYI I also play in large GUI mode.

**Comment by TheIllusiveC4** [comment]
My main issue with having it at more than one width is that it creates the possibility of empty space. For instance, if the width is set to 2 slots and there are 3 slots total in your game: there will be 2 slots in the first row, but only 1 slot in the second, leaving empty space where a theoretically 4th slot would be. This seems like it would look bad.

I'd be interested in hearing any alternatives that would solve both issues, or if my issue with it is superfluous.

**Comment by Drunkender** [comment]
You could always make that extra slot a vanity slot. aka visual only. Additionally configurable amount of vanity slots but if there is an odd number of curios slots add a vanity slot to make it even. This would be useful for botania.

**Comment by TheIllusiveC4** [comment]
I've decided against any width lengthening for the time being, as the new cosmetic slots feature in the 1.16.1 port precludes this idea even more as it occupies a second column. Hopefully the addition of persistence to the scroll index in a previous update helps your issue with scrolling a little bit. I'm also always open to any ideas for a more streamlined interface that will address navigation issues.
