### ISSUE TITLE
[Bug]: Toggle visibility JEI

### ISSUE THREAD

**Issue by NikaDLaw** [TheIllusiveC4/Curios#442]
### Minecraft Version

1.20.1

### What happened?

With Jei installed I cant toggle the visibility of the artifacts that i have in the curious inventory for them to not be seen in my body, it would hide jei's gui instead 

### How do you trigger this bug?

1.Open curious inventory 
2.Toggle the visibility of an artifact 
3.
...

### Loader

NeoForge

### Loader Version

Neoforge 21.0.167

### Mod Version

Curios-neoForge-9.0.8+1.21.jar

**Comment by TheIllusiveC4** [comment]
It looks like this is an issue report for 1.21, this repository is only for 1.20.6 and below. Please report this to the proper repository for the mod you downloaded.
