### ISSUE TITLE
[Bug]: Crash-server

### ISSUE THREAD

**Issue by mghunter159** [TheIllusiveC4/Curios#443]
### Minecraft Version

1.20.1

### What happened?

The crash happens at different times, unknown what caused it

### How do you trigger this bug?

It is not known how to get an error

### Loader

Forge

### Loader Version

forge-1.20.1-47.2.20

### Mod Version

curios-forge-5.10.0+1.20.1.jar

### Relevant Log Outputs

https://pastebin.com/USyxUr1X

**Comment by TheIllusiveC4** [comment]
This is a bug from the Keep Curios Inventory mod, which is outdated as it's a native feature in Curios 1.20.1 and above.
