### ISSUE TITLE
[Bug]:net.kdt.PojavLauncher

### ISSUE THREAD

**Issue by EditorArtyom90** [TheIllusiveC4/Curios#446]
### Minecraft Version

1.19.2

### What happened?

I want to get net.kdt.pojavlauncher

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

1.16.1

### Mod Version

1.16.1

### Relevant Log Outputs

Gg

**Comment by TheIllusiveC4** [comment]
This is not an actionable bug report. I'll need some more information about the nature of the issue and how to reproduce it.
