### ISSUE TITLE
[Bug]: 1.20.1 crash during loading

### ISSUE THREAD

**Issue by TheSexyYeti** [TheIllusiveC4/Curios#452]
### Minecraft Version

1.20.1

### What happened?

Not sure what is exactly causing it. But I keep getting a crash involving Curios.

### How do you trigger this bug?

I don't know

### Loader

Forge

### Loader Version

47.3.11

### Mod Version

5.11.0

### Relevant Log Outputs

https://pastecode.io/s/ge8e0c52

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/TheIllusiveC4/Curios/issues/344
This is an issue with the Tiered mod.
