### ISSUE TITLE
[1.15.2] Mod Interaction

### ISSUE THREAD

**Issue by TheUntamed** [TheIllusiveC4/Curios#47]
Curios: 2.0.2.1.
Forge: 31.1.36

When Curios is open other mod's inventory additions like buttons or slots are removed. It would be neat if that wouldn't happen.

![Screenshot_1](https://user-images.githubusercontent.com/48363903/78658708-cdd16300-78ca-11ea-8c02-3658dc4257b2.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/48363903/78658717-d0cc5380-78ca-11ea-98d4-6168c4fb065c.jpg)

**Comment by TheIllusiveC4** [comment]
I'm not sure if this is really feasible to fix, but I have an idea I'd like to try first. In order to duplicate this issue properly, I'll need to know which mods are adding those particular buttons in your instance.

**Comment by TheUntamed** [comment]
_Extreme sound muffler (Forge)_ adds the sound box at the top center.
_Quark_ adds the square button on the right center.
_Quickstack_ adds the 2 larger buttons next to the button of _Quark_.
_TrashSlot_ adds the trash can slot.

**Comment by TheIllusiveC4** [comment]
Unfortunately my idea didn't really pan out and I don't think there's any good way to fix this on my end. The mods that add those extra features would have to do the same thing to the Curios GUI that they do to the vanilla inventory GUI.
