### ISSUE TITLE
Recipe Book Server Crash

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/Curios#48]
#### Versions:
* `Curios: v2.0.21`
* `Forge: v31.1.39`
* `Minecraft: v1.15.2`

#### Observed Behavior:
- Pressing the recipe book button while in the Curios Gui will crash the game client side while on a server.
#### Expected Behavior:
- Recipe Book Gui should open w/o crashing.
#### Steps to Reproduce:
1. Open Curios Gui
2. Press Recipe Book Button
3. Crash
...

Crash Log: [Link](https://gist.github.com/WenXin20/d8e4e7f679b62c8710acf1673cb8bd31)

**Comment by TheIllusiveC4** [comment]
In your environment, does the recipe book button work fine in the vanilla inventory GUI?

**Comment by WenXin20** [comment]
Yeah, it's only in the curios inventory that it crashes.

**Comment by TheIllusiveC4** [comment]
Hmm, what about in the crafting table GUI?

I can't reproduce this in my environment, everything works fine, so could you try to reproduce this without any other mods? At this juncture, this looks like a compatibility issue but I'm not sure which mod could be the cause and I'm not sure if this strictly needs a dedicated server to reproduce.

**Comment by TheIllusiveC4** [comment]
I had to rewrite the recipe book GUI implementation anyways, so I _think_ that'll solve this issue. But do let me know if it doesn't and I'll re-open it.

**Comment by WenXin20** [comment]
Thanks! I'll be sure to do that!
