### ISSUE TITLE
Render Quark sort buttons on Curios UI

### ISSUE THREAD

**Issue by vico93** [TheIllusiveC4/Curios#51]
Seems like when you press the curios icon and the additional slots are shown the [Quark](https://www.curseforge.com/minecraft/mc-mods/quark) items for sort and such dissapear, if i'm not guessing wrong they arent being "inherited" to the Curious's Inventory UI.

Is possible to make them appear in there too (respecting Quark config)?

Screenshots detailing the issue:

Vanilla inventory screen - notice the small icon (sort) in the far right above the inventory slots
![2020-06-05_23 20 44](https://user-images.githubusercontent.com/3485505/83934080-531aac00-a784-11ea-8991-de81d7668d87.png)

And when i click on the Curios icon to reveal the curios slots the button is gone:
![2020-06-05_23 20 46](https://user-images.githubusercontent.com/3485505/83934090-67f73f80-a784-11ea-9f1f-1c259eedf078.png)

Anyway i'm opening this in both repositories because i'm not sure what side need to make it - sorry if its not your responsibility.

Issue on Quark's side: https://github.com/Vazkii/Quark/issues/2200

And thanks for this amazing mod!

**Comment by TheIllusiveC4** [comment]
From what I can tell, Quark has a bit more/easier access to the bits of code that's needed to get this compatibility going so I'll say I'll leave this to them unless informed otherwise.
