### ISSUE TITLE
[fabric-1.16.1-0.2] Curio doesn't render on slim playermodel

### ISSUE THREAD

**Issue by florensie** [TheIllusiveC4/Curios#58]
#### Versions (Be specific, do not write "latest"):
* Curios: 0.2
* Forge/Fabric: Fabric
#### Steps to Reproduce:
1. I verified this using the latest CuriosShulkerBoxes from git with version 0.2 of Curios
2. Force the slim playermodel in the dev environment by setting a username that has Alex as default. I set `--username Player230` as run config argument.
3. Equip a shulkerbox and go into third person view

**Comment by TheIllusiveC4** [comment]
Unfortunately, I have a hard time reproducing this issue. It always renders for me. However, I did notice a weird missing refmap issue with the renderer. I've fixed that, so there's a chance that might fix this as well? I've published version 0.3 of Curios, so please try that out and see if this remains an issue.

**Comment by florensie** [comment]
I can confirm that that was the issue. It's working now in 0.3.
Thanks for this!
