### ISSUE TITLE
Slot key bindings

### ISSUE THREAD

**Issue by Adirelle** [TheIllusiveC4/Curios#64]
Hello,

Would it possible to add separate key bindings to use the items in the slots added by Curios ?

Some items have permanent effects (like the [Ring of Attraction](https://www.curseforge.com/minecraft/mc-mods/ring-of-attraction-fabric)) and this works fine. But other items are meant to be used, like the [Ring of the Miner](https://www.curseforge.com/minecraft/mc-mods/ring-of-the-miner-fabric) or the [Kibe's Right of Light](https://www.curseforge.com/minecraft/mc-mods/kibe), and storing them in Curios slot does not allow that.

Note : these mods do not support Curios right away. I have just configured Curios according to your doc to create a ring slot and list the rings.

**Comment by TheIllusiveC4** [comment]
This isn't really feasible from a third-party. The mod that adds the function should be the one to add integration with Curios.
