### ISSUE TITLE
Fabric - Curios 1.16.1-0.5 - Crash on start

### ISSUE THREAD

**Issue by StuffByJimm** [TheIllusiveC4/Curios#69]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.16.1-0.5 
* Forge/Fabric: Fabric
#### Steps to Reproduce:
1. Have Curios installed in mod folder
2. Start Minecraft and hit play
3. Game crashes
...
I'm sorry if Curios is indeed not the culprit, but after an hour of binary testing, I've narrowed it down to this exact mod. The crash log literally says nothing about Curios, yet when Curios is installed, my game crashes on start, but as soon as i take Curios out of my mod folder, the game starts up.
Crash Log: https://pastebin.ubuntu.com/p/cqMY5b5hPF/

**Comment by TheIllusiveC4** [comment]
Is that the full log? Because the log you attached doesn't have any sort of error or crash in it.

**Comment by StuffByJimm** [comment]
That is the complete log, yes. I thought it looked kinda short, but it's
the latest crash log in my folder. Did i maybe do something wrong?

**Comment by TheIllusiveC4** [comment]
I'm not sure, but there's not much I can do if I don't see any crashes in the logs.

Also, have you tried loading it up with JUST Curios to see if that loads fine?

**Comment by StuffByJimm** [comment]
I have not, but I will do just that tomorrow morning, thanks for the
suggestion.

Also, I'll look into a more complete log if i can.
