### ISSUE TITLE
[1.14.3] Player kicked when logging in

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Curios#7]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-FORGE-1.14.3-0.17
* Forge: forge-1.14.3-27.0.53
Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk version .061

#### Steps to Reproduce:
The player says - 
I placed a silent gem's obsidian pillars and placed six different mine/slashs unique pieces(including some curios) to use as a display, left the region came back with another Piller and instant kicked after that it keeps dcing me.

He tried to reproduce in single player but was unable.
...

**Stacktrace in console-** 
https://gist.github.com/ProsperCraft/c82761a9e3b9f1b05271f5448e35a8a9

Full logs-
[latest.log](https://github.com/TheIllusiveC4/Curios/files/3402640/latest.log)
[debug.log](https://github.com/TheIllusiveC4/Curios/files/3402641/debug.log)

Playerfile-

[1cce9717-8e7a-4a90-8fa0-b097bc3c982e.zip](https://github.com/TheIllusiveC4/Curios/files/3402679/1cce9717-8e7a-4a90-8fa0-b097bc3c982e.zip)

**Comment by TheIllusiveC4** [comment]
Do you have a reason to suspect this is Curios? I don't see anything leading to this mod from the stacktrace.

**Comment by ProsperCraft** [comment]
NPE from curios.OnCurioChangEvent onEquipCurioChange ?

**Comment by TheIllusiveC4** [comment]
That is not from my mod, it just subscribes to an event that I post. The whole package is `com.mmorpg_libraries.curios.OnCurioChangEvent`, so you're looking for a mod that has the modid `mmorpg_libraries` or something similar. There's also another NPE from an assumed unrelated listener `ovh.corail.tombstone.event.EventHandler` further down the list, so I suspect that there's something else going on here but I don't have much more insight to offer.

If that's all, I will be closing this issue as it likely requires a third-party resolution. If you have other reasons to suspect that Curios is causing this, I'd be happy to hear them and re-open the issue.
