### ISSUE TITLE
Forge/1.16.2 Crash on world start

### ISSUE THREAD

**Issue by qodeninja** [TheIllusiveC4/Curios#71]
Client side MC 1.16.2 with latest Forge for 1.16.2 (forge-1.16.2-33.0.59)

https://hastebin.com/kaxasuvede.php

**java.lang.NoSuchMethodError**: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Lnet/minecraftforge/common/util/LazyOptional;
	at top.theillusivec4.curios.common.CuriosHelper.getAttributeModifiers(CuriosHelper.java:153)
	at top.theillusivec4.curios.client.ClientEventHandler.onTooltip(ClientEventHandler.java:127)
....

Removing Curios mod (curios-forge-1.16.2-4.0.0.0.jar) resolved game crashing.

**Comment by Aizistral** [comment]
I have encountered this either. You can use Curios 4.0.0.1, it seems to be compatible with 1.16.2
