### ISSUE TITLE
[Feature] Overlay Rendering

### ISSUE THREAD

**Issue by cech12** [TheIllusiveC4/Curios#73]
**Please describe the new feature or change.**
It would be nice if there will be a possibility to render an overlay when wearing an item in a curio slot. Like the overlay when wearing a carved pumpkin on head. In Forge there is already [a possibility to add it for items wearing in vanilla armor slots](https://github.com/cech12/UsefulHats/blob/32b84ad5c7f09d748138dc7e3314de33c9f786be/src/main/java/cech12/usefulhats/item/AquanautHelmetItem.java#L88) but I cannot find a way to do it for curio slots.

**Please describe why you want this feature.**
My mod ([Useful Hats](https://www.curseforge.com/minecraft/mc-mods/useful-hats)) adds an aquanaut helmet to the game and when on head it renders an overlay ([see here](https://github.com/cech12/UsefulHats/wiki/Aquanaut-Helmet#effects)). Recently I added the support for Curios and I found out that there is no possibility for me to render it when in curios head slot.

**Comment by Aizistral** [comment]
This is a hella specific feature if you'd ask me. But I can try to figure this one out and make a pull request to forge branch on the matter if @TheIllusiveC4 confirms that it totally makes sense in an API.

**Comment by cech12** [comment]
That would be very nice! :)

**Comment by TheIllusiveC4** [comment]
Hmm, it is rather specific. It might be a little too niche. Also, can't you subscribe to the `RenderGameOverlayEvent` (or whatever it's called), listen for the helmet overlay, and render your logic in that? Basically, wherever Forge does their logic for their `IForgeItem#renderHelmetOverlay` method.

**Comment by cech12** [comment]
Okay, I will try to use the `RenderGameOverlayEvent`. Thanks for the hint! :)
