### ISSUE TITLE
can't equip rings into ring slots

### ISSUE THREAD

**Issue by Warbringer12** [TheIllusiveC4/Curios#75]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.16.3-4.0.2.0
* Forge/Fabric: forge 1.16.3-34.1.5
#### Steps to Reproduce:
1. tried equipping ring into ring slot
2. tried other slots to see if they worked belt and body one worked don't know about rest
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
no crash log

**Comment by TheIllusiveC4** [comment]
Which mods do you have installed that add the ring and ring slot?

**Comment by Warbringer12** [comment]
botania adds rings so does gobber2
