### ISSUE TITLE
Incompatibility with Cinderscapes

### ISSUE THREAD

**Issue by Zentheon** [TheIllusiveC4/Curios#82]
When both the Curios API and Cinderscapes are loaded at once, the Creative menu never shows any of the vanilla blocks or items.

I doubt it would give any valuable info, but the console log is the only resource I can give (Don't mind the missing structure spam, been testing a lot of mods):
[latest.log](https://github.com/TheIllusiveC4/Curios/files/5435801/latest.log)

**Comment by TheIllusiveC4** [comment]
I believe this may be a Fabric API issue as I've heard of a similar problem with Astromine and Cinderscapes, although I don't know anything about the root cause. In addition, Curios doesn't do anything with item groups so I'm not sure how the mod could cause this behavior in itself.
