### ISSUE TITLE
[1.16.3 FORGE] Item completely disappears when switching from normal inventory to curios inventory in creative mode

### ISSUE THREAD

**Issue by RhSm-Firebird** [TheIllusiveC4/Curios#83]
#### Versions (Be specific, do not write "latest"):

* Curios: v4.0.2.0 for Minecraft 1.16.3
* Forge: v34.1.25 for Minecraft 1.16.3

#### Observed Behavior: When an item is clicked and is being held using the mouse in the regular inventory, switching to the curios inventory by pressing the hotkey or by pressing the curios button on the top left causes the item held by the mouse pointer to vanish. Deleted actually, since I couldn't find it anywhere after that.

Only happens in creative mode. Works fine in survival, nothing disappears.

I feel it is worth mentioning that when switching from curios inventory to normal inventory, the item does not disappear, but is thrown away from the player.

#### Expected Behavior: At the very least make the item not vanish.

Also try to stop the player throwing it away when switching from curios to normal.

The cursor should always retain the item when switching inventory types.

#### Steps to Reproduce:

1. Load a creative world.

2. Put any item in your inventory.

3. Open your normal inventory (not the curios one).

4. Left-Click the item in your inventory so that the cursor is now holding it, waiting for you to place it in another slot.

5. Without placing the item in any slot, press the curios hotkey or the curios button.

6. The item that the cursor was holding should have been deleted.

Note: This is especially irritating when grabbing an item from the creative menu and wanting to directly place it in a curios slot without placing it in the normal inventory since the item keeps disappearing.

Crash Log: There was no crash, but here is the latest.log anyway: https://pastebin.com/isUN18wq

**Comment by AguZz** [comment]
Hi, is there any update on this issue? Still having this bug (specifically, with the Sophisticated Backpack mod) on:

Versions (Be specific, do not write "latest"):
Curios: v4.0.8.2 for Minecraft 1.16.5
Forge: v36.2.39 for Minecraft 1.16.5
