### ISSUE TITLE
Can't equip anything in the slots you have to scroll for

### ISSUE THREAD

**Issue by Ranaida** [TheIllusiveC4/Curios#84]
#### Versions (Be specific, do not write "latest"):
* Curios: 1.16.3-4.0.2.0
* Forge/Fabric: forge 1.16.3-34.1.25

#### Observed Behavior:
At first, everything worked as it should. After a few gaming sessions I wanted to change the equipped ring, only to realise that I can not equip anything new in this slot.

At this time I can't say what changed between the time it worked and the time it didn't. I think I died because of one stupid mod I deleted after (something that just add animals). 

So I tried out, but none of the mods I installed (Botania, Enigmatic Legacy, Rings of Ascension, ...) and use curios can equip anything in the slots you have to scroll down for (for example: Backpack is totally fine, amulets not).
For some reason I believed that the grey square in the top right of an item slot has to do something with that so I started experimenting and soon I realised something: When I click on the squares without scrolling it always activates (or deactivates? I really don't know) the one I klicked on. But when I scroll down and click on the squares that would be normally hidden it activates the square on one of the upper slots. 

The problem appeared in the old game and in every new one I begin with, no matter what mod I delete or reinstall.

#### Steps to Reproduce:
1. try to equip something from the lower slots
2. try to equip something from the upper slots
3. try to turn on/off the grey squares
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No crash log

**Mods installed (110):**

→     Absent by Design
→     Additional Bars
→     Additional Lights
→     Advanced Chimneys
→     Ambient Sounds
→     Apotheosis
→     Applied Energistics
→     Aquaculture
→     Attribute Fix
→     Autofish
→     Bed Benefits
→     Biomes o Plenty
→     Bookshelf
→ **Botania**
→     Botany Pots
→     Bow Infinity Fix
→     Brick Furnace
→     Builders Crafts and Additions
→     Bundle o Flesh
→     Ceramics
→     Clear Water
→     Cloth
→     Collective
→     Connected Glass
→     Cooking for Blockheads
→     Curios
→     Cycle Paintings
→     Cyclic
→     Decorative Blocks
→     Double Doors
→     Dragon Mounts Legacy
→     Dramatic Doors
→     Dungeon Crawl
→     Enchanted Book Redesign
→     Enchantment Descriptions
→     Engineers Decor
→ **Enigmatic Legacy**
→     EXP Bottling
→     Extended Creative Inventory
→     Fast Leaf Decay
→     Forge Endertech
→     Friendly Fire
→     Fun Items Mod
→     Gauges and Switches
→     Glassential
→     Grass Seeds
→     Greater Eye of Ender
→     Healing Campfire
→     Hwyla
→     Immersive Engineering
→     Infinity Mending
→     Inventory Tweaks Renewed
→     Iron Age Furniture
→     Just Enough Items
→     Sleeping Doogs Lie
→     Light Overlay
→     Lotta Terracotta
→     Lumberjack
→     Ma Enchants
→     Macaws Bridges
→     Macaws Doors
→     Macaws Roofs
→     Macaws Windows
→     Mantle
→     Mine Colonies
→     Multi Beds
→     Natures Compass
→     No Hostiles around Campfire
→     OpenBlocks Elevator
→     Pane in the Glass
→     Paper Books
→     Patchouli
→     Path Under Gates
→     Placebo
→     Player Plates
→     Practical Tools
→     Random Bone Meal Flowers
→ **Reliquiary**
→     Repurposed Structures
→ **Rings Of Ascension**
→     Security Craft
→     Sheti Phian Core
→     Simple Farming
→     Simply Light
→     Sit
→     Spice of Life Carrot Edition
→     Storage Overhaul
→     Structurize
→     Survive
→     Sweet Concrete
→     Sword Display
→     Tesseract
→     Torch Slabs Mod
→     Trample Stopper
→     Travellers Boots
→     U Team Core
→     Uncrafted
→     Union Lib
→     Upsizer
→ **Useful Backpacks**
→     Useful Railroads
→     Valhelsia Structures
→     Villager Names
→     Waystones
→     Windowlogging
→     XP from Harvest
→     Xtray
→     YUNGs Better Caves
→     YUNGs Better Mineshafts

**Comment by Aizistral** [comment]
I can confirm this happens in dev environment with only Curios 4.0.2.0, with only change being enabled `DEBUG` boolean in main class to have some of those slots. Didn't investigate on what could cause this yet, but plan to.

**Comment by Aizistral** [comment]
Okay, it's not all that simple. Trying to reproduce this in fresher fresh instance and equipping stuff into slots works fine. I specifically set Forge version to 34.1.25 and registered whole 16 slots to check this out, got nothing.

This, however:
> For some reason I believed that the grey square in the top right of an item slot has to do something with that so I started experimenting and soon I realised something: When I click on the squares without scrolling it always activates (or deactivates? I really don't know) the one I klicked on. But when I scroll down and click on the squares that would be normally hidden it activates the square on one of the upper slots.

...indeed happens, with impressive persistency.

It would appear that main subject of this issue is likely to be caused by some other mod interference, though I have no idea what mod could possibly cause anything like this and how. The modlist presented by you, @Ranaida, is way too huge to try and go through all of that one by one, so I would advise you to try and reproduce this without any other mods first, registering 9+ slots through Curios config. If doesn't happen - you'll have to continue debugguing with your modpack, splitting your modlist until you nail down the exact mod or mods in whose presence this happens.
