### ISSUE TITLE
[1.14.4] Server crash - 

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Curios#9]
#### Versions (Be specific, do not write "latest"):
* Curios: curios-FORGE-1.14.4-0.18
* Forge: forge-1.14.4-28.0.14

#### Steps to Reproduce:
1. Start The Adventures of Halk pack, .3 on a server and client
2. open the curious slots.

...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://gist.github.com/ProsperCraft/c6195525e3b5da585be9212735c348cd

[debug.log](https://github.com/TheIllusiveC4/Curios/files/3432841/debug.log)
[latest.log](https://github.com/TheIllusiveC4/Curios/files/3432842/latest.log)

**Comment by ProsperCraft** [comment]
Reproduced here - https://paste.fedoraproject.org/paste/qyjg2o-Dr~Rn6aEbgrWtbw

**Comment by ProsperCraft** [comment]
This was caused by the 1.14.3 version of Trashslot-https://paste.fedoraproject.org/paste/ZXshcTD9DdkgztkE1MU5Eg

Once removed, it resolved.

**Comment by TheIllusiveC4** [comment]
Likely an issue with TrashSlot then, as I don't see anything on my end that would cause this error. I'll re-open this if new information comes to light that this is caused by Curios.
