### ISSUE TITLE
Game crashes on command [Server]

### ISSUE THREAD

**Issue by NashieArtz** [TheIllusiveC4/Curios#93]
After hitting spacebar after the word "add" with the command /curios add, the game completely crashes on severs. Singleplayer is fine.
#### Versions (Be specific, do not write "latest"):
* Curios: Curios API 1.16.3-4.0.2.0
* Forge/Fabric: Forge 34.1.42
#### Steps to Reproduce:
1. /curios add
2. hit the spacebar
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/). https://hastebin.com/uvosiyeleb.properties

**Comment by Aizistral** [comment]
It's been fixed in 4.0.3.0. Despite being marked as 1.16.4-only on CurseForge, this release should work fine on 1.16.3 either.

**Comment by TheIllusiveC4** [comment]
I've recently updated the file on CurseForge to reflect that it's compatible with 1.16.3. So, as Extegral said, just update to Curios 4.0.3.0 and that should solve your issue.
