### ISSUE TITLE
[curios forge-1.16.4-4.0.3.0] Crash on world start

### ISSUE THREAD

**Issue by Daejangnamu** [TheIllusiveC4/Curios#96]
[crash-2020-12-28_03.43.04-server.txt](https://github.com/TheIllusiveC4/Curios/files/5745023/crash-2020-12-28_03.43.04-server.txt)

forge version: 1.16.4-35.1.12

**Comment by TheIllusiveC4** [comment]
This is an issue with some mod called Project MMO. You should report this issue to that project instead.
