### ISSUE TITLE
Custom Elytra texture/resource is rendered by the mod

### ISSUE THREAD

**Issue by waliyt2000** [TheIllusiveC4/Curios#98]
When using a texture pack that changes the texture of Elytra ONLY WHEN the name of the Elytra is changed, Curios mod should render it. The texture pack that I am using: https://www.planetminecraft.com/texture-pack/more-elytras-in-vanilla-minecraft-requires-optifine/

The texture for the Elytra changes depending on what you rename it to.

**Comment by TheIllusiveC4** [comment]
I believe you're referring to Curious Elytra, not Curios itself. Either way, this is not something that can be addressed because, as far as I'm aware, there's no way for me to hook into the changed texture.
