### ISSUE TITLE
Boot Slot missing Icon

### ISSUE THREAD

**Issue by slave2midna** [TheIllusiveC4/Curios#99]
#### Versions (Be specific, do not write "latest"):
* Curios: 4.0.3.3
* Forge/Fabric: 35.1.4
#### Steps to Reproduce:
1. Install Curios API with extra mod 'Artifacts'
2. Open Curios inventory and notice the addition of a 'boots' slot, with not icon to show for it.

Not sure this is a bug, or intended - I personally don't see the need for a 'boot' slot as you already have one for armor. But it appears that this mod adds the slot as a blank square for the boots but no actual icon for it. I'm not sure if this is a bug on the mod side, or the Curious side, so I figured I'd start here. Personally still feel that Curios doesn't need a 'boot' slot for its items and this should be an optional slot that can be removed or disabled.

**Comment by TheIllusiveC4** [comment]
Report this to the Artifacts developer, as I have no control over the boots slot.

Also, every Curios slot is optional. Even as a user, you have the option to disable it if it's present.

**Comment by slave2midna** [comment]
Roger that! Thank you!!
